/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InstantApiKeyResponse,
    InstantApiKeyResponseFromJSON,
    InstantApiKeyResponseToJSON,
} from '../models/InstantApiKeyResponse';
import {
    type V1ErrorWrapper,
    V1ErrorWrapperFromJSON,
    V1ErrorWrapperToJSON,
} from '../models/V1ErrorWrapper';

/**
 * 
 */
export class AuthEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createInstantApiKey without sending the request
     */
    async createInstantApiKeyRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/auth/keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Creates a free-tier API key instantly without authentication. The key can be used immediately for all API endpoints. Rate limited to 3 keys per hour per IP. Keys expire after 30 days.
     * Create an instant API key
     */
    async createInstantApiKeyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstantApiKeyResponse>> {
        const requestOptions = await this.createInstantApiKeyRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstantApiKeyResponseFromJSON(jsonValue));
    }

    /**
     * Creates a free-tier API key instantly without authentication. The key can be used immediately for all API endpoints. Rate limited to 3 keys per hour per IP. Keys expire after 30 days.
     * Create an instant API key
     */
    async createInstantApiKey(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstantApiKeyResponse> {
        const response = await this.createInstantApiKeyRaw(initOverrides);
        return await response.value();
    }

}
