/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChainListResponse,
    ChainListResponseFromJSON,
    ChainListResponseToJSON,
} from '../models/ChainListResponse';

/**
 * 
 */
export class ChainEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getChains without sending the request
     */
    async getChainsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all supported blockchain chains with metadata including name, native currency symbol, swap support, and block explorer information.
     * Get supported chains
     */
    async getChainsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChainListResponse>> {
        const requestOptions = await this.getChainsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChainListResponseFromJSON(jsonValue));
    }

    /**
     * Get all supported blockchain chains with metadata including name, native currency symbol, swap support, and block explorer information.
     * Get supported chains
     */
    async getChains(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChainListResponse> {
        const response = await this.getChainsRaw(initOverrides);
        return await response.value();
    }

}
