/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ContractResponse,
    ContractResponseFromJSON,
    ContractResponseToJSON,
} from '../models/ContractResponse';
import {
    type PaymentToken,
    PaymentTokenFromJSON,
    PaymentTokenToJSON,
} from '../models/PaymentToken';

export interface GetContractRequest {
    address: string;
    chain: string;
}

export interface GetPaymentTokenRequest {
    address: string;
    chain: string;
}

/**
 * 
 */
export class ContractEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getContract without sending the request
     */
    async getContractRequestOpts(requestParameters: GetContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getContract().'
            );
        }

        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getContract().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get contract metadata including collection information, contract standards, and ownership details.
     * Get contract
     */
    async getContractRaw(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContractResponse>> {
        const requestOptions = await this.getContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContractResponseFromJSON(jsonValue));
    }

    /**
     * Get contract metadata including collection information, contract standards, and ownership details.
     * Get contract
     */
    async getContract(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContractResponse> {
        const response = await this.getContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPaymentToken without sending the request
     */
    async getPaymentTokenRequestOpts(requestParameters: GetPaymentTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getPaymentToken().'
            );
        }

        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getPaymentToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/payment_token/{address}`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a payment token by chain and contract address.
     * Get payment token
     */
    async getPaymentTokenRaw(requestParameters: GetPaymentTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentToken>> {
        const requestOptions = await this.getPaymentTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentTokenFromJSON(jsonValue));
    }

    /**
     * Get a payment token by chain and contract address.
     * Get payment token
     */
    async getPaymentToken(requestParameters: GetPaymentTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentToken> {
        const response = await this.getPaymentTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
