/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChainIdentifier,
    ChainIdentifierFromJSON,
    ChainIdentifierToJSON,
} from '../models/ChainIdentifier';
import {
    type DropDeployReceiptResponse,
    DropDeployReceiptResponseFromJSON,
    DropDeployReceiptResponseToJSON,
} from '../models/DropDeployReceiptResponse';
import {
    type DropDeployRequest,
    DropDeployRequestFromJSON,
    DropDeployRequestToJSON,
} from '../models/DropDeployRequest';
import {
    type DropDeployResponse,
    DropDeployResponseFromJSON,
    DropDeployResponseToJSON,
} from '../models/DropDeployResponse';
import {
    type DropDetailedResponse,
    DropDetailedResponseFromJSON,
    DropDetailedResponseToJSON,
} from '../models/DropDetailedResponse';
import {
    type DropMintRequest,
    DropMintRequestFromJSON,
    DropMintRequestToJSON,
} from '../models/DropMintRequest';
import {
    type DropMintResponse,
    DropMintResponseFromJSON,
    DropMintResponseToJSON,
} from '../models/DropMintResponse';
import {
    type DropPaginatedResponse,
    DropPaginatedResponseFromJSON,
    DropPaginatedResponseToJSON,
} from '../models/DropPaginatedResponse';
import {
    type V1ErrorWrapper,
    V1ErrorWrapperFromJSON,
    V1ErrorWrapperToJSON,
} from '../models/V1ErrorWrapper';

export interface BuildDropMintTransactionRequest {
    slug: string;
    dropMintRequest: DropMintRequest;
}

export interface DeployDropContractRequest {
    dropDeployRequest: DropDeployRequest;
}

export interface GetDeployContractReceiptRequest {
    chain: string;
    txHash: string;
}

export interface GetDropBySlugRequest {
    slug: string;
}

export interface GetDropsRequest {
    type?: string;
    limit?: number;
    chains?: Array<ChainIdentifier>;
    cursor?: string;
}

/**
 * 
 */
export class DropsEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for buildDropMintTransaction without sending the request
     */
    async buildDropMintTransactionRequestOpts(requestParameters: BuildDropMintTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling buildDropMintTransaction().'
            );
        }

        if (requestParameters['dropMintRequest'] == null) {
            throw new runtime.RequiredError(
                'dropMintRequest',
                'Required parameter "dropMintRequest" was null or undefined when calling buildDropMintTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/drops/{slug}/mint`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DropMintRequestToJSON(requestParameters['dropMintRequest']),
        };
    }

    /**
     * Returns ready-to-sign transaction data for minting tokens from a drop. The caller is responsible for signing and submitting the transaction. No wallet authentication is required — only an API key. The minter address in the request body determines who will receive the tokens. Stage selection is handled automatically by the backend — if multiple stages are active, the first eligible stage is used.
     * Build mint transaction data for a drop
     */
    async buildDropMintTransactionRaw(requestParameters: BuildDropMintTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropMintResponse>> {
        const requestOptions = await this.buildDropMintTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropMintResponseFromJSON(jsonValue));
    }

    /**
     * Returns ready-to-sign transaction data for minting tokens from a drop. The caller is responsible for signing and submitting the transaction. No wallet authentication is required — only an API key. The minter address in the request body determines who will receive the tokens. Stage selection is handled automatically by the backend — if multiple stages are active, the first eligible stage is used.
     * Build mint transaction data for a drop
     */
    async buildDropMintTransaction(requestParameters: BuildDropMintTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropMintResponse> {
        const response = await this.buildDropMintTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deployDropContract without sending the request
     */
    async deployDropContractRequestOpts(requestParameters: DeployDropContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dropDeployRequest'] == null) {
            throw new runtime.RequiredError(
                'dropDeployRequest',
                'Required parameter "dropDeployRequest" was null or undefined when calling deployDropContract().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/drops/deploy`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DropDeployRequestToJSON(requestParameters['dropDeployRequest']),
        };
    }

    /**
     * Returns ready-to-sign transaction data for deploying a new NFT drop contract. The caller is responsible for signing and submitting the transaction.
     * Build deploy contract transaction data
     */
    async deployDropContractRaw(requestParameters: DeployDropContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropDeployResponse>> {
        const requestOptions = await this.deployDropContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropDeployResponseFromJSON(jsonValue));
    }

    /**
     * Returns ready-to-sign transaction data for deploying a new NFT drop contract. The caller is responsible for signing and submitting the transaction.
     * Build deploy contract transaction data
     */
    async deployDropContract(requestParameters: DeployDropContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropDeployResponse> {
        const response = await this.deployDropContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDeployContractReceipt without sending the request
     */
    async getDeployContractReceiptRequestOpts(requestParameters: GetDeployContractReceiptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getDeployContractReceipt().'
            );
        }

        if (requestParameters['txHash'] == null) {
            throw new runtime.RequiredError(
                'txHash',
                'Required parameter "txHash" was null or undefined when calling getDeployContractReceipt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/drops/deploy/{chain}/{tx_hash}/receipt`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{tx_hash}', encodeURIComponent(String(requestParameters['txHash'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check the status of a contract deployment transaction. Returns the deployment status and, on success, the deployed contract address and linked collection slug.
     * Get deploy contract receipt
     */
    async getDeployContractReceiptRaw(requestParameters: GetDeployContractReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropDeployReceiptResponse>> {
        const requestOptions = await this.getDeployContractReceiptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropDeployReceiptResponseFromJSON(jsonValue));
    }

    /**
     * Check the status of a contract deployment transaction. Returns the deployment status and, on success, the deployed contract address and linked collection slug.
     * Get deploy contract receipt
     */
    async getDeployContractReceipt(requestParameters: GetDeployContractReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropDeployReceiptResponse> {
        const response = await this.getDeployContractReceiptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDropBySlug without sending the request
     */
    async getDropBySlugRequestOpts(requestParameters: GetDropBySlugRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getDropBySlug().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/drops/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed drop information for a collection, including stages and supply.
     * Get drop by collection slug
     */
    async getDropBySlugRaw(requestParameters: GetDropBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropDetailedResponse>> {
        const requestOptions = await this.getDropBySlugRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropDetailedResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed drop information for a collection, including stages and supply.
     * Get drop by collection slug
     */
    async getDropBySlug(requestParameters: GetDropBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropDetailedResponse> {
        const response = await this.getDropBySlugRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDrops without sending the request
     */
    async getDropsRequestOpts(requestParameters: GetDropsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['chains'] != null) {
            queryParameters['chains'] = requestParameters['chains'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/drops`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of NFT drops (mints) by type: featured, upcoming, or recently_minted. Results may be fewer than the requested limit due to post-fetch filtering.
     * Get drops
     */
    async getDropsRaw(requestParameters: GetDropsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropPaginatedResponse>> {
        const requestOptions = await this.getDropsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of NFT drops (mints) by type: featured, upcoming, or recently_minted. Results may be fewer than the requested limit due to post-fetch filtering.
     * Get drops
     */
    async getDrops(requestParameters: GetDropsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropPaginatedResponse> {
        const response = await this.getDropsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
