/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AssetMetadataResponse,
    AssetMetadataResponseFromJSON,
    AssetMetadataResponseToJSON,
} from '../models/AssetMetadataResponse';
import {
    type BatchNftsRequest,
    BatchNftsRequestFromJSON,
    BatchNftsRequestToJSON,
} from '../models/BatchNftsRequest';
import {
    type NftAnalyticsResponse,
    NftAnalyticsResponseFromJSON,
    NftAnalyticsResponseToJSON,
} from '../models/NftAnalyticsResponse';
import {
    type NftBatchResponse,
    NftBatchResponseFromJSON,
    NftBatchResponseToJSON,
} from '../models/NftBatchResponse';
import {
    type NftListResponse,
    NftListResponseFromJSON,
    NftListResponseToJSON,
} from '../models/NftListResponse';
import {
    type NftResponse,
    NftResponseFromJSON,
    NftResponseToJSON,
} from '../models/NftResponse';
import {
    type OwnersPaginatedResponse,
    OwnersPaginatedResponseFromJSON,
    OwnersPaginatedResponseToJSON,
} from '../models/OwnersPaginatedResponse';
import {
    type TransferRequest,
    TransferRequestFromJSON,
    TransferRequestToJSON,
} from '../models/TransferRequest';
import {
    type TransferResponse,
    TransferResponseFromJSON,
    TransferResponseToJSON,
} from '../models/TransferResponse';
import {
    type ValidateMetadataResponse,
    ValidateMetadataResponseFromJSON,
    ValidateMetadataResponseToJSON,
} from '../models/ValidateMetadataResponse';

export interface GetNftRequest {
    chain: string;
    address: string;
    identifier: string;
}

export interface GetNftAnalyticsRequest {
    chain: string;
    address: string;
    identifier: string;
}

export interface GetNftMetadataRequest {
    chain: string;
    contractAddress: string;
    tokenId: string;
}

export interface GetNftOwnersRequest {
    chain: string;
    address: string;
    identifier: string;
    limit?: number;
    next?: string;
}

export interface GetNftsBatchRequest {
    batchNftsRequest: BatchNftsRequest;
}

export interface GetNftsByAccountRequest {
    address: string;
    chain: string;
    collection?: string;
    limit?: number;
    nextValue?: string;
}

export interface GetNftsByCollectionRequest {
    slug: string;
    traits?: string;
    limit?: number;
    nextValue?: string;
}

export interface GetNftsByContractRequest {
    address: string;
    chain: string;
    limit?: number;
    nextValue?: string;
}

export interface RefreshNftMetadataRequest {
    address: string;
    chain: string;
    identifier: string;
    ignoreCachedItemUrls?: boolean;
}

export interface TransferAssetsRequest {
    transferRequest: TransferRequest;
}

export interface ValidateNftMetadataRequest {
    chain: string;
    address: string;
    identifier: string;
    ignoreCachedItemUrls?: boolean;
}

/**
 * 
 */
export class NFTEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getNft without sending the request
     */
    async getNftRequestOpts(requestParameters: GetNftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNft().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getNft().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getNft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts/{identifier}`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get metadata, traits, ownership information, and rarity for a single NFT.
     * Get NFT
     */
    async getNftRaw(requestParameters: GetNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftResponse>> {
        const requestOptions = await this.getNftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftResponseFromJSON(jsonValue));
    }

    /**
     * Get metadata, traits, ownership information, and rarity for a single NFT.
     * Get NFT
     */
    async getNft(requestParameters: GetNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftResponse> {
        const response = await this.getNftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftAnalytics without sending the request
     */
    async getNftAnalyticsRequestOpts(requestParameters: GetNftAnalyticsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNftAnalytics().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getNftAnalytics().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getNftAnalytics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts/{identifier}/analytics`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get analytics data for a specific NFT including sales history and floor price history.
     * Get NFT analytics
     */
    async getNftAnalyticsRaw(requestParameters: GetNftAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftAnalyticsResponse>> {
        const requestOptions = await this.getNftAnalyticsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Get analytics data for a specific NFT including sales history and floor price history.
     * Get NFT analytics
     */
    async getNftAnalytics(requestParameters: GetNftAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftAnalyticsResponse> {
        const response = await this.getNftAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftMetadata without sending the request
     */
    async getNftMetadataRequestOpts(requestParameters: GetNftMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNftMetadata().'
            );
        }

        if (requestParameters['contractAddress'] == null) {
            throw new runtime.RequiredError(
                'contractAddress',
                'Required parameter "contractAddress" was null or undefined when calling getNftMetadata().'
            );
        }

        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling getNftMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/metadata/{chain}/{contractAddress}/{tokenId}`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{contractAddress}', encodeURIComponent(String(requestParameters['contractAddress'])));
        urlPath = urlPath.replace('{tokenId}', encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed metadata for an NFT including name, description, image, traits, and external links.
     * Get NFT metadata
     */
    async getNftMetadataRaw(requestParameters: GetNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetMetadataResponse>> {
        const requestOptions = await this.getNftMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed metadata for an NFT including name, description, image, traits, and external links.
     * Get NFT metadata
     */
    async getNftMetadata(requestParameters: GetNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetMetadataResponse> {
        const response = await this.getNftMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftOwners without sending the request
     */
    async getNftOwnersRequestOpts(requestParameters: GetNftOwnersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNftOwners().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getNftOwners().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getNftOwners().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts/{identifier}/owners`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a paginated list of owners for a specific NFT. Particularly useful for ERC-1155 tokens which can have multiple owners.
     * Get NFT owners
     */
    async getNftOwnersRaw(requestParameters: GetNftOwnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OwnersPaginatedResponse>> {
        const requestOptions = await this.getNftOwnersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OwnersPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of owners for a specific NFT. Particularly useful for ERC-1155 tokens which can have multiple owners.
     * Get NFT owners
     */
    async getNftOwners(requestParameters: GetNftOwnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OwnersPaginatedResponse> {
        const response = await this.getNftOwnersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftsBatch without sending the request
     */
    async getNftsBatchRequestOpts(requestParameters: GetNftsBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchNftsRequest'] == null) {
            throw new runtime.RequiredError(
                'batchNftsRequest',
                'Required parameter "batchNftsRequest" was null or undefined when calling getNftsBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/nfts/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchNftsRequestToJSON(requestParameters['batchNftsRequest']),
        };
    }

    /**
     * Retrieve multiple NFTs in a single request by providing a list of identifiers (chain, contract address, and token ID). Not-found NFTs are silently omitted from the response.
     * Get NFTs by identifiers
     */
    async getNftsBatchRaw(requestParameters: GetNftsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftBatchResponse>> {
        const requestOptions = await this.getNftsBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftBatchResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve multiple NFTs in a single request by providing a list of identifiers (chain, contract address, and token ID). Not-found NFTs are silently omitted from the response.
     * Get NFTs by identifiers
     */
    async getNftsBatch(requestParameters: GetNftsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftBatchResponse> {
        const response = await this.getNftsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftsByAccount without sending the request
     */
    async getNftsByAccountRequestOpts(requestParameters: GetNftsByAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getNftsByAccount().'
            );
        }

        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNftsByAccount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['collection'] != null) {
            queryParameters['collection'] = requestParameters['collection'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/account/{address}/nfts`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all NFTs owned by a specific account on a blockchain, with optional collection filtering.
     * Get NFTs by account
     */
    async getNftsByAccountRaw(requestParameters: GetNftsByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftListResponse>> {
        const requestOptions = await this.getNftsByAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftListResponseFromJSON(jsonValue));
    }

    /**
     * Get all NFTs owned by a specific account on a blockchain, with optional collection filtering.
     * Get NFTs by account
     */
    async getNftsByAccount(requestParameters: GetNftsByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftListResponse> {
        const response = await this.getNftsByAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftsByCollection without sending the request
     */
    async getNftsByCollectionRequestOpts(requestParameters: GetNftsByCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getNftsByCollection().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['traits'] != null) {
            queryParameters['traits'] = requestParameters['traits'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/collection/{slug}/nfts`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get NFTs in a specific collection. Optionally filter by traits using the \'traits\' query parameter with a JSON array of trait filters. Multiple traits are AND-combined (items must match all specified traits). Example: ?traits=[{\"traitType\":\"Background\",\"value\":\"Red\"},{\"traitType\":\"Eyes\",\"value\":\"Blue\"}]
     * Get NFTs by collection
     */
    async getNftsByCollectionRaw(requestParameters: GetNftsByCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftListResponse>> {
        const requestOptions = await this.getNftsByCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftListResponseFromJSON(jsonValue));
    }

    /**
     * Get NFTs in a specific collection. Optionally filter by traits using the \'traits\' query parameter with a JSON array of trait filters. Multiple traits are AND-combined (items must match all specified traits). Example: ?traits=[{\"traitType\":\"Background\",\"value\":\"Red\"},{\"traitType\":\"Eyes\",\"value\":\"Blue\"}]
     * Get NFTs by collection
     */
    async getNftsByCollection(requestParameters: GetNftsByCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftListResponse> {
        const response = await this.getNftsByCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNftsByContract without sending the request
     */
    async getNftsByContractRequestOpts(requestParameters: GetNftsByContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getNftsByContract().'
            );
        }

        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getNftsByContract().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all NFTs for a specific contract address on a blockchain.
     * Get NFTs by contract
     */
    async getNftsByContractRaw(requestParameters: GetNftsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NftListResponse>> {
        const requestOptions = await this.getNftsByContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NftListResponseFromJSON(jsonValue));
    }

    /**
     * Get all NFTs for a specific contract address on a blockchain.
     * Get NFTs by contract
     */
    async getNftsByContract(requestParameters: GetNftsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NftListResponse> {
        const response = await this.getNftsByContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshNftMetadata without sending the request
     */
    async refreshNftMetadataRequestOpts(requestParameters: RefreshNftMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling refreshNftMetadata().'
            );
        }

        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling refreshNftMetadata().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling refreshNftMetadata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreCachedItemUrls'] != null) {
            queryParameters['ignoreCachedItemUrls'] = requestParameters['ignoreCachedItemUrls'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts/{identifier}/refresh`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Queue a metadata refresh for a specific NFT to update its information from the blockchain.
     * Refresh NFT metadata
     */
    async refreshNftMetadataRaw(requestParameters: RefreshNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.refreshNftMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Queue a metadata refresh for a specific NFT to update its information from the blockchain.
     * Refresh NFT metadata
     */
    async refreshNftMetadata(requestParameters: RefreshNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.refreshNftMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferAssets without sending the request
     */
    async transferAssetsRequestOpts(requestParameters: TransferAssetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferAssets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/assets/transfer`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        };
    }

    /**
     * Returns ordered blockchain actions to execute for transferring one or more NFTs or tokens from one wallet to another. Supports bulk transfers of multiple assets in a single request.
     * Transfer NFTs or tokens between wallets
     */
    async transferAssetsRaw(requestParameters: TransferAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferResponse>> {
        const requestOptions = await this.transferAssetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferResponseFromJSON(jsonValue));
    }

    /**
     * Returns ordered blockchain actions to execute for transferring one or more NFTs or tokens from one wallet to another. Supports bulk transfers of multiple assets in a single request.
     * Transfer NFTs or tokens between wallets
     */
    async transferAssets(requestParameters: TransferAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferResponse> {
        const response = await this.transferAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for validateNftMetadata without sending the request
     */
    async validateNftMetadataRequestOpts(requestParameters: ValidateNftMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling validateNftMetadata().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling validateNftMetadata().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling validateNftMetadata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreCachedItemUrls'] != null) {
            queryParameters['ignoreCachedItemUrls'] = requestParameters['ignoreCachedItemUrls'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/contract/{address}/nfts/{identifier}/validate-metadata`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch and validate NFT metadata directly from the blockchain without using cached data. Returns both original and processed (SeaDN) URLs to show how the metadata would be ingested. This endpoint does not persist any data.
     * Validate NFT metadata
     */
    async validateNftMetadataRaw(requestParameters: ValidateNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidateMetadataResponse>> {
        const requestOptions = await this.validateNftMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidateMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Fetch and validate NFT metadata directly from the blockchain without using cached data. Returns both original and processed (SeaDN) URLs to show how the metadata would be ingested. This endpoint does not persist any data.
     * Validate NFT metadata
     */
    async validateNftMetadata(requestParameters: ValidateNftMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidateMetadataResponse> {
        const response = await this.validateNftMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
