/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BuildOfferRequest,
    BuildOfferRequestFromJSON,
    BuildOfferRequestToJSON,
} from '../models/BuildOfferRequest';
import {
    type BuildOfferResponse,
    BuildOfferResponseFromJSON,
    BuildOfferResponseToJSON,
} from '../models/BuildOfferResponse';
import {
    type FulfillListingResponse,
    FulfillListingResponseFromJSON,
    FulfillListingResponseToJSON,
} from '../models/FulfillListingResponse';
import {
    type FullfillmentDataRequest,
    FullfillmentDataRequestFromJSON,
    FullfillmentDataRequestToJSON,
} from '../models/FullfillmentDataRequest';
import {
    type Offer,
    OfferFromJSON,
    OfferToJSON,
} from '../models/Offer';
import {
    type OfferWithCriteriaRequest,
    OfferWithCriteriaRequestFromJSON,
    OfferWithCriteriaRequestToJSON,
} from '../models/OfferWithCriteriaRequest';
import {
    type OffersResponse,
    OffersResponseFromJSON,
    OffersResponseToJSON,
} from '../models/OffersResponse';
import {
    type SeaportRequest,
    SeaportRequestFromJSON,
    SeaportRequestToJSON,
} from '../models/SeaportRequest';

export interface BuildOfferV2Request {
    buildOfferRequest: BuildOfferRequest;
}

export interface GenerateOfferFulfillmentDataV2Request {
    fullfillmentDataRequest: FullfillmentDataRequest;
}

export interface GetBestOfferNftRequest {
    slug: string;
    identifier: string;
}

export interface GetOffersCollectionRequest {
    slug: string;
    limit?: number;
    nextValue?: string;
}

export interface GetOffersCollectionTraitRequest {
    slug: string;
    mode?: GetOffersCollectionTraitModeEnum;
    type?: string;
    value?: string;
    floatValue?: number;
    intValue?: number;
    minValue?: number;
    maxValue?: number;
    traits?: string;
    limit?: number;
    nextValue?: string;
}

export interface GetOffersNftRequest {
    slug: string;
    identifier: string;
    limit?: number;
    nextValue?: string;
}

export interface ListOffersCollectionAllRequest {
    slug: string;
    maker?: string;
    limit?: number;
    nextValue?: string;
}

export interface PostCriteriaOfferV2Request {
    offerWithCriteriaRequest: OfferWithCriteriaRequest;
}

export interface PostOfferRequest {
    chain: string;
    protocol: string;
    seaportRequest: SeaportRequest;
}

/**
 * 
 */
export class OfferEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for buildOfferV2 without sending the request
     */
    async buildOfferV2RequestOpts(requestParameters: BuildOfferV2Request): Promise<runtime.RequestOpts> {
        if (requestParameters['buildOfferRequest'] == null) {
            throw new runtime.RequiredError(
                'buildOfferRequest',
                'Required parameter "buildOfferRequest" was null or undefined when calling buildOfferV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/build`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BuildOfferRequestToJSON(requestParameters['buildOfferRequest']),
        };
    }

    /**
     * Build a portion of a criteria offer including the consideration item, zone, and zone hash needed to post an offer. For trait offers on supported collections, the identifierOrCriteria in the returned consideration will be \'0\' (no merkle root computation needed). For other collections, a computed merkle root is returned. When identifierOrCriteria is \'0\', the encodedTokenIds field is informational only and not required for constructing the onchain order.
     * Build a criteria offer
     */
    async buildOfferV2Raw(requestParameters: BuildOfferV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BuildOfferResponse>> {
        const requestOptions = await this.buildOfferV2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BuildOfferResponseFromJSON(jsonValue));
    }

    /**
     * Build a portion of a criteria offer including the consideration item, zone, and zone hash needed to post an offer. For trait offers on supported collections, the identifierOrCriteria in the returned consideration will be \'0\' (no merkle root computation needed). For other collections, a computed merkle root is returned. When identifierOrCriteria is \'0\', the encodedTokenIds field is informational only and not required for constructing the onchain order.
     * Build a criteria offer
     */
    async buildOfferV2(requestParameters: BuildOfferV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BuildOfferResponse> {
        const response = await this.buildOfferV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for generateOfferFulfillmentDataV2 without sending the request
     */
    async generateOfferFulfillmentDataV2RequestOpts(requestParameters: GenerateOfferFulfillmentDataV2Request): Promise<runtime.RequestOpts> {
        if (requestParameters['fullfillmentDataRequest'] == null) {
            throw new runtime.RequiredError(
                'fullfillmentDataRequest',
                'Required parameter "fullfillmentDataRequest" was null or undefined when calling generateOfferFulfillmentDataV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/fulfillment_data`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FullfillmentDataRequestToJSON(requestParameters['fullfillmentDataRequest']),
        };
    }

    /**
     * Retrieve all the information, including signatures, needed to fulfill an offer directly onchain. For trait offers with identifierOrCriteria \'0\', the server validates that the specified token matches the offer\'s trait criteria before generating fulfillment data.
     * Fulfill an offer
     */
    async generateOfferFulfillmentDataV2Raw(requestParameters: GenerateOfferFulfillmentDataV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FulfillListingResponse>> {
        const requestOptions = await this.generateOfferFulfillmentDataV2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FulfillListingResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve all the information, including signatures, needed to fulfill an offer directly onchain. For trait offers with identifierOrCriteria \'0\', the server validates that the specified token matches the offer\'s trait criteria before generating fulfillment data.
     * Fulfill an offer
     */
    async generateOfferFulfillmentDataV2(requestParameters: GenerateOfferFulfillmentDataV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FulfillListingResponse> {
        const response = await this.generateOfferFulfillmentDataV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBestOfferNft without sending the request
     */
    async getBestOfferNftRequestOpts(requestParameters: GetBestOfferNftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getBestOfferNft().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getBestOfferNft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/collection/{slug}/nfts/{identifier}/best`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the best offer for an NFT.
     * Get best offer by NFT
     */
    async getBestOfferNftRaw(requestParameters: GetBestOfferNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        const requestOptions = await this.getBestOfferNftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * Get the best offer for an NFT.
     * Get best offer by NFT
     */
    async getBestOfferNft(requestParameters: GetBestOfferNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.getBestOfferNftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOffersCollection without sending the request
     */
    async getOffersCollectionRequestOpts(requestParameters: GetOffersCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getOffersCollection().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/collection/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get collection offers on a collection.
     * Get offers by collection
     */
    async getOffersCollectionRaw(requestParameters: GetOffersCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OffersResponse>> {
        const requestOptions = await this.getOffersCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OffersResponseFromJSON(jsonValue));
    }

    /**
     * Get collection offers on a collection.
     * Get offers by collection
     */
    async getOffersCollection(requestParameters: GetOffersCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OffersResponse> {
        const response = await this.getOffersCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOffersCollectionTrait without sending the request
     */
    async getOffersCollectionTraitRequestOpts(requestParameters: GetOffersCollectionTraitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getOffersCollectionTrait().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['floatValue'] != null) {
            queryParameters['float_value'] = requestParameters['floatValue'];
        }

        if (requestParameters['intValue'] != null) {
            queryParameters['int_value'] = requestParameters['intValue'];
        }

        if (requestParameters['minValue'] != null) {
            queryParameters['min_value'] = requestParameters['minValue'];
        }

        if (requestParameters['maxValue'] != null) {
            queryParameters['max_value'] = requestParameters['maxValue'];
        }

        if (requestParameters['traits'] != null) {
            queryParameters['traits'] = requestParameters['traits'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/collection/{slug}/traits`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get trait offers for a collection. Use the `mode` parameter to select the bid category.  **Single string trait:** `?mode=STRING&type=Background&value=Red` **Multiple string traits:** `?mode=MULTI&traits=[{\"traitType\":\"Background\",\"value\":\"Red\"},{\"traitType\":\"Eyes\",\"value\":\"Blue\"}]` **Numeric trait range:** `?mode=NUMERIC&type=Level&min_value=1&max_value=10`  Omit filter params to discover all bids of that mode (e.g. `?mode=NUMERIC` returns all numeric bids).  If `mode` is omitted, the mode is inferred from the params for backward compatibility.
     * Get trait offers for a collection
     */
    async getOffersCollectionTraitRaw(requestParameters: GetOffersCollectionTraitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OffersResponse>> {
        const requestOptions = await this.getOffersCollectionTraitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OffersResponseFromJSON(jsonValue));
    }

    /**
     * Get trait offers for a collection. Use the `mode` parameter to select the bid category.  **Single string trait:** `?mode=STRING&type=Background&value=Red` **Multiple string traits:** `?mode=MULTI&traits=[{\"traitType\":\"Background\",\"value\":\"Red\"},{\"traitType\":\"Eyes\",\"value\":\"Blue\"}]` **Numeric trait range:** `?mode=NUMERIC&type=Level&min_value=1&max_value=10`  Omit filter params to discover all bids of that mode (e.g. `?mode=NUMERIC` returns all numeric bids).  If `mode` is omitted, the mode is inferred from the params for backward compatibility.
     * Get trait offers for a collection
     */
    async getOffersCollectionTrait(requestParameters: GetOffersCollectionTraitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OffersResponse> {
        const response = await this.getOffersCollectionTraitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOffersNft without sending the request
     */
    async getOffersNftRequestOpts(requestParameters: GetOffersNftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getOffersNft().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getOffersNft().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/collection/{slug}/nfts/{identifier}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get offers for an NFT.
     * Get offers by NFT
     */
    async getOffersNftRaw(requestParameters: GetOffersNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OffersResponse>> {
        const requestOptions = await this.getOffersNftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OffersResponseFromJSON(jsonValue));
    }

    /**
     * Get offers for an NFT.
     * Get offers by NFT
     */
    async getOffersNft(requestParameters: GetOffersNftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OffersResponse> {
        const response = await this.getOffersNftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOffersCollectionAll without sending the request
     */
    async listOffersCollectionAllRequestOpts(requestParameters: ListOffersCollectionAllRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling listOffersCollectionAll().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['maker'] != null) {
            queryParameters['maker'] = requestParameters['maker'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextValue'] != null) {
            queryParameters['next.value'] = requestParameters['nextValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers/collection/{slug}/all`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all offers for a collection.
     * Get all offers by collection
     */
    async listOffersCollectionAllRaw(requestParameters: ListOffersCollectionAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OffersResponse>> {
        const requestOptions = await this.listOffersCollectionAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OffersResponseFromJSON(jsonValue));
    }

    /**
     * Get all offers for a collection.
     * Get all offers by collection
     */
    async listOffersCollectionAll(requestParameters: ListOffersCollectionAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OffersResponse> {
        const response = await this.listOffersCollectionAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCriteriaOfferV2 without sending the request
     */
    async postCriteriaOfferV2RequestOpts(requestParameters: PostCriteriaOfferV2Request): Promise<runtime.RequestOpts> {
        if (requestParameters['offerWithCriteriaRequest'] == null) {
            throw new runtime.RequiredError(
                'offerWithCriteriaRequest',
                'Required parameter "offerWithCriteriaRequest" was null or undefined when calling postCriteriaOfferV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/offers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OfferWithCriteriaRequestToJSON(requestParameters['offerWithCriteriaRequest']),
        };
    }

    /**
     * Create a criteria offer to purchase any NFT in a collection or which matches the specified trait. For trait offers where the Build Offer endpoint returns identifierOrCriteria \'0\', use that value directly — trait matching is validated server-side at fulfillment time rather than via onchain merkle proof.
     * Create a criteria offer
     */
    async postCriteriaOfferV2Raw(requestParameters: PostCriteriaOfferV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        const requestOptions = await this.postCriteriaOfferV2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * Create a criteria offer to purchase any NFT in a collection or which matches the specified trait. For trait offers where the Build Offer endpoint returns identifierOrCriteria \'0\', use that value directly — trait matching is validated server-side at fulfillment time rather than via onchain merkle proof.
     * Create a criteria offer
     */
    async postCriteriaOfferV2(requestParameters: PostCriteriaOfferV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.postCriteriaOfferV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postOffer without sending the request
     */
    async postOfferRequestOpts(requestParameters: PostOfferRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling postOffer().'
            );
        }

        if (requestParameters['protocol'] == null) {
            throw new runtime.RequiredError(
                'protocol',
                'Required parameter "protocol" was null or undefined when calling postOffer().'
            );
        }

        if (requestParameters['seaportRequest'] == null) {
            throw new runtime.RequiredError(
                'seaportRequest',
                'Required parameter "seaportRequest" was null or undefined when calling postOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/orders/{chain}/{protocol}/offers`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{protocol}', encodeURIComponent(String(requestParameters['protocol'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SeaportRequestToJSON(requestParameters['seaportRequest']),
        };
    }

    /**
     * Create an offer to purchase a single NFT (ERC721 or ERC1155).
     * Create an item offer
     */
    async postOfferRaw(requestParameters: PostOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Offer>> {
        const requestOptions = await this.postOfferRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OfferFromJSON(jsonValue));
    }

    /**
     * Create an offer to purchase a single NFT (ERC721 or ERC1155).
     * Create an item offer
     */
    async postOffer(requestParameters: PostOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Offer> {
        const response = await this.postOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetOffersCollectionTraitModeEnum = {
    String: 'STRING',
    Numeric: 'NUMERIC',
    Multi: 'MULTI'
} as const;
export type GetOffersCollectionTraitModeEnum = typeof GetOffersCollectionTraitModeEnum[keyof typeof GetOffersCollectionTraitModeEnum];
