/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CancelRequest,
    CancelRequestFromJSON,
    CancelRequestToJSON,
} from '../models/CancelRequest';
import {
    type CancelResponse,
    CancelResponseFromJSON,
    CancelResponseToJSON,
} from '../models/CancelResponse';
import {
    type GetOrderResponse,
    GetOrderResponseFromJSON,
    GetOrderResponseToJSON,
} from '../models/GetOrderResponse';

export interface CancelOrderRequest {
    chain: string;
    protocolAddress: string;
    orderHash: string;
    xApiKey?: string;
    cancelRequest?: CancelRequest;
}

export interface GetOrderRequest {
    chain: string;
    protocolAddress: string;
    orderHash: string;
}

/**
 * 
 */
export class OrderEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelOrder without sending the request
     */
    async cancelOrderRequestOpts(requestParameters: CancelOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling cancelOrder().'
            );
        }

        if (requestParameters['protocolAddress'] == null) {
            throw new runtime.RequiredError(
                'protocolAddress',
                'Required parameter "protocolAddress" was null or undefined when calling cancelOrder().'
            );
        }

        if (requestParameters['orderHash'] == null) {
            throw new runtime.RequiredError(
                'orderHash',
                'Required parameter "orderHash" was null or undefined when calling cancelOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xApiKey'] != null) {
            headerParameters['X-Api-Key'] = String(requestParameters['xApiKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/orders/chain/{chain}/protocol/{protocol_address}/{order_hash}/cancel`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{protocol_address}', encodeURIComponent(String(requestParameters['protocolAddress'])));
        urlPath = urlPath.replace('{order_hash}', encodeURIComponent(String(requestParameters['orderHash'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelRequestToJSON(requestParameters['cancelRequest']),
        };
    }

    /**
     * Offchain cancel a single order, offer or listing, by its order hash when protected by the SignedZone. Protocol and Chain are required to prevent hash collisions. Please note cancellation is only assured if a fulfillment signature was not vended prior to cancellation.
     * Cancel an order
     */
    async cancelOrderRaw(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CancelResponse>> {
        const requestOptions = await this.cancelOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CancelResponseFromJSON(jsonValue));
    }

    /**
     * Offchain cancel a single order, offer or listing, by its order hash when protected by the SignedZone. Protocol and Chain are required to prevent hash collisions. Please note cancellation is only assured if a fulfillment signature was not vended prior to cancellation.
     * Cancel an order
     */
    async cancelOrder(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CancelResponse> {
        const response = await this.cancelOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrder without sending the request
     */
    async getOrderRequestOpts(requestParameters: GetOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getOrder().'
            );
        }

        if (requestParameters['protocolAddress'] == null) {
            throw new runtime.RequiredError(
                'protocolAddress',
                'Required parameter "protocolAddress" was null or undefined when calling getOrder().'
            );
        }

        if (requestParameters['orderHash'] == null) {
            throw new runtime.RequiredError(
                'orderHash',
                'Required parameter "orderHash" was null or undefined when calling getOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/orders/chain/{chain}/protocol/{protocol_address}/{order_hash}`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{protocol_address}', encodeURIComponent(String(requestParameters['protocolAddress'])));
        urlPath = urlPath.replace('{order_hash}', encodeURIComponent(String(requestParameters['orderHash'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single order by its order hash.
     * Get an order
     */
    async getOrderRaw(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrderResponse>> {
        const requestOptions = await this.getOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrderResponseFromJSON(jsonValue));
    }

    /**
     * Get a single order by its order hash.
     * Get an order
     */
    async getOrder(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrderResponse> {
        const response = await this.getOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
