/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SwapExecuteRequest,
    SwapExecuteRequestFromJSON,
    SwapExecuteRequestToJSON,
} from '../models/SwapExecuteRequest';
import {
    type SwapExecuteResponse,
    SwapExecuteResponseFromJSON,
    SwapExecuteResponseToJSON,
} from '../models/SwapExecuteResponse';
import {
    type SwapQuoteResponse,
    SwapQuoteResponseFromJSON,
    SwapQuoteResponseToJSON,
} from '../models/SwapQuoteResponse';

export interface GetSwapQuoteRequest {
    fromChain: string;
    fromAddress: string;
    toChain: string;
    toAddress: string;
    quantity: string;
    address: string;
    slippage?: number;
    recipient?: string;
}

export interface PostSwapExecuteRequest {
    swapExecuteRequest: SwapExecuteRequest;
}

/**
 * 
 */
export class SwapEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getSwapQuote without sending the request
     */
    async getSwapQuoteRequestOpts(requestParameters: GetSwapQuoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fromChain'] == null) {
            throw new runtime.RequiredError(
                'fromChain',
                'Required parameter "fromChain" was null or undefined when calling getSwapQuote().'
            );
        }

        if (requestParameters['fromAddress'] == null) {
            throw new runtime.RequiredError(
                'fromAddress',
                'Required parameter "fromAddress" was null or undefined when calling getSwapQuote().'
            );
        }

        if (requestParameters['toChain'] == null) {
            throw new runtime.RequiredError(
                'toChain',
                'Required parameter "toChain" was null or undefined when calling getSwapQuote().'
            );
        }

        if (requestParameters['toAddress'] == null) {
            throw new runtime.RequiredError(
                'toAddress',
                'Required parameter "toAddress" was null or undefined when calling getSwapQuote().'
            );
        }

        if (requestParameters['quantity'] == null) {
            throw new runtime.RequiredError(
                'quantity',
                'Required parameter "quantity" was null or undefined when calling getSwapQuote().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getSwapQuote().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromChain'] != null) {
            queryParameters['from_chain'] = requestParameters['fromChain'];
        }

        if (requestParameters['fromAddress'] != null) {
            queryParameters['from_address'] = requestParameters['fromAddress'];
        }

        if (requestParameters['toChain'] != null) {
            queryParameters['to_chain'] = requestParameters['toChain'];
        }

        if (requestParameters['toAddress'] != null) {
            queryParameters['to_address'] = requestParameters['toAddress'];
        }

        if (requestParameters['quantity'] != null) {
            queryParameters['quantity'] = requestParameters['quantity'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['slippage'] != null) {
            queryParameters['slippage'] = requestParameters['slippage'];
        }

        if (requestParameters['recipient'] != null) {
            queryParameters['recipient'] = requestParameters['recipient'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/swap/quote`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a quote for swapping tokens, including price details and executable transaction data.
     * Get swap quote
     */
    async getSwapQuoteRaw(requestParameters: GetSwapQuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwapQuoteResponse>> {
        const requestOptions = await this.getSwapQuoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwapQuoteResponseFromJSON(jsonValue));
    }

    /**
     * Get a quote for swapping tokens, including price details and executable transaction data.
     * Get swap quote
     */
    async getSwapQuote(requestParameters: GetSwapQuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwapQuoteResponse> {
        const response = await this.getSwapQuoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSwapExecute without sending the request
     */
    async postSwapExecuteRequestOpts(requestParameters: PostSwapExecuteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['swapExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'swapExecuteRequest',
                'Required parameter "swapExecuteRequest" was null or undefined when calling postSwapExecute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/swap/execute`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwapExecuteRequestToJSON(requestParameters['swapExecuteRequest']),
        };
    }

    /**
     * Get executable transactions for token-to-token swaps. Supports same-chain and cross-chain swaps with multiple from/to assets.
     * Execute a token swap
     */
    async postSwapExecuteRaw(requestParameters: PostSwapExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwapExecuteResponse>> {
        const requestOptions = await this.postSwapExecuteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwapExecuteResponseFromJSON(jsonValue));
    }

    /**
     * Get executable transactions for token-to-token swaps. Supports same-chain and cross-chain swaps with multiple from/to assets.
     * Execute a token swap
     */
    async postSwapExecute(requestParameters: PostSwapExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwapExecuteResponse> {
        const response = await this.postSwapExecuteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
