/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BatchTokensRequest,
    BatchTokensRequestFromJSON,
    BatchTokensRequestToJSON,
} from '../models/BatchTokensRequest';
import {
    type ChainIdentifier,
    ChainIdentifierFromJSON,
    ChainIdentifierToJSON,
} from '../models/ChainIdentifier';
import {
    type OhlcvResponse,
    OhlcvResponseFromJSON,
    OhlcvResponseToJSON,
} from '../models/OhlcvResponse';
import {
    type PriceHistoryResponse,
    PriceHistoryResponseFromJSON,
    PriceHistoryResponseToJSON,
} from '../models/PriceHistoryResponse';
import {
    type TokenBalancePaginatedResponse,
    TokenBalancePaginatedResponseFromJSON,
    TokenBalancePaginatedResponseToJSON,
} from '../models/TokenBalancePaginatedResponse';
import {
    type TokenBatchResponse,
    TokenBatchResponseFromJSON,
    TokenBatchResponseToJSON,
} from '../models/TokenBatchResponse';
import {
    type TokenDetailedResponse,
    TokenDetailedResponseFromJSON,
    TokenDetailedResponseToJSON,
} from '../models/TokenDetailedResponse';
import {
    type TokenGroupPaginatedResponse,
    TokenGroupPaginatedResponseFromJSON,
    TokenGroupPaginatedResponseToJSON,
} from '../models/TokenGroupPaginatedResponse';
import {
    type TokenGroupResponse,
    TokenGroupResponseFromJSON,
    TokenGroupResponseToJSON,
} from '../models/TokenGroupResponse';
import {
    type TokenPaginatedResponse,
    TokenPaginatedResponseFromJSON,
    TokenPaginatedResponseToJSON,
} from '../models/TokenPaginatedResponse';
import {
    type TokenSwapActivityPaginatedResponse,
    TokenSwapActivityPaginatedResponseFromJSON,
    TokenSwapActivityPaginatedResponseToJSON,
} from '../models/TokenSwapActivityPaginatedResponse';

export interface GetTokenRequest {
    chain: string;
    address: string;
}

export interface GetTokenActivityRequest {
    chain: string;
    address: string;
    limit?: number;
    cursor?: string;
}

export interface GetTokenBalancesByAccountRequest {
    address: string;
    limit?: number;
    chains?: Array<ChainIdentifier>;
    sortBy?: GetTokenBalancesByAccountSortByEnum;
    sortDirection?: GetTokenBalancesByAccountSortDirectionEnum;
    disableSpamFiltering?: boolean;
    cursor?: string;
}

export interface GetTokenGroupRequest {
    slug: string;
}

export interface GetTokenGroupsRequest {
    limit?: number;
    cursor?: string;
}

export interface GetTokenOhlcvRequest {
    chain: string;
    address: string;
    startTime: Date;
    bucketSize: string;
    endTime?: Date;
    fillTimeWindow?: boolean;
}

export interface GetTokenPriceHistoryRequest {
    chain: string;
    address: string;
    startTime: Date;
    endTime?: Date;
    bucketSize?: string;
}

export interface GetTokensBatchRequest {
    batchTokensRequest: BatchTokensRequest;
}

export interface GetTopTokensRequest {
    limit?: number;
    chains?: Array<ChainIdentifier>;
    cursor?: string;
}

export interface GetTrendingTokensRequest {
    limit?: number;
    chains?: Array<ChainIdentifier>;
    cursor?: string;
}

/**
 * 
 */
export class TokenEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getToken without sending the request
     */
    async getTokenRequestOpts(requestParameters: GetTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getToken().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/token/{address}`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed information about a specific token by chain and contract address.
     * Get token details
     */
    async getTokenRaw(requestParameters: GetTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenDetailedResponse>> {
        const requestOptions = await this.getTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenDetailedResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific token by chain and contract address.
     * Get token details
     */
    async getToken(requestParameters: GetTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenDetailedResponse> {
        const response = await this.getTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenActivity without sending the request
     */
    async getTokenActivityRequestOpts(requestParameters: GetTokenActivityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getTokenActivity().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getTokenActivity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/token/{address}/activity`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get paginated swap activity for a specific token on a given chain.
     * Get token swap activity
     */
    async getTokenActivityRaw(requestParameters: GetTokenActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenSwapActivityPaginatedResponse>> {
        const requestOptions = await this.getTokenActivityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenSwapActivityPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated swap activity for a specific token on a given chain.
     * Get token swap activity
     */
    async getTokenActivity(requestParameters: GetTokenActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenSwapActivityPaginatedResponse> {
        const response = await this.getTokenActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenBalancesByAccount without sending the request
     */
    async getTokenBalancesByAccountRequestOpts(requestParameters: GetTokenBalancesByAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getTokenBalancesByAccount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['chains'] != null) {
            queryParameters['chains'] = requestParameters['chains'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sort_direction'] = requestParameters['sortDirection'];
        }

        if (requestParameters['disableSpamFiltering'] != null) {
            queryParameters['disable_spam_filtering'] = requestParameters['disableSpamFiltering'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/account/{address}/tokens`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get fungible token balances for a specific wallet address. Returns quantity (in display units, not raw/wei), USD value, and token metadata for each token held.
     * Get token balances by account
     */
    async getTokenBalancesByAccountRaw(requestParameters: GetTokenBalancesByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenBalancePaginatedResponse>> {
        const requestOptions = await this.getTokenBalancesByAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenBalancePaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get fungible token balances for a specific wallet address. Returns quantity (in display units, not raw/wei), USD value, and token metadata for each token held.
     * Get token balances by account
     */
    async getTokenBalancesByAccount(requestParameters: GetTokenBalancesByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenBalancePaginatedResponse> {
        const response = await this.getTokenBalancesByAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenGroup without sending the request
     */
    async getTokenGroupRequestOpts(requestParameters: GetTokenGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getTokenGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/token-groups/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed information about a specific token group by its slug identifier.
     * Get a token group by slug
     */
    async getTokenGroupRaw(requestParameters: GetTokenGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenGroupResponse>> {
        const requestOptions = await this.getTokenGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenGroupResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific token group by its slug identifier.
     * Get a token group by slug
     */
    async getTokenGroup(requestParameters: GetTokenGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenGroupResponse> {
        const response = await this.getTokenGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenGroups without sending the request
     */
    async getTokenGroupsRequestOpts(requestParameters: GetTokenGroupsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/token-groups`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a paginated list of token groups sorted by market cap descending. Token groups represent equivalent currencies across different blockchains (e.g., ETH on Ethereum, Base, and Arbitrum are all in the \"eth\" token group).
     * Get token groups
     */
    async getTokenGroupsRaw(requestParameters: GetTokenGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenGroupPaginatedResponse>> {
        const requestOptions = await this.getTokenGroupsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenGroupPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of token groups sorted by market cap descending. Token groups represent equivalent currencies across different blockchains (e.g., ETH on Ethereum, Base, and Arbitrum are all in the \"eth\" token group).
     * Get token groups
     */
    async getTokenGroups(requestParameters: GetTokenGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenGroupPaginatedResponse> {
        const response = await this.getTokenGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenOhlcv without sending the request
     */
    async getTokenOhlcvRequestOpts(requestParameters: GetTokenOhlcvRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getTokenOhlcv().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getTokenOhlcv().'
            );
        }

        if (requestParameters['startTime'] == null) {
            throw new runtime.RequiredError(
                'startTime',
                'Required parameter "startTime" was null or undefined when calling getTokenOhlcv().'
            );
        }

        if (requestParameters['bucketSize'] == null) {
            throw new runtime.RequiredError(
                'bucketSize',
                'Required parameter "bucketSize" was null or undefined when calling getTokenOhlcv().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        if (requestParameters['bucketSize'] != null) {
            queryParameters['bucket_size'] = requestParameters['bucketSize'];
        }

        if (requestParameters['fillTimeWindow'] != null) {
            queryParameters['fill_time_window'] = requestParameters['fillTimeWindow'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/token/{address}/ohlcv`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get OHLCV (Open, High, Low, Close, Volume) candlestick data for a specific token.
     * Get token OHLCV candles
     */
    async getTokenOhlcvRaw(requestParameters: GetTokenOhlcvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OhlcvResponse>> {
        const requestOptions = await this.getTokenOhlcvRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OhlcvResponseFromJSON(jsonValue));
    }

    /**
     * Get OHLCV (Open, High, Low, Close, Volume) candlestick data for a specific token.
     * Get token OHLCV candles
     */
    async getTokenOhlcv(requestParameters: GetTokenOhlcvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OhlcvResponse> {
        const response = await this.getTokenOhlcvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokenPriceHistory without sending the request
     */
    async getTokenPriceHistoryRequestOpts(requestParameters: GetTokenPriceHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getTokenPriceHistory().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getTokenPriceHistory().'
            );
        }

        if (requestParameters['startTime'] == null) {
            throw new runtime.RequiredError(
                'startTime',
                'Required parameter "startTime" was null or undefined when calling getTokenPriceHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startTime'] != null) {
            queryParameters['start_time'] = (requestParameters['startTime'] as any).toISOString();
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['end_time'] = (requestParameters['endTime'] as any).toISOString();
        }

        if (requestParameters['bucketSize'] != null) {
            queryParameters['bucket_size'] = requestParameters['bucketSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/chain/{chain}/token/{address}/price_history`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get historical price data for a specific token.
     * Get token price history
     */
    async getTokenPriceHistoryRaw(requestParameters: GetTokenPriceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceHistoryResponse>> {
        const requestOptions = await this.getTokenPriceHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Get historical price data for a specific token.
     * Get token price history
     */
    async getTokenPriceHistory(requestParameters: GetTokenPriceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceHistoryResponse> {
        const response = await this.getTokenPriceHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTokensBatch without sending the request
     */
    async getTokensBatchRequestOpts(requestParameters: GetTokensBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchTokensRequest'] == null) {
            throw new runtime.RequiredError(
                'batchTokensRequest',
                'Required parameter "batchTokensRequest" was null or undefined when calling getTokensBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/tokens/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchTokensRequestToJSON(requestParameters['batchTokensRequest']),
        };
    }

    /**
     * Retrieve multiple tokens in a single request by providing a list of contract identifiers (chain and address). Not-found tokens are silently omitted from the response.
     * Get tokens by contract identifiers
     */
    async getTokensBatchRaw(requestParameters: GetTokensBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenBatchResponse>> {
        const requestOptions = await this.getTokensBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenBatchResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve multiple tokens in a single request by providing a list of contract identifiers (chain and address). Not-found tokens are silently omitted from the response.
     * Get tokens by contract identifiers
     */
    async getTokensBatch(requestParameters: GetTokensBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenBatchResponse> {
        const response = await this.getTokensBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTopTokens without sending the request
     */
    async getTopTokensRequestOpts(requestParameters: GetTopTokensRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['chains'] != null) {
            queryParameters['chains'] = requestParameters['chains'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/tokens/top`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get top tokens ranked by 24-hour trading volume. Returns established tokens with high market activity.
     * Get top tokens
     */
    async getTopTokensRaw(requestParameters: GetTopTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPaginatedResponse>> {
        const requestOptions = await this.getTopTokensRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get top tokens ranked by 24-hour trading volume. Returns established tokens with high market activity.
     * Get top tokens
     */
    async getTopTokens(requestParameters: GetTopTokensRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPaginatedResponse> {
        const response = await this.getTopTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTrendingTokens without sending the request
     */
    async getTrendingTokensRequestOpts(requestParameters: GetTrendingTokensRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['chains'] != null) {
            queryParameters['chains'] = requestParameters['chains'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v2/tokens/trending`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get trending tokens based on OpenSea\'s trending score algorithm. Returns tokens with high momentum including memecoins and newly popular assets.
     * Get trending tokens
     */
    async getTrendingTokensRaw(requestParameters: GetTrendingTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPaginatedResponse>> {
        const requestOptions = await this.getTrendingTokensRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get trending tokens based on OpenSea\'s trending score algorithm. Returns tokens with high momentum including memecoins and newly popular assets.
     * Get trending tokens
     */
    async getTrendingTokens(requestParameters: GetTrendingTokensRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPaginatedResponse> {
        const response = await this.getTrendingTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTokenBalancesByAccountSortByEnum = {
    UsdValue: 'USD_VALUE',
    MarketCap: 'MARKET_CAP',
    OneDayVolume: 'ONE_DAY_VOLUME',
    Price: 'PRICE',
    OneDayPriceChange: 'ONE_DAY_PRICE_CHANGE',
    SevenDayPriceChange: 'SEVEN_DAY_PRICE_CHANGE'
} as const;
export type GetTokenBalancesByAccountSortByEnum = typeof GetTokenBalancesByAccountSortByEnum[keyof typeof GetTokenBalancesByAccountSortByEnum];
/**
 * @export
 */
export const GetTokenBalancesByAccountSortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetTokenBalancesByAccountSortDirectionEnum = typeof GetTokenBalancesByAccountSortDirectionEnum[keyof typeof GetTokenBalancesByAccountSortDirectionEnum];
