/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Account search result
 * @export
 * @interface AccountSearchResponse
 */
export interface AccountSearchResponse {
    /**
     * Primary wallet address of the account
     * @type {string}
     * @memberof AccountSearchResponse
     */
    address: string;
    /**
     * Username of the account
     * @type {string}
     * @memberof AccountSearchResponse
     */
    username?: string;
    /**
     * URL of the account's profile image
     * @type {string}
     * @memberof AccountSearchResponse
     */
    profileImageUrl?: string;
    /**
     * URL to the account on OpenSea
     * @type {string}
     * @memberof AccountSearchResponse
     */
    openseaUrl: string;
}

/**
 * Check if a given object implements the AccountSearchResponse interface.
 */
export function instanceOfAccountSearchResponse(value: object): value is AccountSearchResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    return true;
}

export function AccountSearchResponseFromJSON(json: any): AccountSearchResponse {
    return AccountSearchResponseFromJSONTyped(json, false);
}

export function AccountSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'username': json['username'] == null ? undefined : json['username'],
        'profileImageUrl': json['profile_image_url'] == null ? undefined : json['profile_image_url'],
        'openseaUrl': json['opensea_url'],
    };
}

export function AccountSearchResponseToJSON(json: any): AccountSearchResponse {
    return AccountSearchResponseToJSONTyped(json, false);
}

export function AccountSearchResponseToJSONTyped(value?: AccountSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'username': value['username'],
        'profile_image_url': value['profileImageUrl'],
        'opensea_url': value['openseaUrl'],
    };
}

