/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocialMediaAccount } from './SocialMediaAccount';
import {
    SocialMediaAccountFromJSON,
    SocialMediaAccountFromJSONTyped,
    SocialMediaAccountToJSON,
    SocialMediaAccountToJSONTyped,
} from './SocialMediaAccount';

/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    bannerImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    website?: string;
    /**
     * 
     * @type {Array<SocialMediaAccount>}
     * @memberof AccountResponse
     */
    socialMediaAccounts: Array<SocialMediaAccount>;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    bio: string;
    /**
     * 
     * @type {Date}
     * @memberof AccountResponse
     */
    joinedDate: Date;
}

/**
 * Check if a given object implements the AccountResponse interface.
 */
export function instanceOfAccountResponse(value: object): value is AccountResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('socialMediaAccounts' in value) || value['socialMediaAccounts'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('joinedDate' in value) || value['joinedDate'] === undefined) return false;
    return true;
}

export function AccountResponseFromJSON(json: any): AccountResponse {
    return AccountResponseFromJSONTyped(json, false);
}

export function AccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'username': json['username'] == null ? undefined : json['username'],
        'profileImageUrl': json['profile_image_url'] == null ? undefined : json['profile_image_url'],
        'bannerImageUrl': json['banner_image_url'] == null ? undefined : json['banner_image_url'],
        'website': json['website'] == null ? undefined : json['website'],
        'socialMediaAccounts': ((json['social_media_accounts'] as Array<any>).map(SocialMediaAccountFromJSON)),
        'bio': json['bio'],
        'joinedDate': (new Date(json['joined_date'])),
    };
}

export function AccountResponseToJSON(json: any): AccountResponse {
    return AccountResponseToJSONTyped(json, false);
}

export function AccountResponseToJSONTyped(value?: AccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'username': value['username'],
        'profile_image_url': value['profileImageUrl'],
        'banner_image_url': value['bannerImageUrl'],
        'website': value['website'],
        'social_media_accounts': ((value['socialMediaAccounts'] as Array<any>).map(SocialMediaAccountToJSON)),
        'bio': value['bio'],
        'joined_date': value['joinedDate'].toISOString(),
    };
}

