/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';

/**
 * 
 * @export
 * @interface AdditionalRecipient
 */
export interface AdditionalRecipient {
    /**
     * 
     * @type {Array<Type>}
     * @memberof AdditionalRecipient
     */
    value?: Array<Type>;
    /**
     * 
     * @type {number}
     * @memberof AdditionalRecipient
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof AdditionalRecipient
     */
    recipient?: string;
    /**
     * 
     * @type {string}
     * @memberof AdditionalRecipient
     */
    typeAsString?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof AdditionalRecipient
     */
    nativeValueCopy?: Array<any>;
}

/**
 * Check if a given object implements the AdditionalRecipient interface.
 */
export function instanceOfAdditionalRecipient(value: object): value is AdditionalRecipient {
    return true;
}

export function AdditionalRecipientFromJSON(json: any): AdditionalRecipient {
    return AdditionalRecipientFromJSONTyped(json, false);
}

export function AdditionalRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalRecipient {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(TypeFromJSON)),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
        'typeAsString': json['typeAsString'] == null ? undefined : json['typeAsString'],
        'nativeValueCopy': json['nativeValueCopy'] == null ? undefined : json['nativeValueCopy'],
    };
}

export function AdditionalRecipientToJSON(json: any): AdditionalRecipient {
    return AdditionalRecipientToJSONTyped(json, false);
}

export function AdditionalRecipientToJSONTyped(value?: AdditionalRecipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(TypeToJSON)),
        'amount': value['amount'],
        'recipient': value['recipient'],
        'typeAsString': value['typeAsString'],
        'nativeValueCopy': value['nativeValueCopy'],
    };
}

