/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An asset with quantity in base units
 * @export
 * @interface AssetQuantityInput
 */
export interface AssetQuantityInput {
    /**
     * The blockchain chain
     * @type {string}
     * @memberof AssetQuantityInput
     */
    chain: string;
    /**
     * The contract address
     * @type {string}
     * @memberof AssetQuantityInput
     */
    contract: string;
    /**
     * Token ID for NFTs
     * @type {string}
     * @memberof AssetQuantityInput
     */
    tokenId?: string;
    /**
     * Amount in base units (wei/lamports)
     * @type {string}
     * @memberof AssetQuantityInput
     */
    amount: string;
}

/**
 * Check if a given object implements the AssetQuantityInput interface.
 */
export function instanceOfAssetQuantityInput(value: object): value is AssetQuantityInput {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AssetQuantityInputFromJSON(json: any): AssetQuantityInput {
    return AssetQuantityInputFromJSONTyped(json, false);
}

export function AssetQuantityInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetQuantityInput {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contract': json['contract'],
        'tokenId': json['token_id'] == null ? undefined : json['token_id'],
        'amount': json['amount'],
    };
}

export function AssetQuantityInputToJSON(json: any): AssetQuantityInput {
    return AssetQuantityInputToJSONTyped(json, false);
}

export function AssetQuantityInputToJSONTyped(value?: AssetQuantityInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract': value['contract'],
        'token_id': value['tokenId'],
        'amount': value['amount'],
    };
}

