/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OrderEvent } from './OrderEvent';
import {
    instanceOfOrderEvent,
    OrderEventFromJSON,
    OrderEventFromJSONTyped,
    OrderEventToJSON,
} from './OrderEvent';
import type { SaleEvent } from './SaleEvent';
import {
    instanceOfSaleEvent,
    SaleEventFromJSON,
    SaleEventFromJSONTyped,
    SaleEventToJSON,
} from './SaleEvent';
import type { TransferEvent } from './TransferEvent';
import {
    instanceOfTransferEvent,
    TransferEventFromJSON,
    TransferEventFromJSONTyped,
    TransferEventToJSON,
} from './TransferEvent';

/**
 * @type AssetEventsResponseAssetEventsInner
 * 
 * @export
 */
export type AssetEventsResponseAssetEventsInner = OrderEvent | SaleEvent | TransferEvent;

export function AssetEventsResponseAssetEventsInnerFromJSON(json: any): AssetEventsResponseAssetEventsInner {
    return AssetEventsResponseAssetEventsInnerFromJSONTyped(json, false);
}

export function AssetEventsResponseAssetEventsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetEventsResponseAssetEventsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfOrderEvent(json)) {
        return OrderEventFromJSONTyped(json, true);
    }
    if (instanceOfSaleEvent(json)) {
        return SaleEventFromJSONTyped(json, true);
    }
    if (instanceOfTransferEvent(json)) {
        return TransferEventFromJSONTyped(json, true);
    }
    return {} as any;
}

export function AssetEventsResponseAssetEventsInnerToJSON(json: any): any {
    return AssetEventsResponseAssetEventsInnerToJSONTyped(json, false);
}

export function AssetEventsResponseAssetEventsInnerToJSONTyped(value?: AssetEventsResponseAssetEventsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfOrderEvent(value)) {
        return OrderEventToJSON(value as OrderEvent);
    }
    if (instanceOfSaleEvent(value)) {
        return SaleEventToJSON(value as SaleEvent);
    }
    if (instanceOfTransferEvent(value)) {
        return TransferEventToJSON(value as TransferEvent);
    }
    return {};
}

