/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Trait } from './Trait';
import {
    TraitFromJSON,
    TraitFromJSONTyped,
    TraitToJSON,
    TraitToJSONTyped,
} from './Trait';

/**
 * 
 * @export
 * @interface AssetMetadataResponse
 */
export interface AssetMetadataResponse {
    /**
     * 
     * @type {string}
     * @memberof AssetMetadataResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetMetadataResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetMetadataResponse
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetMetadataResponse
     */
    externalLink?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetMetadataResponse
     */
    animationUrl?: string;
    /**
     * 
     * @type {Array<Trait>}
     * @memberof AssetMetadataResponse
     */
    traits: Array<Trait>;
}

/**
 * Check if a given object implements the AssetMetadataResponse interface.
 */
export function instanceOfAssetMetadataResponse(value: object): value is AssetMetadataResponse {
    if (!('traits' in value) || value['traits'] === undefined) return false;
    return true;
}

export function AssetMetadataResponseFromJSON(json: any): AssetMetadataResponse {
    return AssetMetadataResponseFromJSONTyped(json, false);
}

export function AssetMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
        'externalLink': json['external_link'] == null ? undefined : json['external_link'],
        'animationUrl': json['animation_url'] == null ? undefined : json['animation_url'],
        'traits': ((json['traits'] as Array<any>).map(TraitFromJSON)),
    };
}

export function AssetMetadataResponseToJSON(json: any): AssetMetadataResponse {
    return AssetMetadataResponseToJSONTyped(json, false);
}

export function AssetMetadataResponseToJSONTyped(value?: AssetMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'image': value['image'],
        'external_link': value['externalLink'],
        'animation_url': value['animationUrl'],
        'traits': ((value['traits'] as Array<any>).map(TraitToJSON)),
    };
}

