/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Asset identifier with chain, contract address, and optional token ID
 * @export
 * @interface AssetIdentifierResponse
 */
export interface AssetIdentifierResponse {
    /**
     * The blockchain chain
     * @type {string}
     * @memberof AssetIdentifierResponse
     */
    chain: string;
    /**
     * The contract address
     * @type {string}
     * @memberof AssetIdentifierResponse
     */
    contract: string;
    /**
     * Token ID for NFTs
     * @type {string}
     * @memberof AssetIdentifierResponse
     */
    tokenId?: string;
}

/**
 * Check if a given object implements the AssetIdentifierResponse interface.
 */
export function instanceOfAssetIdentifierResponse(value: object): value is AssetIdentifierResponse {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function AssetIdentifierResponseFromJSON(json: any): AssetIdentifierResponse {
    return AssetIdentifierResponseFromJSONTyped(json, false);
}

export function AssetIdentifierResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetIdentifierResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contract': json['contract'],
        'tokenId': json['token_id'] == null ? undefined : json['token_id'],
    };
}

export function AssetIdentifierResponseToJSON(json: any): AssetIdentifierResponse {
    return AssetIdentifierResponseToJSONTyped(json, false);
}

export function AssetIdentifierResponseToJSONTyped(value?: AssetIdentifierResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract': value['contract'],
        'token_id': value['tokenId'],
    };
}

