/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';
import type { AdditionalRecipient } from './AdditionalRecipient';
import {
    AdditionalRecipientFromJSON,
    AdditionalRecipientFromJSONTyped,
    AdditionalRecipientToJSON,
    AdditionalRecipientToJSONTyped,
} from './AdditionalRecipient';

/**
 * 
 * @export
 * @interface BasicOrderParameters
 */
export interface BasicOrderParameters {
    /**
     * 
     * @type {Array<Type>}
     * @memberof BasicOrderParameters
     */
    value?: Array<Type>;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    considerationToken?: string;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    considerationIdentifier?: number;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    considerationAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    offerer?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    zone?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    offerToken?: string;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    offerIdentifier?: number;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    offerAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    basicOrderType?: number;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    endTime?: number;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    zoneHash?: string;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    salt?: number;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    offererConduitKey?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    fulfillerConduitKey?: string;
    /**
     * 
     * @type {number}
     * @memberof BasicOrderParameters
     */
    totalOriginalAdditionalRecipients?: number;
    /**
     * 
     * @type {Array<AdditionalRecipient>}
     * @memberof BasicOrderParameters
     */
    additionalRecipients?: Array<AdditionalRecipient>;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    signature?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicOrderParameters
     */
    typeAsString?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof BasicOrderParameters
     */
    nativeValueCopy?: Array<any>;
}

/**
 * Check if a given object implements the BasicOrderParameters interface.
 */
export function instanceOfBasicOrderParameters(value: object): value is BasicOrderParameters {
    return true;
}

export function BasicOrderParametersFromJSON(json: any): BasicOrderParameters {
    return BasicOrderParametersFromJSONTyped(json, false);
}

export function BasicOrderParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicOrderParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(TypeFromJSON)),
        'considerationToken': json['considerationToken'] == null ? undefined : json['considerationToken'],
        'considerationIdentifier': json['considerationIdentifier'] == null ? undefined : json['considerationIdentifier'],
        'considerationAmount': json['considerationAmount'] == null ? undefined : json['considerationAmount'],
        'offerer': json['offerer'] == null ? undefined : json['offerer'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'offerToken': json['offerToken'] == null ? undefined : json['offerToken'],
        'offerIdentifier': json['offerIdentifier'] == null ? undefined : json['offerIdentifier'],
        'offerAmount': json['offerAmount'] == null ? undefined : json['offerAmount'],
        'basicOrderType': json['basicOrderType'] == null ? undefined : json['basicOrderType'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'zoneHash': json['zoneHash'] == null ? undefined : json['zoneHash'],
        'salt': json['salt'] == null ? undefined : json['salt'],
        'offererConduitKey': json['offererConduitKey'] == null ? undefined : json['offererConduitKey'],
        'fulfillerConduitKey': json['fulfillerConduitKey'] == null ? undefined : json['fulfillerConduitKey'],
        'totalOriginalAdditionalRecipients': json['totalOriginalAdditionalRecipients'] == null ? undefined : json['totalOriginalAdditionalRecipients'],
        'additionalRecipients': json['additionalRecipients'] == null ? undefined : ((json['additionalRecipients'] as Array<any>).map(AdditionalRecipientFromJSON)),
        'signature': json['signature'] == null ? undefined : json['signature'],
        'typeAsString': json['typeAsString'] == null ? undefined : json['typeAsString'],
        'nativeValueCopy': json['nativeValueCopy'] == null ? undefined : json['nativeValueCopy'],
    };
}

export function BasicOrderParametersToJSON(json: any): BasicOrderParameters {
    return BasicOrderParametersToJSONTyped(json, false);
}

export function BasicOrderParametersToJSONTyped(value?: BasicOrderParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(TypeToJSON)),
        'considerationToken': value['considerationToken'],
        'considerationIdentifier': value['considerationIdentifier'],
        'considerationAmount': value['considerationAmount'],
        'offerer': value['offerer'],
        'zone': value['zone'],
        'offerToken': value['offerToken'],
        'offerIdentifier': value['offerIdentifier'],
        'offerAmount': value['offerAmount'],
        'basicOrderType': value['basicOrderType'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'zoneHash': value['zoneHash'],
        'salt': value['salt'],
        'offererConduitKey': value['offererConduitKey'],
        'fulfillerConduitKey': value['fulfillerConduitKey'],
        'totalOriginalAdditionalRecipients': value['totalOriginalAdditionalRecipients'],
        'additionalRecipients': value['additionalRecipients'] == null ? undefined : ((value['additionalRecipients'] as Array<any>).map(AdditionalRecipientToJSON)),
        'signature': value['signature'],
        'typeAsString': value['typeAsString'],
        'nativeValueCopy': value['nativeValueCopy'],
    };
}

