/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenContractInput } from './TokenContractInput';
import {
    TokenContractInputFromJSON,
    TokenContractInputFromJSONTyped,
    TokenContractInputToJSON,
    TokenContractInputToJSONTyped,
} from './TokenContractInput';

/**
 * Request body for batch token retrieval by contract identifiers
 * @export
 * @interface BatchTokensRequest
 */
export interface BatchTokensRequest {
    /**
     * List of token contract identifiers to retrieve
     * @type {Array<TokenContractInput>}
     * @memberof BatchTokensRequest
     */
    contracts: Array<TokenContractInput>;
}

/**
 * Check if a given object implements the BatchTokensRequest interface.
 */
export function instanceOfBatchTokensRequest(value: object): value is BatchTokensRequest {
    if (!('contracts' in value) || value['contracts'] === undefined) return false;
    return true;
}

export function BatchTokensRequestFromJSON(json: any): BatchTokensRequest {
    return BatchTokensRequestFromJSONTyped(json, false);
}

export function BatchTokensRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchTokensRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contracts': ((json['contracts'] as Array<any>).map(TokenContractInputFromJSON)),
    };
}

export function BatchTokensRequestToJSON(json: any): BatchTokensRequest {
    return BatchTokensRequestToJSONTyped(json, false);
}

export function BatchTokensRequestToJSONTyped(value?: BatchTokensRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contracts': ((value['contracts'] as Array<any>).map(TokenContractInputToJSON)),
    };
}

