/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A bidder in an offer aggregate
 * @export
 * @interface BidderResponse
 */
export interface BidderResponse {
    /**
     * Wallet address of the bidder
     * @type {string}
     * @memberof BidderResponse
     */
    address: string;
    /**
     * Number of offers from this bidder
     * @type {number}
     * @memberof BidderResponse
     */
    quantity: number;
}

/**
 * Check if a given object implements the BidderResponse interface.
 */
export function instanceOfBidderResponse(value: object): value is BidderResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function BidderResponseFromJSON(json: any): BidderResponse {
    return BidderResponseFromJSONTyped(json, false);
}

export function BidderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BidderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'quantity': json['quantity'],
    };
}

export function BidderResponseToJSON(json: any): BidderResponse {
    return BidderResponseToJSONTyped(json, false);
}

export function BidderResponseToJSONTyped(value?: BidderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'quantity': value['quantity'],
    };
}

