/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelResponse
 */
export interface CancelResponse {
    /**
     * 
     * @type {string}
     * @memberof CancelResponse
     */
    lastSignatureIssuedValidUntil: string;
}

/**
 * Check if a given object implements the CancelResponse interface.
 */
export function instanceOfCancelResponse(value: object): value is CancelResponse {
    if (!('lastSignatureIssuedValidUntil' in value) || value['lastSignatureIssuedValidUntil'] === undefined) return false;
    return true;
}

export function CancelResponseFromJSON(json: any): CancelResponse {
    return CancelResponseFromJSONTyped(json, false);
}

export function CancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'lastSignatureIssuedValidUntil': json['last_signature_issued_valid_until'],
    };
}

export function CancelResponseToJSON(json: any): CancelResponse {
    return CancelResponseToJSONTyped(json, false);
}

export function CancelResponseToJSONTyped(value?: CancelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_signature_issued_valid_until': value['lastSignatureIssuedValidUntil'],
    };
}

