/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricingCurrencies } from './PricingCurrencies';
import {
    PricingCurrenciesFromJSON,
    PricingCurrenciesFromJSONTyped,
    PricingCurrenciesToJSON,
    PricingCurrenciesToJSONTyped,
} from './PricingCurrencies';
import type { Fee } from './Fee';
import {
    FeeFromJSON,
    FeeFromJSONTyped,
    FeeToJSON,
    FeeToJSONTyped,
} from './Fee';
import type { CollectionRarity } from './CollectionRarity';
import {
    CollectionRarityFromJSON,
    CollectionRarityFromJSONTyped,
    CollectionRarityToJSON,
    CollectionRarityToJSONTyped,
} from './CollectionRarity';
import type { Contract } from './Contract';
import {
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
    ContractToJSONTyped,
} from './Contract';

/**
 * 
 * @export
 * @interface CollectionDetailedResponse
 */
export interface CollectionDetailedResponse {
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    bannerImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    safelistStatus: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    category?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDetailedResponse
     */
    isDisabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDetailedResponse
     */
    isNsfw: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDetailedResponse
     */
    traitOffersEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDetailedResponse
     */
    collectionOffersEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    openseaUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    projectUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    wikiUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    discordUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    telegramUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    twitterUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    instagramUsername?: string;
    /**
     * 
     * @type {Array<Contract>}
     * @memberof CollectionDetailedResponse
     */
    contracts: Array<Contract>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionDetailedResponse
     */
    editors: Array<string>;
    /**
     * 
     * @type {Array<Fee>}
     * @memberof CollectionDetailedResponse
     */
    fees: Array<Fee>;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedResponse
     */
    requiredZone?: string;
    /**
     * 
     * @type {CollectionRarity}
     * @memberof CollectionDetailedResponse
     */
    rarity?: CollectionRarity;
    /**
     * 
     * @type {number}
     * @memberof CollectionDetailedResponse
     */
    totalSupply: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionDetailedResponse
     */
    uniqueItemCount: number;
    /**
     * 
     * @type {Date}
     * @memberof CollectionDetailedResponse
     */
    createdDate: Date;
    /**
     * 
     * @type {PricingCurrencies}
     * @memberof CollectionDetailedResponse
     */
    pricingCurrencies: PricingCurrencies;
}

/**
 * Check if a given object implements the CollectionDetailedResponse interface.
 */
export function instanceOfCollectionDetailedResponse(value: object): value is CollectionDetailedResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('safelistStatus' in value) || value['safelistStatus'] === undefined) return false;
    if (!('isDisabled' in value) || value['isDisabled'] === undefined) return false;
    if (!('isNsfw' in value) || value['isNsfw'] === undefined) return false;
    if (!('traitOffersEnabled' in value) || value['traitOffersEnabled'] === undefined) return false;
    if (!('collectionOffersEnabled' in value) || value['collectionOffersEnabled'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    if (!('contracts' in value) || value['contracts'] === undefined) return false;
    if (!('editors' in value) || value['editors'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('totalSupply' in value) || value['totalSupply'] === undefined) return false;
    if (!('uniqueItemCount' in value) || value['uniqueItemCount'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('pricingCurrencies' in value) || value['pricingCurrencies'] === undefined) return false;
    return true;
}

export function CollectionDetailedResponseFromJSON(json: any): CollectionDetailedResponse {
    return CollectionDetailedResponseFromJSONTyped(json, false);
}

export function CollectionDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionDetailedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'bannerImageUrl': json['banner_image_url'] == null ? undefined : json['banner_image_url'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'safelistStatus': json['safelist_status'],
        'category': json['category'] == null ? undefined : json['category'],
        'isDisabled': json['is_disabled'],
        'isNsfw': json['is_nsfw'],
        'traitOffersEnabled': json['trait_offers_enabled'],
        'collectionOffersEnabled': json['collection_offers_enabled'],
        'openseaUrl': json['opensea_url'],
        'projectUrl': json['project_url'] == null ? undefined : json['project_url'],
        'wikiUrl': json['wiki_url'] == null ? undefined : json['wiki_url'],
        'discordUrl': json['discord_url'] == null ? undefined : json['discord_url'],
        'telegramUrl': json['telegram_url'] == null ? undefined : json['telegram_url'],
        'twitterUsername': json['twitter_username'] == null ? undefined : json['twitter_username'],
        'instagramUsername': json['instagram_username'] == null ? undefined : json['instagram_username'],
        'contracts': ((json['contracts'] as Array<any>).map(ContractFromJSON)),
        'editors': json['editors'],
        'fees': ((json['fees'] as Array<any>).map(FeeFromJSON)),
        'requiredZone': json['required_zone'] == null ? undefined : json['required_zone'],
        'rarity': json['rarity'] == null ? undefined : CollectionRarityFromJSON(json['rarity']),
        'totalSupply': json['total_supply'],
        'uniqueItemCount': json['unique_item_count'],
        'createdDate': (new Date(json['created_date'])),
        'pricingCurrencies': PricingCurrenciesFromJSON(json['pricing_currencies']),
    };
}

export function CollectionDetailedResponseToJSON(json: any): CollectionDetailedResponse {
    return CollectionDetailedResponseToJSONTyped(json, false);
}

export function CollectionDetailedResponseToJSONTyped(value?: CollectionDetailedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'name': value['name'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'banner_image_url': value['bannerImageUrl'],
        'owner': value['owner'],
        'safelist_status': value['safelistStatus'],
        'category': value['category'],
        'is_disabled': value['isDisabled'],
        'is_nsfw': value['isNsfw'],
        'trait_offers_enabled': value['traitOffersEnabled'],
        'collection_offers_enabled': value['collectionOffersEnabled'],
        'opensea_url': value['openseaUrl'],
        'project_url': value['projectUrl'],
        'wiki_url': value['wikiUrl'],
        'discord_url': value['discordUrl'],
        'telegram_url': value['telegramUrl'],
        'twitter_username': value['twitterUsername'],
        'instagram_username': value['instagramUsername'],
        'contracts': ((value['contracts'] as Array<any>).map(ContractToJSON)),
        'editors': value['editors'],
        'fees': ((value['fees'] as Array<any>).map(FeeToJSON)),
        'required_zone': value['requiredZone'],
        'rarity': CollectionRarityToJSON(value['rarity']),
        'total_supply': value['totalSupply'],
        'unique_item_count': value['uniqueItemCount'],
        'created_date': value['createdDate'].toISOString(),
        'pricing_currencies': PricingCurrenciesToJSON(value['pricingCurrencies']),
    };
}

