/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionOfferAggregateResponse } from './CollectionOfferAggregateResponse';
import {
    CollectionOfferAggregateResponseFromJSON,
    CollectionOfferAggregateResponseFromJSONTyped,
    CollectionOfferAggregateResponseToJSON,
    CollectionOfferAggregateResponseToJSONTyped,
} from './CollectionOfferAggregateResponse';

/**
 * Paginated list of collection offer aggregates
 * @export
 * @interface CollectionOfferAggregatesPaginatedResponse
 */
export interface CollectionOfferAggregatesPaginatedResponse {
    /**
     * List of offer aggregates
     * @type {Array<CollectionOfferAggregateResponse>}
     * @memberof CollectionOfferAggregatesPaginatedResponse
     */
    offerAggregates: Array<CollectionOfferAggregateResponse>;
    /**
     * Cursor for the next page of results
     * @type {string}
     * @memberof CollectionOfferAggregatesPaginatedResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the CollectionOfferAggregatesPaginatedResponse interface.
 */
export function instanceOfCollectionOfferAggregatesPaginatedResponse(value: object): value is CollectionOfferAggregatesPaginatedResponse {
    if (!('offerAggregates' in value) || value['offerAggregates'] === undefined) return false;
    return true;
}

export function CollectionOfferAggregatesPaginatedResponseFromJSON(json: any): CollectionOfferAggregatesPaginatedResponse {
    return CollectionOfferAggregatesPaginatedResponseFromJSONTyped(json, false);
}

export function CollectionOfferAggregatesPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionOfferAggregatesPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'offerAggregates': ((json['offer_aggregates'] as Array<any>).map(CollectionOfferAggregateResponseFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function CollectionOfferAggregatesPaginatedResponseToJSON(json: any): CollectionOfferAggregatesPaginatedResponse {
    return CollectionOfferAggregatesPaginatedResponseToJSONTyped(json, false);
}

export function CollectionOfferAggregatesPaginatedResponseToJSONTyped(value?: CollectionOfferAggregatesPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offer_aggregates': ((value['offerAggregates'] as Array<any>).map(CollectionOfferAggregateResponseToJSON)),
        'next': value['next'],
    };
}

