/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Contract } from './Contract';
import {
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
    ContractToJSONTyped,
} from './Contract';

/**
 * 
 * @export
 * @interface CollectionResponse
 */
export interface CollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    bannerImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    safelistStatus: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    category?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionResponse
     */
    isDisabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionResponse
     */
    isNsfw: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionResponse
     */
    traitOffersEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionResponse
     */
    collectionOffersEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    openseaUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    projectUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    wikiUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    discordUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    telegramUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    twitterUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionResponse
     */
    instagramUsername?: string;
    /**
     * 
     * @type {Array<Contract>}
     * @memberof CollectionResponse
     */
    contracts: Array<Contract>;
}

/**
 * Check if a given object implements the CollectionResponse interface.
 */
export function instanceOfCollectionResponse(value: object): value is CollectionResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('safelistStatus' in value) || value['safelistStatus'] === undefined) return false;
    if (!('isDisabled' in value) || value['isDisabled'] === undefined) return false;
    if (!('isNsfw' in value) || value['isNsfw'] === undefined) return false;
    if (!('traitOffersEnabled' in value) || value['traitOffersEnabled'] === undefined) return false;
    if (!('collectionOffersEnabled' in value) || value['collectionOffersEnabled'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    if (!('contracts' in value) || value['contracts'] === undefined) return false;
    return true;
}

export function CollectionResponseFromJSON(json: any): CollectionResponse {
    return CollectionResponseFromJSONTyped(json, false);
}

export function CollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'bannerImageUrl': json['banner_image_url'] == null ? undefined : json['banner_image_url'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'safelistStatus': json['safelist_status'],
        'category': json['category'] == null ? undefined : json['category'],
        'isDisabled': json['is_disabled'],
        'isNsfw': json['is_nsfw'],
        'traitOffersEnabled': json['trait_offers_enabled'],
        'collectionOffersEnabled': json['collection_offers_enabled'],
        'openseaUrl': json['opensea_url'],
        'projectUrl': json['project_url'] == null ? undefined : json['project_url'],
        'wikiUrl': json['wiki_url'] == null ? undefined : json['wiki_url'],
        'discordUrl': json['discord_url'] == null ? undefined : json['discord_url'],
        'telegramUrl': json['telegram_url'] == null ? undefined : json['telegram_url'],
        'twitterUsername': json['twitter_username'] == null ? undefined : json['twitter_username'],
        'instagramUsername': json['instagram_username'] == null ? undefined : json['instagram_username'],
        'contracts': ((json['contracts'] as Array<any>).map(ContractFromJSON)),
    };
}

export function CollectionResponseToJSON(json: any): CollectionResponse {
    return CollectionResponseToJSONTyped(json, false);
}

export function CollectionResponseToJSONTyped(value?: CollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'name': value['name'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'banner_image_url': value['bannerImageUrl'],
        'owner': value['owner'],
        'safelist_status': value['safelistStatus'],
        'category': value['category'],
        'is_disabled': value['isDisabled'],
        'is_nsfw': value['isNsfw'],
        'trait_offers_enabled': value['traitOffersEnabled'],
        'collection_offers_enabled': value['collectionOffersEnabled'],
        'opensea_url': value['openseaUrl'],
        'project_url': value['projectUrl'],
        'wiki_url': value['wikiUrl'],
        'discord_url': value['discordUrl'],
        'telegram_url': value['telegramUrl'],
        'twitter_username': value['twitterUsername'],
        'instagram_username': value['instagramUsername'],
        'contracts': ((value['contracts'] as Array<any>).map(ContractToJSON)),
    };
}

