/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionInner
 */
export interface CollectionInner {
    /**
     * 
     * @type {string}
     * @memberof CollectionInner
     */
    slug: string;
}

/**
 * Check if a given object implements the CollectionInner interface.
 */
export function instanceOfCollectionInner(value: object): value is CollectionInner {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function CollectionInnerFromJSON(json: any): CollectionInner {
    return CollectionInnerFromJSONTyped(json, false);
}

export function CollectionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
    };
}

export function CollectionInnerToJSON(json: any): CollectionInner {
    return CollectionInnerToJSONTyped(json, false);
}

export function CollectionInnerToJSONTyped(value?: CollectionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
    };
}

