/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A collection holder
 * @export
 * @interface CollectionHolderResponse
 */
export interface CollectionHolderResponse {
    /**
     * Wallet address of the holder
     * @type {string}
     * @memberof CollectionHolderResponse
     */
    address: string;
    /**
     * Number of items held
     * @type {number}
     * @memberof CollectionHolderResponse
     */
    quantity: number;
    /**
     * Ownership percentage of the collection
     * @type {number}
     * @memberof CollectionHolderResponse
     */
    percentage: number;
}

/**
 * Check if a given object implements the CollectionHolderResponse interface.
 */
export function instanceOfCollectionHolderResponse(value: object): value is CollectionHolderResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function CollectionHolderResponseFromJSON(json: any): CollectionHolderResponse {
    return CollectionHolderResponseFromJSONTyped(json, false);
}

export function CollectionHolderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionHolderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'quantity': json['quantity'],
        'percentage': json['percentage'],
    };
}

export function CollectionHolderResponseToJSON(json: any): CollectionHolderResponse {
    return CollectionHolderResponseToJSONTyped(json, false);
}

export function CollectionHolderResponseToJSONTyped(value?: CollectionHolderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'quantity': value['quantity'],
        'percentage': value['percentage'],
    };
}

