/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntervalStat } from './IntervalStat';
import {
    IntervalStatFromJSON,
    IntervalStatFromJSONTyped,
    IntervalStatToJSON,
    IntervalStatToJSONTyped,
} from './IntervalStat';
import type { Total } from './Total';
import {
    TotalFromJSON,
    TotalFromJSONTyped,
    TotalToJSON,
    TotalToJSONTyped,
} from './Total';

/**
 * 
 * @export
 * @interface CollectionStatsResponse
 */
export interface CollectionStatsResponse {
    /**
     * 
     * @type {Total}
     * @memberof CollectionStatsResponse
     */
    total: Total;
    /**
     * 
     * @type {Array<IntervalStat>}
     * @memberof CollectionStatsResponse
     */
    intervals: Array<IntervalStat>;
}

/**
 * Check if a given object implements the CollectionStatsResponse interface.
 */
export function instanceOfCollectionStatsResponse(value: object): value is CollectionStatsResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('intervals' in value) || value['intervals'] === undefined) return false;
    return true;
}

export function CollectionStatsResponseFromJSON(json: any): CollectionStatsResponse {
    return CollectionStatsResponseFromJSONTyped(json, false);
}

export function CollectionStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': TotalFromJSON(json['total']),
        'intervals': ((json['intervals'] as Array<any>).map(IntervalStatFromJSON)),
    };
}

export function CollectionStatsResponseToJSON(json: any): CollectionStatsResponse {
    return CollectionStatsResponseToJSONTyped(json, false);
}

export function CollectionStatsResponseToJSONTyped(value?: CollectionStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': TotalToJSON(value['total']),
        'intervals': ((value['intervals'] as Array<any>).map(IntervalStatToJSON)),
    };
}

