/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionHolderResponse } from './CollectionHolderResponse';
import {
    CollectionHolderResponseFromJSON,
    CollectionHolderResponseFromJSONTyped,
    CollectionHolderResponseToJSON,
    CollectionHolderResponseToJSONTyped,
} from './CollectionHolderResponse';

/**
 * Paginated list of collection holders
 * @export
 * @interface CollectionHoldersPaginatedResponse
 */
export interface CollectionHoldersPaginatedResponse {
    /**
     * List of holders
     * @type {Array<CollectionHolderResponse>}
     * @memberof CollectionHoldersPaginatedResponse
     */
    holders: Array<CollectionHolderResponse>;
    /**
     * Cursor for the next page of results
     * @type {string}
     * @memberof CollectionHoldersPaginatedResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the CollectionHoldersPaginatedResponse interface.
 */
export function instanceOfCollectionHoldersPaginatedResponse(value: object): value is CollectionHoldersPaginatedResponse {
    if (!('holders' in value) || value['holders'] === undefined) return false;
    return true;
}

export function CollectionHoldersPaginatedResponseFromJSON(json: any): CollectionHoldersPaginatedResponse {
    return CollectionHoldersPaginatedResponseFromJSONTyped(json, false);
}

export function CollectionHoldersPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionHoldersPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'holders': ((json['holders'] as Array<any>).map(CollectionHolderResponseFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function CollectionHoldersPaginatedResponseToJSON(json: any): CollectionHoldersPaginatedResponse {
    return CollectionHoldersPaginatedResponseToJSONTyped(json, false);
}

export function CollectionHoldersPaginatedResponseToJSONTyped(value?: CollectionHoldersPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'holders': ((value['holders'] as Array<any>).map(CollectionHolderResponseToJSON)),
        'next': value['next'],
    };
}

