/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Collection search result
 * @export
 * @interface CollectionSearchResponse
 */
export interface CollectionSearchResponse {
    /**
     * The collection slug
     * @type {string}
     * @memberof CollectionSearchResponse
     */
    collection: string;
    /**
     * The collection name
     * @type {string}
     * @memberof CollectionSearchResponse
     */
    name: string;
    /**
     * URL of the collection image
     * @type {string}
     * @memberof CollectionSearchResponse
     */
    imageUrl?: string;
    /**
     * Whether trading is disabled for this collection
     * @type {boolean}
     * @memberof CollectionSearchResponse
     */
    isDisabled: boolean;
    /**
     * Whether this collection is marked as NSFW
     * @type {boolean}
     * @memberof CollectionSearchResponse
     */
    isNsfw: boolean;
    /**
     * URL to the collection on OpenSea
     * @type {string}
     * @memberof CollectionSearchResponse
     */
    openseaUrl: string;
}

/**
 * Check if a given object implements the CollectionSearchResponse interface.
 */
export function instanceOfCollectionSearchResponse(value: object): value is CollectionSearchResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isDisabled' in value) || value['isDisabled'] === undefined) return false;
    if (!('isNsfw' in value) || value['isNsfw'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    return true;
}

export function CollectionSearchResponseFromJSON(json: any): CollectionSearchResponse {
    return CollectionSearchResponseFromJSONTyped(json, false);
}

export function CollectionSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
        'name': json['name'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'isDisabled': json['is_disabled'],
        'isNsfw': json['is_nsfw'],
        'openseaUrl': json['opensea_url'],
    };
}

export function CollectionSearchResponseToJSON(json: any): CollectionSearchResponse {
    return CollectionSearchResponseToJSONTyped(json, false);
}

export function CollectionSearchResponseToJSONTyped(value?: CollectionSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'name': value['name'],
        'image_url': value['imageUrl'],
        'is_disabled': value['isDisabled'],
        'is_nsfw': value['isNsfw'],
        'opensea_url': value['openseaUrl'],
    };
}

