/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsiderationObject
 */
export interface ConsiderationObject {
    /**
     * 
     * @type {string}
     * @memberof ConsiderationObject
     */
    assetContractAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ConsiderationObject
     */
    tokenId: string;
}

/**
 * Check if a given object implements the ConsiderationObject interface.
 */
export function instanceOfConsiderationObject(value: object): value is ConsiderationObject {
    if (!('assetContractAddress' in value) || value['assetContractAddress'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    return true;
}

export function ConsiderationObjectFromJSON(json: any): ConsiderationObject {
    return ConsiderationObjectFromJSONTyped(json, false);
}

export function ConsiderationObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsiderationObject {
    if (json == null) {
        return json;
    }
    return {
        
        'assetContractAddress': json['asset_contract_address'],
        'tokenId': json['token_id'],
    };
}

export function ConsiderationObjectToJSON(json: any): ConsiderationObject {
    return ConsiderationObjectToJSONTyped(json, false);
}

export function ConsiderationObjectToJSONTyped(value?: ConsiderationObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_contract_address': value['assetContractAddress'],
        'token_id': value['tokenId'],
    };
}

