/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Consideration
 */
export interface Consideration {
    /**
     * 
     * @type {number}
     * @memberof Consideration
     */
    itemType: number;
    /**
     * 
     * @type {string}
     * @memberof Consideration
     */
    token: string;
    /**
     * For criteria-based offers, this is the merkle root of eligible token IDs. For trait offers on supported collections, this will be '0' — trait matching is validated server-side at fulfillment time instead of via onchain merkle proof.
     * @type {string}
     * @memberof Consideration
     */
    identifierOrCriteria: string;
    /**
     * 
     * @type {string}
     * @memberof Consideration
     */
    startAmount: string;
    /**
     * 
     * @type {string}
     * @memberof Consideration
     */
    endAmount: string;
    /**
     * 
     * @type {string}
     * @memberof Consideration
     */
    recipient: string;
}

/**
 * Check if a given object implements the Consideration interface.
 */
export function instanceOfConsideration(value: object): value is Consideration {
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('identifierOrCriteria' in value) || value['identifierOrCriteria'] === undefined) return false;
    if (!('startAmount' in value) || value['startAmount'] === undefined) return false;
    if (!('endAmount' in value) || value['endAmount'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function ConsiderationFromJSON(json: any): Consideration {
    return ConsiderationFromJSONTyped(json, false);
}

export function ConsiderationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Consideration {
    if (json == null) {
        return json;
    }
    return {
        
        'itemType': json['itemType'],
        'token': json['token'],
        'identifierOrCriteria': json['identifierOrCriteria'],
        'startAmount': json['startAmount'],
        'endAmount': json['endAmount'],
        'recipient': json['recipient'],
    };
}

export function ConsiderationToJSON(json: any): Consideration {
    return ConsiderationToJSONTyped(json, false);
}

export function ConsiderationToJSONTyped(value?: Consideration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemType': value['itemType'],
        'token': value['token'],
        'identifierOrCriteria': value['identifierOrCriteria'],
        'startAmount': value['startAmount'],
        'endAmount': value['endAmount'],
        'recipient': value['recipient'],
    };
}

