/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractCriteria
 */
export interface ContractCriteria {
    /**
     * 
     * @type {string}
     * @memberof ContractCriteria
     */
    address: string;
}

/**
 * Check if a given object implements the ContractCriteria interface.
 */
export function instanceOfContractCriteria(value: object): value is ContractCriteria {
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function ContractCriteriaFromJSON(json: any): ContractCriteria {
    return ContractCriteriaFromJSONTyped(json, false);
}

export function ContractCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function ContractCriteriaToJSON(json: any): ContractCriteria {
    return ContractCriteriaToJSONTyped(json, false);
}

export function ContractCriteriaToJSONTyped(value?: ContractCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
    };
}

