/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractResponse
 */
export interface ContractResponse {
    /**
     * 
     * @type {string}
     * @memberof ContractResponse
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof ContractResponse
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof ContractResponse
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof ContractResponse
     */
    contractStandard: string;
    /**
     * 
     * @type {string}
     * @memberof ContractResponse
     */
    name: string;
}

/**
 * Check if a given object implements the ContractResponse interface.
 */
export function instanceOfContractResponse(value: object): value is ContractResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('contractStandard' in value) || value['contractStandard'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ContractResponseFromJSON(json: any): ContractResponse {
    return ContractResponseFromJSONTyped(json, false);
}

export function ContractResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chain': json['chain'],
        'collection': json['collection'],
        'contractStandard': json['contract_standard'],
        'name': json['name'],
    };
}

export function ContractResponseToJSON(json: any): ContractResponse {
    return ContractResponseToJSONTyped(json, false);
}

export function ContractResponseToJSONTyped(value?: ContractResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'collection': value['collection'],
        'contract_standard': value['contractStandard'],
        'name': value['name'],
    };
}

