/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractInner
 */
export interface ContractInner {
    /**
     * 
     * @type {string}
     * @memberof ContractInner
     */
    address: string;
}

/**
 * Check if a given object implements the ContractInner interface.
 */
export function instanceOfContractInner(value: object): value is ContractInner {
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function ContractInnerFromJSON(json: any): ContractInner {
    return ContractInnerFromJSONTyped(json, false);
}

export function ContractInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractInner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function ContractInnerToJSON(json: any): ContractInner {
    return ContractInnerToJSONTyped(json, false);
}

export function ContractInnerToJSONTyped(value?: ContractInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
    };
}

