/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response containing blockchain actions to execute for listing creation
 * @export
 * @interface CreateListingActionsResponse
 */
export interface CreateListingActionsResponse {
    /**
     * Ordered list of blockchain actions to execute. May include approval actions (e.g. setApprovalForAll) and a createListingsAction containing the Seaport order to sign. Serialized using proto3 JSON format — fields with default values (empty string, 0, false) may be omitted.
     * @type {Array<any>}
     * @memberof CreateListingActionsResponse
     */
    steps: Array<any>;
}

/**
 * Check if a given object implements the CreateListingActionsResponse interface.
 */
export function instanceOfCreateListingActionsResponse(value: object): value is CreateListingActionsResponse {
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function CreateListingActionsResponseFromJSON(json: any): CreateListingActionsResponse {
    return CreateListingActionsResponseFromJSONTyped(json, false);
}

export function CreateListingActionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListingActionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': json['steps'],
    };
}

export function CreateListingActionsResponseToJSON(json: any): CreateListingActionsResponse {
    return CreateListingActionsResponseToJSONTyped(json, false);
}

export function CreateListingActionsResponseToJSONTyped(value?: CreateListingActionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': value['steps'],
    };
}

