/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';

/**
 * 
 * @export
 * @interface CriteriaResolver
 */
export interface CriteriaResolver {
    /**
     * 
     * @type {Array<Type>}
     * @memberof CriteriaResolver
     */
    value?: Array<Type>;
    /**
     * 
     * @type {number}
     * @memberof CriteriaResolver
     */
    orderIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof CriteriaResolver
     */
    side?: number;
    /**
     * 
     * @type {number}
     * @memberof CriteriaResolver
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof CriteriaResolver
     */
    identifier?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CriteriaResolver
     */
    criteriaProof?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CriteriaResolver
     */
    typeAsString?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof CriteriaResolver
     */
    nativeValueCopy?: Array<any>;
}

/**
 * Check if a given object implements the CriteriaResolver interface.
 */
export function instanceOfCriteriaResolver(value: object): value is CriteriaResolver {
    return true;
}

export function CriteriaResolverFromJSON(json: any): CriteriaResolver {
    return CriteriaResolverFromJSONTyped(json, false);
}

export function CriteriaResolverFromJSONTyped(json: any, ignoreDiscriminator: boolean): CriteriaResolver {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(TypeFromJSON)),
        'orderIndex': json['orderIndex'] == null ? undefined : json['orderIndex'],
        'side': json['side'] == null ? undefined : json['side'],
        'index': json['index'] == null ? undefined : json['index'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'criteriaProof': json['criteriaProof'] == null ? undefined : json['criteriaProof'],
        'typeAsString': json['typeAsString'] == null ? undefined : json['typeAsString'],
        'nativeValueCopy': json['nativeValueCopy'] == null ? undefined : json['nativeValueCopy'],
    };
}

export function CriteriaResolverToJSON(json: any): CriteriaResolver {
    return CriteriaResolverToJSONTyped(json, false);
}

export function CriteriaResolverToJSONTyped(value?: CriteriaResolver | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(TypeToJSON)),
        'orderIndex': value['orderIndex'],
        'side': value['side'],
        'index': value['index'],
        'identifier': value['identifier'],
        'criteriaProof': value['criteriaProof'],
        'typeAsString': value['typeAsString'],
        'nativeValueCopy': value['nativeValueCopy'],
    };
}

