/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionInner } from './CollectionInner';
import {
    CollectionInnerFromJSON,
    CollectionInnerFromJSONTyped,
    CollectionInnerToJSON,
    CollectionInnerToJSONTyped,
} from './CollectionInner';
import type { ContractInner } from './ContractInner';
import {
    ContractInnerFromJSON,
    ContractInnerFromJSONTyped,
    ContractInnerToJSON,
    ContractInnerToJSONTyped,
} from './ContractInner';
import type { NumericTraitData } from './NumericTraitData';
import {
    NumericTraitDataFromJSON,
    NumericTraitDataFromJSONTyped,
    NumericTraitDataToJSON,
    NumericTraitDataToJSONTyped,
} from './NumericTraitData';
import type { TraitData } from './TraitData';
import {
    TraitDataFromJSON,
    TraitDataFromJSONTyped,
    TraitDataToJSON,
    TraitDataToJSONTyped,
} from './TraitData';

/**
 * 
 * @export
 * @interface Criteria
 */
export interface Criteria {
    /**
     * 
     * @type {CollectionInner}
     * @memberof Criteria
     */
    collection?: CollectionInner;
    /**
     * 
     * @type {ContractInner}
     * @memberof Criteria
     */
    contract?: ContractInner;
    /**
     * 
     * @type {Array<TraitData>}
     * @memberof Criteria
     */
    traits?: Array<TraitData>;
    /**
     * 
     * @type {Array<NumericTraitData>}
     * @memberof Criteria
     */
    numericTraits?: Array<NumericTraitData>;
    /**
     * 
     * @type {string}
     * @memberof Criteria
     */
    encodedTokenIds?: string;
}

/**
 * Check if a given object implements the Criteria interface.
 */
export function instanceOfCriteria(value: object): value is Criteria {
    return true;
}

export function CriteriaFromJSON(json: any): Criteria {
    return CriteriaFromJSONTyped(json, false);
}

export function CriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Criteria {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'] == null ? undefined : CollectionInnerFromJSON(json['collection']),
        'contract': json['contract'] == null ? undefined : ContractInnerFromJSON(json['contract']),
        'traits': json['traits'] == null ? undefined : ((json['traits'] as Array<any>).map(TraitDataFromJSON)),
        'numericTraits': json['numeric_traits'] == null ? undefined : ((json['numeric_traits'] as Array<any>).map(NumericTraitDataFromJSON)),
        'encodedTokenIds': json['encoded_token_ids'] == null ? undefined : json['encoded_token_ids'],
    };
}

export function CriteriaToJSON(json: any): Criteria {
    return CriteriaToJSONTyped(json, false);
}

export function CriteriaToJSONTyped(value?: Criteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionInnerToJSON(value['collection']),
        'contract': ContractInnerToJSON(value['contract']),
        'traits': value['traits'] == null ? undefined : ((value['traits'] as Array<any>).map(TraitDataToJSON)),
        'numeric_traits': value['numericTraits'] == null ? undefined : ((value['numericTraits'] as Array<any>).map(NumericTraitDataToJSON)),
        'encoded_token_ids': value['encodedTokenIds'],
    };
}

