/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payment token to use for cross-chain fulfillment
 * @export
 * @interface CrossChainPaymentToken
 */
export interface CrossChainPaymentToken {
    /**
     * Chain of the payment token (e.g. 'base', 'ethereum')
     * @type {string}
     * @memberof CrossChainPaymentToken
     */
    chain: string;
    /**
     * Contract address of the payment token (use 0x0000000000000000000000000000000000000000 for native token)
     * @type {string}
     * @memberof CrossChainPaymentToken
     */
    tokenAddress: string;
}

/**
 * Check if a given object implements the CrossChainPaymentToken interface.
 */
export function instanceOfCrossChainPaymentToken(value: object): value is CrossChainPaymentToken {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('tokenAddress' in value) || value['tokenAddress'] === undefined) return false;
    return true;
}

export function CrossChainPaymentTokenFromJSON(json: any): CrossChainPaymentToken {
    return CrossChainPaymentTokenFromJSONTyped(json, false);
}

export function CrossChainPaymentTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossChainPaymentToken {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'tokenAddress': json['token_address'],
    };
}

export function CrossChainPaymentTokenToJSON(json: any): CrossChainPaymentToken {
    return CrossChainPaymentTokenToJSONTyped(json, false);
}

export function CrossChainPaymentTokenToJSONTyped(value?: CrossChainPaymentToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'token_address': value['tokenAddress'],
    };
}

