/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SwapTransactionResponse } from './SwapTransactionResponse';
import {
    SwapTransactionResponseFromJSON,
    SwapTransactionResponseFromJSONTyped,
    SwapTransactionResponseToJSON,
    SwapTransactionResponseToJSONTyped,
} from './SwapTransactionResponse';

/**
 * Response containing ordered transactions to execute for cross-chain fulfillment
 * @export
 * @interface CrossChainFulfillmentResponse
 */
export interface CrossChainFulfillmentResponse {
    /**
     * Ordered list of transactions to execute. May include approval and buy/swap transactions.
     * @type {Array<SwapTransactionResponse>}
     * @memberof CrossChainFulfillmentResponse
     */
    transactions: Array<SwapTransactionResponse>;
}

/**
 * Check if a given object implements the CrossChainFulfillmentResponse interface.
 */
export function instanceOfCrossChainFulfillmentResponse(value: object): value is CrossChainFulfillmentResponse {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function CrossChainFulfillmentResponseFromJSON(json: any): CrossChainFulfillmentResponse {
    return CrossChainFulfillmentResponseFromJSONTyped(json, false);
}

export function CrossChainFulfillmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossChainFulfillmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': ((json['transactions'] as Array<any>).map(SwapTransactionResponseFromJSON)),
    };
}

export function CrossChainFulfillmentResponseToJSON(json: any): CrossChainFulfillmentResponse {
    return CrossChainFulfillmentResponseToJSONTyped(json, false);
}

export function CrossChainFulfillmentResponseToJSONTyped(value?: CrossChainFulfillmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': ((value['transactions'] as Array<any>).map(SwapTransactionResponseToJSON)),
    };
}

