/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Deploy contract request parameters
 * @export
 * @interface DropDeployRequest
 */
export interface DropDeployRequest {
    /**
     * Chain slug (e.g. "ethereum", "base")
     * @type {string}
     * @memberof DropDeployRequest
     */
    chain: string;
    /**
     * Name for the new contract
     * @type {string}
     * @memberof DropDeployRequest
     */
    contractName: string;
    /**
     * Symbol for the new contract
     * @type {string}
     * @memberof DropDeployRequest
     */
    contractSymbol: string;
    /**
     * Drop type (see validation error for supported values)
     * @type {string}
     * @memberof DropDeployRequest
     */
    dropType: string;
    /**
     * Token type (see validation error for supported values)
     * @type {string}
     * @memberof DropDeployRequest
     */
    tokenType: string;
    /**
     * Deployer wallet address
     * @type {string}
     * @memberof DropDeployRequest
     */
    sender: string;
}

/**
 * Check if a given object implements the DropDeployRequest interface.
 */
export function instanceOfDropDeployRequest(value: object): value is DropDeployRequest {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contractName' in value) || value['contractName'] === undefined) return false;
    if (!('contractSymbol' in value) || value['contractSymbol'] === undefined) return false;
    if (!('dropType' in value) || value['dropType'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    return true;
}

export function DropDeployRequestFromJSON(json: any): DropDeployRequest {
    return DropDeployRequestFromJSONTyped(json, false);
}

export function DropDeployRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropDeployRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contractName': json['contract_name'],
        'contractSymbol': json['contract_symbol'],
        'dropType': json['drop_type'],
        'tokenType': json['token_type'],
        'sender': json['sender'],
    };
}

export function DropDeployRequestToJSON(json: any): DropDeployRequest {
    return DropDeployRequestToJSONTyped(json, false);
}

export function DropDeployRequestToJSONTyped(value?: DropDeployRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract_name': value['contractName'],
        'contract_symbol': value['contractSymbol'],
        'drop_type': value['dropType'],
        'token_type': value['tokenType'],
        'sender': value['sender'],
    };
}

