/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A mint stage within a drop
 * @export
 * @interface DropStageResponse
 */
export interface DropStageResponse {
    /**
     * Stage UUID
     * @type {string}
     * @memberof DropStageResponse
     */
    uuid: string;
    /**
     * Stage type
     * @type {string}
     * @memberof DropStageResponse
     */
    stageType: string;
    /**
     * Stage label/name
     * @type {string}
     * @memberof DropStageResponse
     */
    label?: string;
    /**
     * Mint price per token in wei (decimal string)
     * @type {string}
     * @memberof DropStageResponse
     */
    price?: string;
    /**
     * Currency contract address (e.g. 0x0000...0000 for native token)
     * @type {string}
     * @memberof DropStageResponse
     */
    priceCurrencyAddress: string;
    /**
     * Stage start time (ISO 8601)
     * @type {string}
     * @memberof DropStageResponse
     */
    startTime: string;
    /**
     * Stage end time (ISO 8601)
     * @type {string}
     * @memberof DropStageResponse
     */
    endTime: string;
    /**
     * Max tokens mintable per wallet in this stage
     * @type {string}
     * @memberof DropStageResponse
     */
    maxPerWallet: string;
}

/**
 * Check if a given object implements the DropStageResponse interface.
 */
export function instanceOfDropStageResponse(value: object): value is DropStageResponse {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('stageType' in value) || value['stageType'] === undefined) return false;
    if (!('priceCurrencyAddress' in value) || value['priceCurrencyAddress'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('maxPerWallet' in value) || value['maxPerWallet'] === undefined) return false;
    return true;
}

export function DropStageResponseFromJSON(json: any): DropStageResponse {
    return DropStageResponseFromJSONTyped(json, false);
}

export function DropStageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropStageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'stageType': json['stage_type'],
        'label': json['label'] == null ? undefined : json['label'],
        'price': json['price'] == null ? undefined : json['price'],
        'priceCurrencyAddress': json['price_currency_address'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'maxPerWallet': json['max_per_wallet'],
    };
}

export function DropStageResponseToJSON(json: any): DropStageResponse {
    return DropStageResponseToJSONTyped(json, false);
}

export function DropStageResponseToJSONTyped(value?: DropStageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'stage_type': value['stageType'],
        'label': value['label'],
        'price': value['price'],
        'price_currency_address': value['priceCurrencyAddress'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'max_per_wallet': value['maxPerWallet'],
    };
}

