/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DropResponse } from './DropResponse';
import {
    DropResponseFromJSON,
    DropResponseFromJSONTyped,
    DropResponseToJSON,
    DropResponseToJSONTyped,
} from './DropResponse';

/**
 * Paginated list of drops
 * @export
 * @interface DropPaginatedResponse
 */
export interface DropPaginatedResponse {
    /**
     * List of drops
     * @type {Array<DropResponse>}
     * @memberof DropPaginatedResponse
     */
    drops: Array<DropResponse>;
    /**
     * Cursor for the next page. May be present even when drops is empty if all items in the page were filtered by visibility rules; continue paginating until next is null.
     * @type {string}
     * @memberof DropPaginatedResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the DropPaginatedResponse interface.
 */
export function instanceOfDropPaginatedResponse(value: object): value is DropPaginatedResponse {
    if (!('drops' in value) || value['drops'] === undefined) return false;
    return true;
}

export function DropPaginatedResponseFromJSON(json: any): DropPaginatedResponse {
    return DropPaginatedResponseFromJSONTyped(json, false);
}

export function DropPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'drops': ((json['drops'] as Array<any>).map(DropResponseFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function DropPaginatedResponseToJSON(json: any): DropPaginatedResponse {
    return DropPaginatedResponseToJSONTyped(json, false);
}

export function DropPaginatedResponseToJSONTyped(value?: DropPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'drops': ((value['drops'] as Array<any>).map(DropResponseToJSON)),
        'next': value['next'],
    };
}

