/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Fee
 */
export interface Fee {
    /**
     * 
     * @type {number}
     * @memberof Fee
     */
    fee: number;
    /**
     * 
     * @type {string}
     * @memberof Fee
     */
    recipient: string;
    /**
     * 
     * @type {boolean}
     * @memberof Fee
     */
    required: boolean;
}

/**
 * Check if a given object implements the Fee interface.
 */
export function instanceOfFee(value: object): value is Fee {
    if (!('fee' in value) || value['fee'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    return true;
}

export function FeeFromJSON(json: any): Fee {
    return FeeFromJSONTyped(json, false);
}

export function FeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fee {
    if (json == null) {
        return json;
    }
    return {
        
        'fee': json['fee'],
        'recipient': json['recipient'],
        'required': json['required'],
    };
}

export function FeeToJSON(json: any): Fee {
    return FeeToJSONTyped(json, false);
}

export function FeeToJSONTyped(value?: Fee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee': value['fee'],
        'recipient': value['recipient'],
        'required': value['required'],
    };
}

