/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedOrder } from './AdvancedOrder';
import {
    AdvancedOrderFromJSON,
    AdvancedOrderFromJSONTyped,
    AdvancedOrderToJSON,
    AdvancedOrderToJSONTyped,
} from './AdvancedOrder';
import type { CriteriaResolver } from './CriteriaResolver';
import {
    CriteriaResolverFromJSON,
    CriteriaResolverFromJSONTyped,
    CriteriaResolverToJSON,
    CriteriaResolverToJSONTyped,
} from './CriteriaResolver';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface FulfillAdvancedOrder
 */
export interface FulfillAdvancedOrder {
    /**
     * 
     * @type {AdvancedOrder}
     * @memberof FulfillAdvancedOrder
     */
    advancedOrder: AdvancedOrder;
    /**
     * 
     * @type {Array<CriteriaResolver>}
     * @memberof FulfillAdvancedOrder
     */
    criteriaResolvers: Array<CriteriaResolver>;
    /**
     * 
     * @type {string}
     * @memberof FulfillAdvancedOrder
     */
    fulfillerConduitKey: string;
    /**
     * 
     * @type {Address}
     * @memberof FulfillAdvancedOrder
     */
    recipient: Address;
}

/**
 * Check if a given object implements the FulfillAdvancedOrder interface.
 */
export function instanceOfFulfillAdvancedOrder(value: object): value is FulfillAdvancedOrder {
    if (!('advancedOrder' in value) || value['advancedOrder'] === undefined) return false;
    if (!('criteriaResolvers' in value) || value['criteriaResolvers'] === undefined) return false;
    if (!('fulfillerConduitKey' in value) || value['fulfillerConduitKey'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function FulfillAdvancedOrderFromJSON(json: any): FulfillAdvancedOrder {
    return FulfillAdvancedOrderFromJSONTyped(json, false);
}

export function FulfillAdvancedOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillAdvancedOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'advancedOrder': AdvancedOrderFromJSON(json['advancedOrder']),
        'criteriaResolvers': ((json['criteriaResolvers'] as Array<any>).map(CriteriaResolverFromJSON)),
        'fulfillerConduitKey': json['fulfillerConduitKey'],
        'recipient': AddressFromJSON(json['recipient']),
    };
}

export function FulfillAdvancedOrderToJSON(json: any): FulfillAdvancedOrder {
    return FulfillAdvancedOrderToJSONTyped(json, false);
}

export function FulfillAdvancedOrderToJSONTyped(value?: FulfillAdvancedOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advancedOrder': AdvancedOrderToJSON(value['advancedOrder']),
        'criteriaResolvers': ((value['criteriaResolvers'] as Array<any>).map(CriteriaResolverToJSON)),
        'fulfillerConduitKey': value['fulfillerConduitKey'],
        'recipient': AddressToJSON(value['recipient']),
    };
}

