/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';

/**
 * 
 * @export
 * @interface FulfillmentComponent
 */
export interface FulfillmentComponent {
    /**
     * 
     * @type {Array<Type>}
     * @memberof FulfillmentComponent
     */
    value?: Array<Type>;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentComponent
     */
    orderIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentComponent
     */
    itemIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentComponent
     */
    typeAsString?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof FulfillmentComponent
     */
    nativeValueCopy?: Array<any>;
}

/**
 * Check if a given object implements the FulfillmentComponent interface.
 */
export function instanceOfFulfillmentComponent(value: object): value is FulfillmentComponent {
    return true;
}

export function FulfillmentComponentFromJSON(json: any): FulfillmentComponent {
    return FulfillmentComponentFromJSONTyped(json, false);
}

export function FulfillmentComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(TypeFromJSON)),
        'orderIndex': json['orderIndex'] == null ? undefined : json['orderIndex'],
        'itemIndex': json['itemIndex'] == null ? undefined : json['itemIndex'],
        'typeAsString': json['typeAsString'] == null ? undefined : json['typeAsString'],
        'nativeValueCopy': json['nativeValueCopy'] == null ? undefined : json['nativeValueCopy'],
    };
}

export function FulfillmentComponentToJSON(json: any): FulfillmentComponent {
    return FulfillmentComponentToJSONTyped(json, false);
}

export function FulfillmentComponentToJSONTyped(value?: FulfillmentComponent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(TypeToJSON)),
        'orderIndex': value['orderIndex'],
        'itemIndex': value['itemIndex'],
        'typeAsString': value['typeAsString'],
        'nativeValueCopy': value['nativeValueCopy'],
    };
}

