/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfillmentData } from './FulfillmentData';
import {
    FulfillmentDataFromJSON,
    FulfillmentDataFromJSONTyped,
    FulfillmentDataToJSON,
    FulfillmentDataToJSONTyped,
} from './FulfillmentData';

/**
 * 
 * @export
 * @interface FulfillListingResponse
 */
export interface FulfillListingResponse {
    /**
     * 
     * @type {string}
     * @memberof FulfillListingResponse
     */
    protocol: string;
    /**
     * 
     * @type {FulfillmentData}
     * @memberof FulfillListingResponse
     */
    fulfillmentData: FulfillmentData;
}

/**
 * Check if a given object implements the FulfillListingResponse interface.
 */
export function instanceOfFulfillListingResponse(value: object): value is FulfillListingResponse {
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('fulfillmentData' in value) || value['fulfillmentData'] === undefined) return false;
    return true;
}

export function FulfillListingResponseFromJSON(json: any): FulfillListingResponse {
    return FulfillListingResponseFromJSONTyped(json, false);
}

export function FulfillListingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillListingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'protocol': json['protocol'],
        'fulfillmentData': FulfillmentDataFromJSON(json['fulfillment_data']),
    };
}

export function FulfillListingResponseToJSON(json: any): FulfillListingResponse {
    return FulfillListingResponseToJSONTyped(json, false);
}

export function FulfillListingResponseToJSONTyped(value?: FulfillListingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol': value['protocol'],
        'fulfillment_data': FulfillmentDataToJSON(value['fulfillmentData']),
    };
}

