/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface FulfillOrder
 */
export interface FulfillOrder {
    /**
     * 
     * @type {Order}
     * @memberof FulfillOrder
     */
    order: Order;
    /**
     * 
     * @type {string}
     * @memberof FulfillOrder
     */
    fulfillerConduitKey: string;
}

/**
 * Check if a given object implements the FulfillOrder interface.
 */
export function instanceOfFulfillOrder(value: object): value is FulfillOrder {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('fulfillerConduitKey' in value) || value['fulfillerConduitKey'] === undefined) return false;
    return true;
}

export function FulfillOrderFromJSON(json: any): FulfillOrder {
    return FulfillOrderFromJSONTyped(json, false);
}

export function FulfillOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'order': OrderFromJSON(json['order']),
        'fulfillerConduitKey': json['fulfillerConduitKey'],
    };
}

export function FulfillOrderToJSON(json: any): FulfillOrder {
    return FulfillOrderToJSONTyped(json, false);
}

export function FulfillOrderToJSONTyped(value?: FulfillOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order': OrderToJSON(value['order']),
        'fulfillerConduitKey': value['fulfillerConduitKey'],
    };
}

