/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderData } from './OrderData';
import {
    OrderDataFromJSON,
    OrderDataFromJSONTyped,
    OrderDataToJSON,
    OrderDataToJSONTyped,
} from './OrderData';
import type { TransactionData } from './TransactionData';
import {
    TransactionDataFromJSON,
    TransactionDataFromJSONTyped,
    TransactionDataToJSON,
    TransactionDataToJSONTyped,
} from './TransactionData';

/**
 * 
 * @export
 * @interface FulfillmentData
 */
export interface FulfillmentData {
    /**
     * 
     * @type {TransactionData}
     * @memberof FulfillmentData
     */
    transaction: TransactionData;
    /**
     * 
     * @type {Array<OrderData>}
     * @memberof FulfillmentData
     */
    orders: Array<OrderData>;
}

/**
 * Check if a given object implements the FulfillmentData interface.
 */
export function instanceOfFulfillmentData(value: object): value is FulfillmentData {
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    return true;
}

export function FulfillmentDataFromJSON(json: any): FulfillmentData {
    return FulfillmentDataFromJSONTyped(json, false);
}

export function FulfillmentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentData {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': TransactionDataFromJSON(json['transaction']),
        'orders': ((json['orders'] as Array<any>).map(OrderDataFromJSON)),
    };
}

export function FulfillmentDataToJSON(json: any): FulfillmentData {
    return FulfillmentDataToJSONTyped(json, false);
}

export function FulfillmentDataToJSONTyped(value?: FulfillmentData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': TransactionDataToJSON(value['transaction']),
        'orders': ((value['orders'] as Array<any>).map(OrderDataToJSON)),
    };
}

