/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OfferObject } from './OfferObject';
import {
    OfferObjectFromJSON,
    OfferObjectFromJSONTyped,
    OfferObjectToJSON,
    OfferObjectToJSONTyped,
} from './OfferObject';
import type { FulfillerObject } from './FulfillerObject';
import {
    FulfillerObjectFromJSON,
    FulfillerObjectFromJSONTyped,
    FulfillerObjectToJSON,
    FulfillerObjectToJSONTyped,
} from './FulfillerObject';
import type { ConsiderationObject } from './ConsiderationObject';
import {
    ConsiderationObjectFromJSON,
    ConsiderationObjectFromJSONTyped,
    ConsiderationObjectToJSON,
    ConsiderationObjectToJSONTyped,
} from './ConsiderationObject';

/**
 * 
 * @export
 * @interface FullfillmentDataRequest
 */
export interface FullfillmentDataRequest {
    /**
     * 
     * @type {OfferObject}
     * @memberof FullfillmentDataRequest
     */
    offer: OfferObject;
    /**
     * 
     * @type {FulfillerObject}
     * @memberof FullfillmentDataRequest
     */
    fulfiller: FulfillerObject;
    /**
     * 
     * @type {ConsiderationObject}
     * @memberof FullfillmentDataRequest
     */
    consideration?: ConsiderationObject;
    /**
     * Optional quantity of units to fulfill; defaults to 1 for offers
     * @type {number}
     * @memberof FullfillmentDataRequest
     */
    unitsToFill?: number;
    /**
     * Whether to include optional creator fees in the fulfillment. If creator fees are already required, this is a no-op. Defaults to false.
     * @type {boolean}
     * @memberof FullfillmentDataRequest
     */
    includeOptionalCreatorFees?: boolean;
}

/**
 * Check if a given object implements the FullfillmentDataRequest interface.
 */
export function instanceOfFullfillmentDataRequest(value: object): value is FullfillmentDataRequest {
    if (!('offer' in value) || value['offer'] === undefined) return false;
    if (!('fulfiller' in value) || value['fulfiller'] === undefined) return false;
    return true;
}

export function FullfillmentDataRequestFromJSON(json: any): FullfillmentDataRequest {
    return FullfillmentDataRequestFromJSONTyped(json, false);
}

export function FullfillmentDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullfillmentDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offer': OfferObjectFromJSON(json['offer']),
        'fulfiller': FulfillerObjectFromJSON(json['fulfiller']),
        'consideration': json['consideration'] == null ? undefined : ConsiderationObjectFromJSON(json['consideration']),
        'unitsToFill': json['units_to_fill'] == null ? undefined : json['units_to_fill'],
        'includeOptionalCreatorFees': json['include_optional_creator_fees'] == null ? undefined : json['include_optional_creator_fees'],
    };
}

export function FullfillmentDataRequestToJSON(json: any): FullfillmentDataRequest {
    return FullfillmentDataRequestToJSONTyped(json, false);
}

export function FullfillmentDataRequestToJSONTyped(value?: FullfillmentDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offer': OfferObjectToJSON(value['offer']),
        'fulfiller': FulfillerObjectToJSON(value['fulfiller']),
        'consideration': ConsiderationObjectToJSON(value['consideration']),
        'units_to_fill': value['unitsToFill'],
        'include_optional_creator_fees': value['includeOptionalCreatorFees'],
    };
}

