/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Listing } from './Listing';
import {
    instanceOfListing,
    ListingFromJSON,
    ListingFromJSONTyped,
    ListingToJSON,
} from './Listing';
import type { Offer } from './Offer';
import {
    instanceOfOffer,
    OfferFromJSON,
    OfferFromJSONTyped,
    OfferToJSON,
} from './Offer';

/**
 * @type GetOrderResponseOrder
 * 
 * @export
 */
export type GetOrderResponseOrder = Listing | Offer;

export function GetOrderResponseOrderFromJSON(json: any): GetOrderResponseOrder {
    return GetOrderResponseOrderFromJSONTyped(json, false);
}

export function GetOrderResponseOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderResponseOrder {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfListing(json)) {
        return ListingFromJSONTyped(json, true);
    }
    if (instanceOfOffer(json)) {
        return OfferFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GetOrderResponseOrderToJSON(json: any): any {
    return GetOrderResponseOrderToJSONTyped(json, false);
}

export function GetOrderResponseOrderToJSONTyped(value?: GetOrderResponseOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfListing(value)) {
        return ListingToJSON(value as Listing);
    }
    if (instanceOfOffer(value)) {
        return OfferToJSON(value as Offer);
    }
    return {};
}

