/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    itemType: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    identifierOrCriteria: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    startAmount: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    endAmount: string;
}

/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('identifierOrCriteria' in value) || value['identifierOrCriteria'] === undefined) return false;
    if (!('startAmount' in value) || value['startAmount'] === undefined) return false;
    if (!('endAmount' in value) || value['endAmount'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'itemType': json['itemType'],
        'token': json['token'],
        'identifierOrCriteria': json['identifierOrCriteria'],
        'startAmount': json['startAmount'],
        'endAmount': json['endAmount'],
    };
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false);
}

export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemType': value['itemType'],
        'token': value['token'],
        'identifierOrCriteria': value['identifierOrCriteria'],
        'startAmount': value['startAmount'],
        'endAmount': value['endAmount'],
    };
}

