/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingObject
 */
export interface ListingObject {
    /**
     * 
     * @type {string}
     * @memberof ListingObject
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof ListingObject
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof ListingObject
     */
    protocolAddress: string;
}

/**
 * Check if a given object implements the ListingObject interface.
 */
export function instanceOfListingObject(value: object): value is ListingObject {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('protocolAddress' in value) || value['protocolAddress'] === undefined) return false;
    return true;
}

export function ListingObjectFromJSON(json: any): ListingObject {
    return ListingObjectFromJSONTyped(json, false);
}

export function ListingObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingObject {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'chain': json['chain'],
        'protocolAddress': json['protocol_address'],
    };
}

export function ListingObjectToJSON(json: any): ListingObject {
    return ListingObjectToJSONTyped(json, false);
}

export function ListingObjectToJSONTyped(value?: ListingObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
        'chain': value['chain'],
        'protocol_address': value['protocolAddress'],
    };
}

