/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingPrice } from './ListingPrice';
import {
    ListingPriceFromJSON,
    ListingPriceFromJSONTyped,
    ListingPriceToJSON,
    ListingPriceToJSONTyped,
} from './ListingPrice';

/**
 * An item to list for sale
 * @export
 * @interface ListingItem
 */
export interface ListingItem {
    /**
     * Chain of the item (e.g. 'ethereum', 'base')
     * @type {string}
     * @memberof ListingItem
     */
    chain: string;
    /**
     * Contract address of the NFT
     * @type {string}
     * @memberof ListingItem
     */
    contract: string;
    /**
     * Token ID of the NFT
     * @type {string}
     * @memberof ListingItem
     */
    tokenId: string;
    /**
     * Quantity to list (use 1 for ERC-721)
     * @type {number}
     * @memberof ListingItem
     */
    quantity: number;
    /**
     * Price per item
     * @type {ListingPrice}
     * @memberof ListingItem
     */
    price: ListingPrice;
    /**
     * Listing start time in ISO 8601 format. Defaults to now.
     * @type {string}
     * @memberof ListingItem
     */
    startTime?: string;
    /**
     * Listing end time in ISO 8601 format. Defaults to 30 days from start.
     * @type {string}
     * @memberof ListingItem
     */
    endTime?: string;
}

/**
 * Check if a given object implements the ListingItem interface.
 */
export function instanceOfListingItem(value: object): value is ListingItem {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ListingItemFromJSON(json: any): ListingItem {
    return ListingItemFromJSONTyped(json, false);
}

export function ListingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingItem {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contract': json['contract'],
        'tokenId': json['token_id'],
        'quantity': json['quantity'],
        'price': ListingPriceFromJSON(json['price']),
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
    };
}

export function ListingItemToJSON(json: any): ListingItem {
    return ListingItemToJSONTyped(json, false);
}

export function ListingItemToJSONTyped(value?: ListingItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract': value['contract'],
        'token_id': value['tokenId'],
        'quantity': value['quantity'],
        'price': ListingPriceToJSON(value['price']),
        'start_time': value['startTime'],
        'end_time': value['endTime'],
    };
}

