/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedOrder } from './AdvancedOrder';
import {
    AdvancedOrderFromJSON,
    AdvancedOrderFromJSONTyped,
    AdvancedOrderToJSON,
    AdvancedOrderToJSONTyped,
} from './AdvancedOrder';
import type { Fulfillment } from './Fulfillment';
import {
    FulfillmentFromJSON,
    FulfillmentFromJSONTyped,
    FulfillmentToJSON,
    FulfillmentToJSONTyped,
} from './Fulfillment';
import type { CriteriaResolver } from './CriteriaResolver';
import {
    CriteriaResolverFromJSON,
    CriteriaResolverFromJSONTyped,
    CriteriaResolverToJSON,
    CriteriaResolverToJSONTyped,
} from './CriteriaResolver';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface MatchAdvancedOrders
 */
export interface MatchAdvancedOrders {
    /**
     * 
     * @type {Array<AdvancedOrder>}
     * @memberof MatchAdvancedOrders
     */
    orders: Array<AdvancedOrder>;
    /**
     * 
     * @type {Array<CriteriaResolver>}
     * @memberof MatchAdvancedOrders
     */
    criteriaResolvers: Array<CriteriaResolver>;
    /**
     * 
     * @type {Array<Fulfillment>}
     * @memberof MatchAdvancedOrders
     */
    fulfillments: Array<Fulfillment>;
    /**
     * 
     * @type {Address}
     * @memberof MatchAdvancedOrders
     */
    recipient: Address;
}

/**
 * Check if a given object implements the MatchAdvancedOrders interface.
 */
export function instanceOfMatchAdvancedOrders(value: object): value is MatchAdvancedOrders {
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('criteriaResolvers' in value) || value['criteriaResolvers'] === undefined) return false;
    if (!('fulfillments' in value) || value['fulfillments'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function MatchAdvancedOrdersFromJSON(json: any): MatchAdvancedOrders {
    return MatchAdvancedOrdersFromJSONTyped(json, false);
}

export function MatchAdvancedOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchAdvancedOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': ((json['orders'] as Array<any>).map(AdvancedOrderFromJSON)),
        'criteriaResolvers': ((json['criteriaResolvers'] as Array<any>).map(CriteriaResolverFromJSON)),
        'fulfillments': ((json['fulfillments'] as Array<any>).map(FulfillmentFromJSON)),
        'recipient': AddressFromJSON(json['recipient']),
    };
}

export function MatchAdvancedOrdersToJSON(json: any): MatchAdvancedOrders {
    return MatchAdvancedOrdersToJSONTyped(json, false);
}

export function MatchAdvancedOrdersToJSONTyped(value?: MatchAdvancedOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': ((value['orders'] as Array<any>).map(AdvancedOrderToJSON)),
        'criteriaResolvers': ((value['criteriaResolvers'] as Array<any>).map(CriteriaResolverToJSON)),
        'fulfillments': ((value['fulfillments'] as Array<any>).map(FulfillmentToJSON)),
        'recipient': AddressToJSON(value['recipient']),
    };
}

