/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataIngestionError
 */
export interface MetadataIngestionError {
    /**
     * 
     * @type {string}
     * @memberof MetadataIngestionError
     */
    errorType: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataIngestionError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataIngestionError
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof MetadataIngestionError
     */
    statusCode?: number;
}

/**
 * Check if a given object implements the MetadataIngestionError interface.
 */
export function instanceOfMetadataIngestionError(value: object): value is MetadataIngestionError {
    if (!('errorType' in value) || value['errorType'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MetadataIngestionErrorFromJSON(json: any): MetadataIngestionError {
    return MetadataIngestionErrorFromJSONTyped(json, false);
}

export function MetadataIngestionErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataIngestionError {
    if (json == null) {
        return json;
    }
    return {
        
        'errorType': json['errorType'],
        'message': json['message'],
        'url': json['url'] == null ? undefined : json['url'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function MetadataIngestionErrorToJSON(json: any): MetadataIngestionError {
    return MetadataIngestionErrorToJSONTyped(json, false);
}

export function MetadataIngestionErrorToJSONTyped(value?: MetadataIngestionError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorType': value['errorType'],
        'message': value['message'],
        'url': value['url'],
        'statusCode': value['statusCode'],
    };
}

