/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NftDetailed } from './NftDetailed';
import {
    NftDetailedFromJSON,
    NftDetailedFromJSONTyped,
    NftDetailedToJSON,
    NftDetailedToJSONTyped,
} from './NftDetailed';

/**
 * 
 * @export
 * @interface NftBatchResponse
 */
export interface NftBatchResponse {
    /**
     * 
     * @type {Array<NftDetailed>}
     * @memberof NftBatchResponse
     */
    nfts: Array<NftDetailed>;
}

/**
 * Check if a given object implements the NftBatchResponse interface.
 */
export function instanceOfNftBatchResponse(value: object): value is NftBatchResponse {
    if (!('nfts' in value) || value['nfts'] === undefined) return false;
    return true;
}

export function NftBatchResponseFromJSON(json: any): NftBatchResponse {
    return NftBatchResponseFromJSONTyped(json, false);
}

export function NftBatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftBatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nfts': ((json['nfts'] as Array<any>).map(NftDetailedFromJSON)),
    };
}

export function NftBatchResponseToJSON(json: any): NftBatchResponse {
    return NftBatchResponseToJSONTyped(json, false);
}

export function NftBatchResponseToJSONTyped(value?: NftBatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nfts': ((value['nfts'] as Array<any>).map(NftDetailedToJSON)),
    };
}

