/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Owner } from './Owner';
import {
    OwnerFromJSON,
    OwnerFromJSONTyped,
    OwnerToJSON,
    OwnerToJSONTyped,
} from './Owner';
import type { Rarity } from './Rarity';
import {
    RarityFromJSON,
    RarityFromJSONTyped,
    RarityToJSON,
    RarityToJSONTyped,
} from './Rarity';
import type { Trait } from './Trait';
import {
    TraitFromJSON,
    TraitFromJSONTyped,
    TraitToJSON,
    TraitToJSONTyped,
} from './Trait';

/**
 * 
 * @export
 * @interface NftDetailed
 */
export interface NftDetailed {
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    contract: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    tokenStandard: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    displayImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    displayAnimationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    metadataUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    openseaUrl: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    updatedAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof NftDetailed
     */
    isDisabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NftDetailed
     */
    isNsfw: boolean;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    originalImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    originalAnimationUrl?: string;
    /**
     * 
     * @type {Array<Trait>}
     * @memberof NftDetailed
     */
    traits: Array<Trait>;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    animationUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NftDetailed
     */
    isSuspicious: boolean;
    /**
     * 
     * @type {string}
     * @memberof NftDetailed
     */
    creator: string;
    /**
     * 
     * @type {Array<Owner>}
     * @memberof NftDetailed
     */
    owners: Array<Owner>;
    /**
     * 
     * @type {Rarity}
     * @memberof NftDetailed
     */
    rarity?: Rarity;
}

/**
 * Check if a given object implements the NftDetailed interface.
 */
export function instanceOfNftDetailed(value: object): value is NftDetailed {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('tokenStandard' in value) || value['tokenStandard'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('isDisabled' in value) || value['isDisabled'] === undefined) return false;
    if (!('isNsfw' in value) || value['isNsfw'] === undefined) return false;
    if (!('traits' in value) || value['traits'] === undefined) return false;
    if (!('isSuspicious' in value) || value['isSuspicious'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('owners' in value) || value['owners'] === undefined) return false;
    return true;
}

export function NftDetailedFromJSON(json: any): NftDetailed {
    return NftDetailedFromJSONTyped(json, false);
}

export function NftDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftDetailed {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'collection': json['collection'],
        'contract': json['contract'],
        'tokenStandard': json['token_standard'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'displayImageUrl': json['display_image_url'] == null ? undefined : json['display_image_url'],
        'displayAnimationUrl': json['display_animation_url'] == null ? undefined : json['display_animation_url'],
        'metadataUrl': json['metadata_url'] == null ? undefined : json['metadata_url'],
        'openseaUrl': json['opensea_url'],
        'updatedAt': json['updated_at'],
        'isDisabled': json['is_disabled'],
        'isNsfw': json['is_nsfw'],
        'originalImageUrl': json['original_image_url'] == null ? undefined : json['original_image_url'],
        'originalAnimationUrl': json['original_animation_url'] == null ? undefined : json['original_animation_url'],
        'traits': ((json['traits'] as Array<any>).map(TraitFromJSON)),
        'animationUrl': json['animation_url'] == null ? undefined : json['animation_url'],
        'isSuspicious': json['is_suspicious'],
        'creator': json['creator'],
        'owners': ((json['owners'] as Array<any>).map(OwnerFromJSON)),
        'rarity': json['rarity'] == null ? undefined : RarityFromJSON(json['rarity']),
    };
}

export function NftDetailedToJSON(json: any): NftDetailed {
    return NftDetailedToJSONTyped(json, false);
}

export function NftDetailedToJSONTyped(value?: NftDetailed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'collection': value['collection'],
        'contract': value['contract'],
        'token_standard': value['tokenStandard'],
        'name': value['name'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'display_image_url': value['displayImageUrl'],
        'display_animation_url': value['displayAnimationUrl'],
        'metadata_url': value['metadataUrl'],
        'opensea_url': value['openseaUrl'],
        'updated_at': value['updatedAt'],
        'is_disabled': value['isDisabled'],
        'is_nsfw': value['isNsfw'],
        'original_image_url': value['originalImageUrl'],
        'original_animation_url': value['originalAnimationUrl'],
        'traits': ((value['traits'] as Array<any>).map(TraitToJSON)),
        'animation_url': value['animationUrl'],
        'is_suspicious': value['isSuspicious'],
        'creator': value['creator'],
        'owners': ((value['owners'] as Array<any>).map(OwnerToJSON)),
        'rarity': RarityToJSON(value['rarity']),
    };
}

