/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An NFT identifier consisting of chain, contract address, and token ID
 * @export
 * @interface NftIdentifierInput
 */
export interface NftIdentifierInput {
    /**
     * The blockchain the NFT is on
     * @type {string}
     * @memberof NftIdentifierInput
     */
    chain: string;
    /**
     * The contract address of the NFT
     * @type {string}
     * @memberof NftIdentifierInput
     */
    contractAddress: string;
    /**
     * The token ID of the NFT
     * @type {string}
     * @memberof NftIdentifierInput
     */
    tokenId: string;
}

/**
 * Check if a given object implements the NftIdentifierInput interface.
 */
export function instanceOfNftIdentifierInput(value: object): value is NftIdentifierInput {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contractAddress' in value) || value['contractAddress'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    return true;
}

export function NftIdentifierInputFromJSON(json: any): NftIdentifierInput {
    return NftIdentifierInputFromJSONTyped(json, false);
}

export function NftIdentifierInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftIdentifierInput {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contractAddress': json['contract_address'],
        'tokenId': json['token_id'],
    };
}

export function NftIdentifierInputToJSON(json: any): NftIdentifierInput {
    return NftIdentifierInputToJSONTyped(json, false);
}

export function NftIdentifierInputToJSONTyped(value?: NftIdentifierInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract_address': value['contractAddress'],
        'token_id': value['tokenId'],
    };
}

