/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Nft } from './Nft';
import {
    NftFromJSON,
    NftFromJSONTyped,
    NftToJSON,
    NftToJSONTyped,
} from './Nft';

/**
 * 
 * @export
 * @interface NftListResponse
 */
export interface NftListResponse {
    /**
     * 
     * @type {Array<Nft>}
     * @memberof NftListResponse
     */
    nfts: Array<Nft>;
    /**
     * 
     * @type {string}
     * @memberof NftListResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the NftListResponse interface.
 */
export function instanceOfNftListResponse(value: object): value is NftListResponse {
    if (!('nfts' in value) || value['nfts'] === undefined) return false;
    return true;
}

export function NftListResponseFromJSON(json: any): NftListResponse {
    return NftListResponseFromJSONTyped(json, false);
}

export function NftListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nfts': ((json['nfts'] as Array<any>).map(NftFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function NftListResponseToJSON(json: any): NftListResponse {
    return NftListResponseToJSONTyped(json, false);
}

export function NftListResponseToJSONTyped(value?: NftListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nfts': ((value['nfts'] as Array<any>).map(NftToJSON)),
        'next': value['next'],
    };
}

