/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NftDetailed } from './NftDetailed';
import {
    NftDetailedFromJSON,
    NftDetailedFromJSONTyped,
    NftDetailedToJSON,
    NftDetailedToJSONTyped,
} from './NftDetailed';

/**
 * 
 * @export
 * @interface NftResponse
 */
export interface NftResponse {
    /**
     * 
     * @type {NftDetailed}
     * @memberof NftResponse
     */
    nft: NftDetailed;
}

/**
 * Check if a given object implements the NftResponse interface.
 */
export function instanceOfNftResponse(value: object): value is NftResponse {
    if (!('nft' in value) || value['nft'] === undefined) return false;
    return true;
}

export function NftResponseFromJSON(json: any): NftResponse {
    return NftResponseFromJSONTyped(json, false);
}

export function NftResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nft': NftDetailedFromJSON(json['nft']),
    };
}

export function NftResponseToJSON(json: any): NftResponse {
    return NftResponseToJSONTyped(json, false);
}

export function NftResponseToJSONTyped(value?: NftResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nft': NftDetailedToJSON(value['nft']),
    };
}

