/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A sale data point for an NFT
 * @export
 * @interface NftSalePointResponse
 */
export interface NftSalePointResponse {
    /**
     * Timestamp of the sale
     * @type {Date}
     * @memberof NftSalePointResponse
     */
    time: Date;
    /**
     * Sale price in USD
     * @type {string}
     * @memberof NftSalePointResponse
     */
    usdPrice: string;
    /**
     * Sale price in token units
     * @type {number}
     * @memberof NftSalePointResponse
     */
    tokenUnit: number;
    /**
     * Payment token symbol
     * @type {string}
     * @memberof NftSalePointResponse
     */
    symbol?: string;
    /**
     * Blockchain chain
     * @type {string}
     * @memberof NftSalePointResponse
     */
    chain: string;
}

/**
 * Check if a given object implements the NftSalePointResponse interface.
 */
export function instanceOfNftSalePointResponse(value: object): value is NftSalePointResponse {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    if (!('tokenUnit' in value) || value['tokenUnit'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    return true;
}

export function NftSalePointResponseFromJSON(json: any): NftSalePointResponse {
    return NftSalePointResponseFromJSONTyped(json, false);
}

export function NftSalePointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftSalePointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'time': (new Date(json['time'])),
        'usdPrice': json['usd_price'],
        'tokenUnit': json['token_unit'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'chain': json['chain'],
    };
}

export function NftSalePointResponseToJSON(json: any): NftSalePointResponse {
    return NftSalePointResponseToJSONTyped(json, false);
}

export function NftSalePointResponseToJSONTyped(value?: NftSalePointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'].toISOString(),
        'usd_price': value['usdPrice'],
        'token_unit': value['tokenUnit'],
        'symbol': value['symbol'],
        'chain': value['chain'],
    };
}

