/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * NFT search result
 * @export
 * @interface NftSearchResponse
 */
export interface NftSearchResponse {
    /**
     * Token ID of the NFT
     * @type {string}
     * @memberof NftSearchResponse
     */
    identifier: string;
    /**
     * Collection slug the NFT belongs to
     * @type {string}
     * @memberof NftSearchResponse
     */
    collection: string;
    /**
     * Contract address of the NFT
     * @type {string}
     * @memberof NftSearchResponse
     */
    contract: string;
    /**
     * Name of the NFT
     * @type {string}
     * @memberof NftSearchResponse
     */
    name?: string;
    /**
     * URL of the NFT image
     * @type {string}
     * @memberof NftSearchResponse
     */
    imageUrl?: string;
    /**
     * URL to the NFT on OpenSea
     * @type {string}
     * @memberof NftSearchResponse
     */
    openseaUrl: string;
}

/**
 * Check if a given object implements the NftSearchResponse interface.
 */
export function instanceOfNftSearchResponse(value: object): value is NftSearchResponse {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    return true;
}

export function NftSearchResponseFromJSON(json: any): NftSearchResponse {
    return NftSearchResponseFromJSONTyped(json, false);
}

export function NftSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'collection': json['collection'],
        'contract': json['contract'],
        'name': json['name'] == null ? undefined : json['name'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'openseaUrl': json['opensea_url'],
    };
}

export function NftSearchResponseToJSON(json: any): NftSearchResponse {
    return NftSearchResponseToJSONTyped(json, false);
}

export function NftSearchResponseToJSONTyped(value?: NftSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'collection': value['collection'],
        'contract': value['contract'],
        'name': value['name'],
        'image_url': value['imageUrl'],
        'opensea_url': value['openseaUrl'],
    };
}

