/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumericTraitCriteria
 */
export interface NumericTraitCriteria {
    /**
     * 
     * @type {string}
     * @memberof NumericTraitCriteria
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof NumericTraitCriteria
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof NumericTraitCriteria
     */
    max?: number;
}

/**
 * Check if a given object implements the NumericTraitCriteria interface.
 */
export function instanceOfNumericTraitCriteria(value: object): value is NumericTraitCriteria {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NumericTraitCriteriaFromJSON(json: any): NumericTraitCriteria {
    return NumericTraitCriteriaFromJSONTyped(json, false);
}

export function NumericTraitCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumericTraitCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function NumericTraitCriteriaToJSON(json: any): NumericTraitCriteria {
    return NumericTraitCriteriaToJSONTyped(json, false);
}

export function NumericTraitCriteriaToJSONTyped(value?: NumericTraitCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'min': value['min'],
        'max': value['max'],
    };
}

