/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { Criteria } from './Criteria';
import {
    CriteriaFromJSON,
    CriteriaFromJSONTyped,
    CriteriaToJSON,
    CriteriaToJSONTyped,
} from './Criteria';
import type { ProtocolData } from './ProtocolData';
import {
    ProtocolDataFromJSON,
    ProtocolDataFromJSONTyped,
    ProtocolDataToJSON,
    ProtocolDataToJSONTyped,
} from './ProtocolData';

/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    orderHash: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    chain: string;
    /**
     * 
     * @type {ProtocolData}
     * @memberof Offer
     */
    protocolData?: ProtocolData;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    protocolAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    remainingQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    orderCreatedAt?: number;
    /**
     * 
     * @type {Criteria}
     * @memberof Offer
     */
    criteria?: Criteria;
    /**
     * 
     * @type {Price}
     * @memberof Offer
     */
    price: Price;
    /**
     * 
     * @type {OfferStatusEnum}
     * @memberof Offer
     */
    status: OfferStatusEnum;
}


/**
 * @export
 */
export const OfferStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Fulfilled: 'FULFILLED',
    Expired: 'EXPIRED',
    Cancelled: 'CANCELLED'
} as const;
export type OfferStatusEnum = typeof OfferStatusEnum[keyof typeof OfferStatusEnum];


/**
 * Check if a given object implements the Offer interface.
 */
export function instanceOfOffer(value: object): value is Offer {
    if (!('orderHash' in value) || value['orderHash'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('remainingQuantity' in value) || value['remainingQuantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OfferFromJSON(json: any): Offer {
    return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Offer {
    if (json == null) {
        return json;
    }
    return {
        
        'orderHash': json['order_hash'],
        'chain': json['chain'],
        'protocolData': json['protocol_data'] == null ? undefined : ProtocolDataFromJSON(json['protocol_data']),
        'protocolAddress': json['protocol_address'] == null ? undefined : json['protocol_address'],
        'remainingQuantity': json['remaining_quantity'],
        'orderCreatedAt': json['order_created_at'] == null ? undefined : json['order_created_at'],
        'criteria': json['criteria'] == null ? undefined : CriteriaFromJSON(json['criteria']),
        'price': PriceFromJSON(json['price']),
        'status': json['status'],
    };
}

export function OfferToJSON(json: any): Offer {
    return OfferToJSONTyped(json, false);
}

export function OfferToJSONTyped(value?: Offer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_hash': value['orderHash'],
        'chain': value['chain'],
        'protocol_data': ProtocolDataToJSON(value['protocolData']),
        'protocol_address': value['protocolAddress'],
        'remaining_quantity': value['remainingQuantity'],
        'order_created_at': value['orderCreatedAt'],
        'criteria': CriteriaToJSON(value['criteria']),
        'price': PriceToJSON(value['price']),
        'status': value['status'],
    };
}

