/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Price information for an offer aggregate
 * @export
 * @interface OfferAggregatePriceResponse
 */
export interface OfferAggregatePriceResponse {
    /**
     * Price in USD
     * @type {string}
     * @memberof OfferAggregatePriceResponse
     */
    usdPrice: string;
    /**
     * Price in token units
     * @type {number}
     * @memberof OfferAggregatePriceResponse
     */
    tokenUnit: number;
    /**
     * Payment token symbol
     * @type {string}
     * @memberof OfferAggregatePriceResponse
     */
    symbol?: string;
    /**
     * Blockchain chain
     * @type {string}
     * @memberof OfferAggregatePriceResponse
     */
    chain: string;
}

/**
 * Check if a given object implements the OfferAggregatePriceResponse interface.
 */
export function instanceOfOfferAggregatePriceResponse(value: object): value is OfferAggregatePriceResponse {
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    if (!('tokenUnit' in value) || value['tokenUnit'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    return true;
}

export function OfferAggregatePriceResponseFromJSON(json: any): OfferAggregatePriceResponse {
    return OfferAggregatePriceResponseFromJSONTyped(json, false);
}

export function OfferAggregatePriceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferAggregatePriceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'usdPrice': json['usd_price'],
        'tokenUnit': json['token_unit'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'chain': json['chain'],
    };
}

export function OfferAggregatePriceResponseToJSON(json: any): OfferAggregatePriceResponse {
    return OfferAggregatePriceResponseToJSONTyped(json, false);
}

export function OfferAggregatePriceResponseToJSONTyped(value?: OfferAggregatePriceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usd_price': value['usdPrice'],
        'token_unit': value['tokenUnit'],
        'symbol': value['symbol'],
        'chain': value['chain'],
    };
}

