/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OhlcvCandleResponse } from './OhlcvCandleResponse';
import {
    OhlcvCandleResponseFromJSON,
    OhlcvCandleResponseFromJSONTyped,
    OhlcvCandleResponseToJSON,
    OhlcvCandleResponseToJSONTyped,
} from './OhlcvCandleResponse';

/**
 * List of OHLCV candle data points
 * @export
 * @interface OhlcvResponse
 */
export interface OhlcvResponse {
    /**
     * List of OHLCV candles
     * @type {Array<OhlcvCandleResponse>}
     * @memberof OhlcvResponse
     */
    candles: Array<OhlcvCandleResponse>;
}

/**
 * Check if a given object implements the OhlcvResponse interface.
 */
export function instanceOfOhlcvResponse(value: object): value is OhlcvResponse {
    if (!('candles' in value) || value['candles'] === undefined) return false;
    return true;
}

export function OhlcvResponseFromJSON(json: any): OhlcvResponse {
    return OhlcvResponseFromJSONTyped(json, false);
}

export function OhlcvResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OhlcvResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'candles': ((json['candles'] as Array<any>).map(OhlcvCandleResponseFromJSON)),
    };
}

export function OhlcvResponseToJSON(json: any): OhlcvResponse {
    return OhlcvResponseToJSONTyped(json, false);
}

export function OhlcvResponseToJSONTyped(value?: OhlcvResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candles': ((value['candles'] as Array<any>).map(OhlcvCandleResponseToJSON)),
    };
}

