/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An OHLCV candle data point
 * @export
 * @interface OhlcvCandleResponse
 */
export interface OhlcvCandleResponse {
    /**
     * Candle timestamp
     * @type {Date}
     * @memberof OhlcvCandleResponse
     */
    time: Date;
    /**
     * Opening price in USD
     * @type {number}
     * @memberof OhlcvCandleResponse
     */
    open: number;
    /**
     * Highest price in USD
     * @type {number}
     * @memberof OhlcvCandleResponse
     */
    high: number;
    /**
     * Lowest price in USD
     * @type {number}
     * @memberof OhlcvCandleResponse
     */
    low: number;
    /**
     * Closing price in USD
     * @type {number}
     * @memberof OhlcvCandleResponse
     */
    close: number;
    /**
     * Trading volume in USD
     * @type {number}
     * @memberof OhlcvCandleResponse
     */
    volume: number;
}

/**
 * Check if a given object implements the OhlcvCandleResponse interface.
 */
export function instanceOfOhlcvCandleResponse(value: object): value is OhlcvCandleResponse {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('close' in value) || value['close'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function OhlcvCandleResponseFromJSON(json: any): OhlcvCandleResponse {
    return OhlcvCandleResponseFromJSONTyped(json, false);
}

export function OhlcvCandleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OhlcvCandleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'time': (new Date(json['time'])),
        'open': json['open'],
        'high': json['high'],
        'low': json['low'],
        'close': json['close'],
        'volume': json['volume'],
    };
}

export function OhlcvCandleResponseToJSON(json: any): OhlcvCandleResponse {
    return OhlcvCandleResponseToJSONTyped(json, false);
}

export function OhlcvCandleResponseToJSONTyped(value?: OhlcvCandleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'].toISOString(),
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
        'volume': value['volume'],
    };
}

