/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelParameters } from './ModelParameters';
import {
    ModelParametersFromJSON,
    ModelParametersFromJSONTyped,
    ModelParametersToJSON,
    ModelParametersToJSONTyped,
} from './ModelParameters';

/**
 * 
 * @export
 * @interface OrderData
 */
export interface OrderData {
    /**
     * 
     * @type {ModelParameters}
     * @memberof OrderData
     */
    parameters: ModelParameters;
    /**
     * 
     * @type {string}
     * @memberof OrderData
     */
    signature: string;
}

/**
 * Check if a given object implements the OrderData interface.
 */
export function instanceOfOrderData(value: object): value is OrderData {
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function OrderDataFromJSON(json: any): OrderData {
    return OrderDataFromJSONTyped(json, false);
}

export function OrderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderData {
    if (json == null) {
        return json;
    }
    return {
        
        'parameters': ModelParametersFromJSON(json['parameters']),
        'signature': json['signature'],
    };
}

export function OrderDataToJSON(json: any): OrderData {
    return OrderDataToJSONTyped(json, false);
}

export function OrderDataToJSONTyped(value?: OrderData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parameters': ModelParametersToJSON(value['parameters']),
        'signature': value['signature'],
    };
}

