/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';
import type { Criteria } from './Criteria';
import {
    CriteriaFromJSON,
    CriteriaFromJSONTyped,
    CriteriaToJSON,
    CriteriaToJSONTyped,
} from './Criteria';
import type { Nft } from './Nft';
import {
    NftFromJSON,
    NftFromJSONTyped,
    NftToJSON,
    NftToJSONTyped,
} from './Nft';

/**
 * 
 * @export
 * @interface OrderEvent
 */
export interface OrderEvent {
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    eventType: string;
    /**
     * 
     * @type {number}
     * @memberof OrderEvent
     */
    eventTimestamp: number;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    transaction?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    orderHash?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    protocolAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    chain: string;
    /**
     * 
     * @type {Payment}
     * @memberof OrderEvent
     */
    payment?: Payment;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    orderType: string;
    /**
     * 
     * @type {number}
     * @memberof OrderEvent
     */
    startDate?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderEvent
     */
    expirationDate?: number;
    /**
     * 
     * @type {Nft}
     * @memberof OrderEvent
     */
    asset?: Nft;
    /**
     * 
     * @type {number}
     * @memberof OrderEvent
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    maker: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEvent
     */
    taker?: string;
    /**
     * 
     * @type {Criteria}
     * @memberof OrderEvent
     */
    criteria?: Criteria;
    /**
     * 
     * @type {boolean}
     * @memberof OrderEvent
     */
    isPrivateListing: boolean;
}

/**
 * Check if a given object implements the OrderEvent interface.
 */
export function instanceOfOrderEvent(value: object): value is OrderEvent {
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('eventTimestamp' in value) || value['eventTimestamp'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('orderType' in value) || value['orderType'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('maker' in value) || value['maker'] === undefined) return false;
    if (!('isPrivateListing' in value) || value['isPrivateListing'] === undefined) return false;
    return true;
}

export function OrderEventFromJSON(json: any): OrderEvent {
    return OrderEventFromJSONTyped(json, false);
}

export function OrderEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['event_type'],
        'eventTimestamp': json['event_timestamp'],
        'transaction': json['transaction'] == null ? undefined : json['transaction'],
        'orderHash': json['order_hash'] == null ? undefined : json['order_hash'],
        'protocolAddress': json['protocol_address'] == null ? undefined : json['protocol_address'],
        'chain': json['chain'],
        'payment': json['payment'] == null ? undefined : PaymentFromJSON(json['payment']),
        'orderType': json['order_type'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'expirationDate': json['expiration_date'] == null ? undefined : json['expiration_date'],
        'asset': json['asset'] == null ? undefined : NftFromJSON(json['asset']),
        'quantity': json['quantity'],
        'maker': json['maker'],
        'taker': json['taker'] == null ? undefined : json['taker'],
        'criteria': json['criteria'] == null ? undefined : CriteriaFromJSON(json['criteria']),
        'isPrivateListing': json['is_private_listing'],
    };
}

export function OrderEventToJSON(json: any): OrderEvent {
    return OrderEventToJSONTyped(json, false);
}

export function OrderEventToJSONTyped(value?: OrderEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_type': value['eventType'],
        'event_timestamp': value['eventTimestamp'],
        'transaction': value['transaction'],
        'order_hash': value['orderHash'],
        'protocol_address': value['protocolAddress'],
        'chain': value['chain'],
        'payment': PaymentToJSON(value['payment']),
        'order_type': value['orderType'],
        'start_date': value['startDate'],
        'expiration_date': value['expirationDate'],
        'asset': NftToJSON(value['asset']),
        'quantity': value['quantity'],
        'maker': value['maker'],
        'taker': value['taker'],
        'criteria': CriteriaToJSON(value['criteria']),
        'is_private_listing': value['isPrivateListing'],
    };
}

