/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Owner
 */
export interface Owner {
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof Owner
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    quantityString: string;
}

/**
 * Check if a given object implements the Owner interface.
 */
export function instanceOfOwner(value: object): value is Owner {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('quantityString' in value) || value['quantityString'] === undefined) return false;
    return true;
}

export function OwnerFromJSON(json: any): Owner {
    return OwnerFromJSONTyped(json, false);
}

export function OwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Owner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'quantity': json['quantity'],
        'quantityString': json['quantity_string'],
    };
}

export function OwnerToJSON(json: any): Owner {
    return OwnerToJSONTyped(json, false);
}

export function OwnerToJSONTyped(value?: Owner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'quantity': value['quantity'],
        'quantity_string': value['quantityString'],
    };
}

