/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Owner } from './Owner';
import {
    OwnerFromJSON,
    OwnerFromJSONTyped,
    OwnerToJSON,
    OwnerToJSONTyped,
} from './Owner';

/**
 * 
 * @export
 * @interface OwnersPaginatedResponse
 */
export interface OwnersPaginatedResponse {
    /**
     * 
     * @type {Array<Owner>}
     * @memberof OwnersPaginatedResponse
     */
    owners: Array<Owner>;
    /**
     * 
     * @type {string}
     * @memberof OwnersPaginatedResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the OwnersPaginatedResponse interface.
 */
export function instanceOfOwnersPaginatedResponse(value: object): value is OwnersPaginatedResponse {
    if (!('owners' in value) || value['owners'] === undefined) return false;
    return true;
}

export function OwnersPaginatedResponseFromJSON(json: any): OwnersPaginatedResponse {
    return OwnersPaginatedResponseFromJSONTyped(json, false);
}

export function OwnersPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnersPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'owners': ((json['owners'] as Array<any>).map(OwnerFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function OwnersPaginatedResponseToJSON(json: any): OwnersPaginatedResponse {
    return OwnersPaginatedResponseToJSONTyped(json, false);
}

export function OwnersPaginatedResponseToJSONTyped(value?: OwnersPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owners': ((value['owners'] as Array<any>).map(OwnerToJSON)),
        'next': value['next'],
    };
}

