/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Consideration } from './Consideration';
import {
    ConsiderationFromJSON,
    ConsiderationFromJSONTyped,
    ConsiderationToJSON,
    ConsiderationToJSONTyped,
} from './Consideration';

/**
 * 
 * @export
 * @interface PartialParameters
 */
export interface PartialParameters {
    /**
     * 
     * @type {Array<Consideration>}
     * @memberof PartialParameters
     */
    consideration: Array<Consideration>;
    /**
     * 
     * @type {string}
     * @memberof PartialParameters
     */
    zone: string;
    /**
     * 
     * @type {string}
     * @memberof PartialParameters
     */
    zoneHash: string;
}

/**
 * Check if a given object implements the PartialParameters interface.
 */
export function instanceOfPartialParameters(value: object): value is PartialParameters {
    if (!('consideration' in value) || value['consideration'] === undefined) return false;
    if (!('zone' in value) || value['zone'] === undefined) return false;
    if (!('zoneHash' in value) || value['zoneHash'] === undefined) return false;
    return true;
}

export function PartialParametersFromJSON(json: any): PartialParameters {
    return PartialParametersFromJSONTyped(json, false);
}

export function PartialParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'consideration': ((json['consideration'] as Array<any>).map(ConsiderationFromJSON)),
        'zone': json['zone'],
        'zoneHash': json['zoneHash'],
    };
}

export function PartialParametersToJSON(json: any): PartialParameters {
    return PartialParametersToJSONTyped(json, false);
}

export function PartialParametersToJSONTyped(value?: PartialParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consideration': ((value['consideration'] as Array<any>).map(ConsiderationToJSON)),
        'zone': value['zone'],
        'zoneHash': value['zoneHash'],
    };
}

