/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentToken
 */
export interface PaymentToken {
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentToken
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    ethPrice: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentToken
     */
    usdPrice: string;
}

/**
 * Check if a given object implements the PaymentToken interface.
 */
export function instanceOfPaymentToken(value: object): value is PaymentToken {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('ethPrice' in value) || value['ethPrice'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    return true;
}

export function PaymentTokenFromJSON(json: any): PaymentToken {
    return PaymentTokenFromJSONTyped(json, false);
}

export function PaymentTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentToken {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'address': json['address'],
        'chain': json['chain'],
        'image': json['image'],
        'name': json['name'],
        'decimals': json['decimals'],
        'ethPrice': json['eth_price'],
        'usdPrice': json['usd_price'],
    };
}

export function PaymentTokenToJSON(json: any): PaymentToken {
    return PaymentTokenToJSONTyped(json, false);
}

export function PaymentTokenToJSONTyped(value?: PaymentToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'address': value['address'],
        'chain': value['chain'],
        'image': value['image'],
        'name': value['name'],
        'decimals': value['decimals'],
        'eth_price': value['ethPrice'],
        'usd_price': value['usdPrice'],
    };
}

