/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceHistoryPointResponse } from './PriceHistoryPointResponse';
import {
    PriceHistoryPointResponseFromJSON,
    PriceHistoryPointResponseFromJSONTyped,
    PriceHistoryPointResponseToJSON,
    PriceHistoryPointResponseToJSONTyped,
} from './PriceHistoryPointResponse';

/**
 * List of price history data points
 * @export
 * @interface PriceHistoryResponse
 */
export interface PriceHistoryResponse {
    /**
     * List of price history points
     * @type {Array<PriceHistoryPointResponse>}
     * @memberof PriceHistoryResponse
     */
    prices: Array<PriceHistoryPointResponse>;
}

/**
 * Check if a given object implements the PriceHistoryResponse interface.
 */
export function instanceOfPriceHistoryResponse(value: object): value is PriceHistoryResponse {
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function PriceHistoryResponseFromJSON(json: any): PriceHistoryResponse {
    return PriceHistoryResponseFromJSONTyped(json, false);
}

export function PriceHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'prices': ((json['prices'] as Array<any>).map(PriceHistoryPointResponseFromJSON)),
    };
}

export function PriceHistoryResponseToJSON(json: any): PriceHistoryResponse {
    return PriceHistoryResponseToJSONTyped(json, false);
}

export function PriceHistoryResponseToJSONTyped(value?: PriceHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prices': ((value['prices'] as Array<any>).map(PriceHistoryPointResponseToJSON)),
    };
}

