/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentToken } from './PaymentToken';
import {
    PaymentTokenFromJSON,
    PaymentTokenFromJSONTyped,
    PaymentTokenToJSON,
    PaymentTokenToJSONTyped,
} from './PaymentToken';

/**
 * 
 * @export
 * @interface PricingCurrencies
 */
export interface PricingCurrencies {
    /**
     * 
     * @type {PaymentToken}
     * @memberof PricingCurrencies
     */
    listingCurrency: PaymentToken;
    /**
     * 
     * @type {PaymentToken}
     * @memberof PricingCurrencies
     */
    offerCurrency: PaymentToken;
}

/**
 * Check if a given object implements the PricingCurrencies interface.
 */
export function instanceOfPricingCurrencies(value: object): value is PricingCurrencies {
    if (!('listingCurrency' in value) || value['listingCurrency'] === undefined) return false;
    if (!('offerCurrency' in value) || value['offerCurrency'] === undefined) return false;
    return true;
}

export function PricingCurrenciesFromJSON(json: any): PricingCurrencies {
    return PricingCurrenciesFromJSONTyped(json, false);
}

export function PricingCurrenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingCurrencies {
    if (json == null) {
        return json;
    }
    return {
        
        'listingCurrency': PaymentTokenFromJSON(json['listing_currency']),
        'offerCurrency': PaymentTokenFromJSON(json['offer_currency']),
    };
}

export function PricingCurrenciesToJSON(json: any): PricingCurrencies {
    return PricingCurrenciesToJSONTyped(json, false);
}

export function PricingCurrenciesToJSONTyped(value?: PricingCurrencies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing_currency': PaymentTokenToJSON(value['listingCurrency']),
        'offer_currency': PaymentTokenToJSON(value['offerCurrency']),
    };
}

