/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A price history data point
 * @export
 * @interface PriceHistoryPointResponse
 */
export interface PriceHistoryPointResponse {
    /**
     * Timestamp of the price point
     * @type {Date}
     * @memberof PriceHistoryPointResponse
     */
    time: Date;
    /**
     * Price in USD
     * @type {string}
     * @memberof PriceHistoryPointResponse
     */
    usdPrice: string;
}

/**
 * Check if a given object implements the PriceHistoryPointResponse interface.
 */
export function instanceOfPriceHistoryPointResponse(value: object): value is PriceHistoryPointResponse {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    return true;
}

export function PriceHistoryPointResponseFromJSON(json: any): PriceHistoryPointResponse {
    return PriceHistoryPointResponseFromJSONTyped(json, false);
}

export function PriceHistoryPointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceHistoryPointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'time': (new Date(json['time'])),
        'usdPrice': json['usd_price'],
    };
}

export function PriceHistoryPointResponseToJSON(json: any): PriceHistoryPointResponse {
    return PriceHistoryPointResponseToJSONTyped(json, false);
}

export function PriceHistoryPointResponseToJSONTyped(value?: PriceHistoryPointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'].toISOString(),
        'usd_price': value['usdPrice'],
    };
}

