/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Price information for an asset
 * @export
 * @interface PriceResponse
 */
export interface PriceResponse {
    /**
     * Amount in the token's native units
     * @type {string}
     * @memberof PriceResponse
     */
    amount: string;
    /**
     * Token symbol
     * @type {string}
     * @memberof PriceResponse
     */
    currency?: string;
    /**
     * USD equivalent
     * @type {string}
     * @memberof PriceResponse
     */
    usd: string;
}

/**
 * Check if a given object implements the PriceResponse interface.
 */
export function instanceOfPriceResponse(value: object): value is PriceResponse {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('usd' in value) || value['usd'] === undefined) return false;
    return true;
}

export function PriceResponseFromJSON(json: any): PriceResponse {
    return PriceResponseFromJSONTyped(json, false);
}

export function PriceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'usd': json['usd'],
    };
}

export function PriceResponseToJSON(json: any): PriceResponse {
    return PriceResponseToJSONTyped(json, false);
}

export function PriceResponseToJSONTyped(value?: PriceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'usd': value['usd'],
    };
}

