/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileCollectionResponse } from './ProfileCollectionResponse';
import {
    ProfileCollectionResponseFromJSON,
    ProfileCollectionResponseFromJSONTyped,
    ProfileCollectionResponseToJSON,
    ProfileCollectionResponseToJSONTyped,
} from './ProfileCollectionResponse';

/**
 * 
 * @export
 * @interface ProfileCollectionsResponse
 */
export interface ProfileCollectionsResponse {
    /**
     * 
     * @type {Array<ProfileCollectionResponse>}
     * @memberof ProfileCollectionsResponse
     */
    collections: Array<ProfileCollectionResponse>;
    /**
     * 
     * @type {string}
     * @memberof ProfileCollectionsResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the ProfileCollectionsResponse interface.
 */
export function instanceOfProfileCollectionsResponse(value: object): value is ProfileCollectionsResponse {
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function ProfileCollectionsResponseFromJSON(json: any): ProfileCollectionsResponse {
    return ProfileCollectionsResponseFromJSONTyped(json, false);
}

export function ProfileCollectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileCollectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collections': ((json['collections'] as Array<any>).map(ProfileCollectionResponseFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ProfileCollectionsResponseToJSON(json: any): ProfileCollectionsResponse {
    return ProfileCollectionsResponseToJSONTyped(json, false);
}

export function ProfileCollectionsResponseToJSONTyped(value?: ProfileCollectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collections': ((value['collections'] as Array<any>).map(ProfileCollectionResponseToJSON)),
        'next': value['next'],
    };
}

