/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rate limits for the API key
 * @export
 * @interface RateLimitsResponse
 */
export interface RateLimitsResponse {
    /**
     * Read rate limit
     * @type {string}
     * @memberof RateLimitsResponse
     */
    read: string;
    /**
     * Write rate limit
     * @type {string}
     * @memberof RateLimitsResponse
     */
    write: string;
    /**
     * Fulfillment rate limit
     * @type {string}
     * @memberof RateLimitsResponse
     */
    fulfillment: string;
}

/**
 * Check if a given object implements the RateLimitsResponse interface.
 */
export function instanceOfRateLimitsResponse(value: object): value is RateLimitsResponse {
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('write' in value) || value['write'] === undefined) return false;
    if (!('fulfillment' in value) || value['fulfillment'] === undefined) return false;
    return true;
}

export function RateLimitsResponseFromJSON(json: any): RateLimitsResponse {
    return RateLimitsResponseFromJSONTyped(json, false);
}

export function RateLimitsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateLimitsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'read': json['read'],
        'write': json['write'],
        'fulfillment': json['fulfillment'],
    };
}

export function RateLimitsResponseToJSON(json: any): RateLimitsResponse {
    return RateLimitsResponseToJSONTyped(json, false);
}

export function RateLimitsResponseToJSONTyped(value?: RateLimitsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'read': value['read'],
        'write': value['write'],
        'fulfillment': value['fulfillment'],
    };
}

