/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';
import type { Nft } from './Nft';
import {
    NftFromJSON,
    NftFromJSONTyped,
    NftToJSON,
    NftToJSONTyped,
} from './Nft';

/**
 * 
 * @export
 * @interface SaleEvent
 */
export interface SaleEvent {
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    eventType: string;
    /**
     * 
     * @type {number}
     * @memberof SaleEvent
     */
    eventTimestamp: number;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    transaction?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    orderHash?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    protocolAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    chain: string;
    /**
     * 
     * @type {Payment}
     * @memberof SaleEvent
     */
    payment?: Payment;
    /**
     * 
     * @type {number}
     * @memberof SaleEvent
     */
    closingDate: number;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    seller: string;
    /**
     * 
     * @type {string}
     * @memberof SaleEvent
     */
    buyer: string;
    /**
     * 
     * @type {number}
     * @memberof SaleEvent
     */
    quantity: number;
    /**
     * 
     * @type {Nft}
     * @memberof SaleEvent
     */
    nft?: Nft;
}

/**
 * Check if a given object implements the SaleEvent interface.
 */
export function instanceOfSaleEvent(value: object): value is SaleEvent {
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('eventTimestamp' in value) || value['eventTimestamp'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('closingDate' in value) || value['closingDate'] === undefined) return false;
    if (!('seller' in value) || value['seller'] === undefined) return false;
    if (!('buyer' in value) || value['buyer'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function SaleEventFromJSON(json: any): SaleEvent {
    return SaleEventFromJSONTyped(json, false);
}

export function SaleEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['event_type'],
        'eventTimestamp': json['event_timestamp'],
        'transaction': json['transaction'] == null ? undefined : json['transaction'],
        'orderHash': json['order_hash'] == null ? undefined : json['order_hash'],
        'protocolAddress': json['protocol_address'] == null ? undefined : json['protocol_address'],
        'chain': json['chain'],
        'payment': json['payment'] == null ? undefined : PaymentFromJSON(json['payment']),
        'closingDate': json['closing_date'],
        'seller': json['seller'],
        'buyer': json['buyer'],
        'quantity': json['quantity'],
        'nft': json['nft'] == null ? undefined : NftFromJSON(json['nft']),
    };
}

export function SaleEventToJSON(json: any): SaleEvent {
    return SaleEventToJSONTyped(json, false);
}

export function SaleEventToJSONTyped(value?: SaleEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_type': value['eventType'],
        'event_timestamp': value['eventTimestamp'],
        'transaction': value['transaction'],
        'order_hash': value['orderHash'],
        'protocol_address': value['protocolAddress'],
        'chain': value['chain'],
        'payment': PaymentToJSON(value['payment']),
        'closing_date': value['closingDate'],
        'seller': value['seller'],
        'buyer': value['buyer'],
        'quantity': value['quantity'],
        'nft': NftToJSON(value['nft']),
    };
}

