/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeaportParameters } from './SeaportParameters';
import {
    SeaportParametersFromJSON,
    SeaportParametersFromJSONTyped,
    SeaportParametersToJSON,
    SeaportParametersToJSONTyped,
} from './SeaportParameters';

/**
 * 
 * @export
 * @interface SeaportProtocolDataModel
 */
export interface SeaportProtocolDataModel {
    /**
     * 
     * @type {SeaportParameters}
     * @memberof SeaportProtocolDataModel
     */
    parameters: SeaportParameters;
    /**
     * 
     * @type {string}
     * @memberof SeaportProtocolDataModel
     */
    signature: string;
}

/**
 * Check if a given object implements the SeaportProtocolDataModel interface.
 */
export function instanceOfSeaportProtocolDataModel(value: object): value is SeaportProtocolDataModel {
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function SeaportProtocolDataModelFromJSON(json: any): SeaportProtocolDataModel {
    return SeaportProtocolDataModelFromJSONTyped(json, false);
}

export function SeaportProtocolDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeaportProtocolDataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'parameters': SeaportParametersFromJSON(json['parameters']),
        'signature': json['signature'],
    };
}

export function SeaportProtocolDataModelToJSON(json: any): SeaportProtocolDataModel {
    return SeaportProtocolDataModelToJSONTyped(json, false);
}

export function SeaportProtocolDataModelToJSONTyped(value?: SeaportProtocolDataModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parameters': SeaportParametersToJSON(value['parameters']),
        'signature': value['signature'],
    };
}

