/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenSearchResponse } from './TokenSearchResponse';
import {
    TokenSearchResponseFromJSON,
    TokenSearchResponseFromJSONTyped,
    TokenSearchResponseToJSON,
    TokenSearchResponseToJSONTyped,
} from './TokenSearchResponse';
import type { AccountSearchResponse } from './AccountSearchResponse';
import {
    AccountSearchResponseFromJSON,
    AccountSearchResponseFromJSONTyped,
    AccountSearchResponseToJSON,
    AccountSearchResponseToJSONTyped,
} from './AccountSearchResponse';
import type { NftSearchResponse } from './NftSearchResponse';
import {
    NftSearchResponseFromJSON,
    NftSearchResponseFromJSONTyped,
    NftSearchResponseToJSON,
    NftSearchResponseToJSONTyped,
} from './NftSearchResponse';
import type { CollectionSearchResponse } from './CollectionSearchResponse';
import {
    CollectionSearchResponseFromJSON,
    CollectionSearchResponseFromJSONTyped,
    CollectionSearchResponseToJSON,
    CollectionSearchResponseToJSONTyped,
} from './CollectionSearchResponse';

/**
 * A single search result with a type discriminator and the corresponding typed object
 * @export
 * @interface SearchResultResponse
 */
export interface SearchResultResponse {
    /**
     * The type of search result
     * @type {string}
     * @memberof SearchResultResponse
     */
    type: string;
    /**
     * Collection details, present when type is 'collection'
     * @type {CollectionSearchResponse}
     * @memberof SearchResultResponse
     */
    collection?: CollectionSearchResponse;
    /**
     * Token details, present when type is 'token'
     * @type {TokenSearchResponse}
     * @memberof SearchResultResponse
     */
    token?: TokenSearchResponse;
    /**
     * NFT details, present when type is 'nft'
     * @type {NftSearchResponse}
     * @memberof SearchResultResponse
     */
    nft?: NftSearchResponse;
    /**
     * Account details, present when type is 'account'
     * @type {AccountSearchResponse}
     * @memberof SearchResultResponse
     */
    account?: AccountSearchResponse;
}

/**
 * Check if a given object implements the SearchResultResponse interface.
 */
export function instanceOfSearchResultResponse(value: object): value is SearchResultResponse {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SearchResultResponseFromJSON(json: any): SearchResultResponse {
    return SearchResultResponseFromJSONTyped(json, false);
}

export function SearchResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'collection': json['collection'] == null ? undefined : CollectionSearchResponseFromJSON(json['collection']),
        'token': json['token'] == null ? undefined : TokenSearchResponseFromJSON(json['token']),
        'nft': json['nft'] == null ? undefined : NftSearchResponseFromJSON(json['nft']),
        'account': json['account'] == null ? undefined : AccountSearchResponseFromJSON(json['account']),
    };
}

export function SearchResultResponseToJSON(json: any): SearchResultResponse {
    return SearchResultResponseToJSONTyped(json, false);
}

export function SearchResultResponseToJSONTyped(value?: SearchResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'collection': CollectionSearchResponseToJSON(value['collection']),
        'token': TokenSearchResponseToJSON(value['token']),
        'nft': NftSearchResponseToJSON(value['nft']),
        'account': AccountSearchResponseToJSON(value['account']),
    };
}

