/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultResponse } from './SearchResultResponse';
import {
    SearchResultResponseFromJSON,
    SearchResultResponseFromJSONTyped,
    SearchResultResponseToJSON,
    SearchResultResponseToJSONTyped,
} from './SearchResultResponse';

/**
 * Search results response
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * List of search results ranked by relevance
     * @type {Array<SearchResultResponse>}
     * @memberof SearchResponse
     */
    results: Array<SearchResultResponse>;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(SearchResultResponseFromJSON)),
    };
}

export function SearchResponseToJSON(json: any): SearchResponse {
    return SearchResponseToJSONTyped(json, false);
}

export function SearchResponseToJSONTyped(value?: SearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(SearchResultResponseToJSON)),
    };
}

