/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetQuantityInput } from './AssetQuantityInput';
import {
    AssetQuantityInputFromJSON,
    AssetQuantityInputFromJSONTyped,
    AssetQuantityInputToJSON,
    AssetQuantityInputToJSONTyped,
} from './AssetQuantityInput';

/**
 * The original swap quote assets
 * @export
 * @interface SwapQuoteInput
 */
export interface SwapQuoteInput {
    /**
     * Assets being sent/spent
     * @type {Array<AssetQuantityInput>}
     * @memberof SwapQuoteInput
     */
    fromAssets: Array<AssetQuantityInput>;
    /**
     * Assets being received
     * @type {Array<AssetQuantityInput>}
     * @memberof SwapQuoteInput
     */
    toAssets?: Array<AssetQuantityInput>;
}

/**
 * Check if a given object implements the SwapQuoteInput interface.
 */
export function instanceOfSwapQuoteInput(value: object): value is SwapQuoteInput {
    if (!('fromAssets' in value) || value['fromAssets'] === undefined) return false;
    return true;
}

export function SwapQuoteInputFromJSON(json: any): SwapQuoteInput {
    return SwapQuoteInputFromJSONTyped(json, false);
}

export function SwapQuoteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapQuoteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fromAssets': ((json['from_assets'] as Array<any>).map(AssetQuantityInputFromJSON)),
        'toAssets': json['to_assets'] == null ? undefined : ((json['to_assets'] as Array<any>).map(AssetQuantityInputFromJSON)),
    };
}

export function SwapQuoteInputToJSON(json: any): SwapQuoteInput {
    return SwapQuoteInputToJSONTyped(json, false);
}

export function SwapQuoteInputToJSONTyped(value?: SwapQuoteInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_assets': ((value['fromAssets'] as Array<any>).map(AssetQuantityInputToJSON)),
        'to_assets': value['toAssets'] == null ? undefined : ((value['toAssets'] as Array<any>).map(AssetQuantityInputToJSON)),
    };
}

