/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A transaction to be submitted onchain to execute a swap
 * @export
 * @interface SwapTransactionResponse
 */
export interface SwapTransactionResponse {
    /**
     * The blockchain for this transaction
     * @type {string}
     * @memberof SwapTransactionResponse
     */
    chain: string;
    /**
     * The destination address for the transaction
     * @type {string}
     * @memberof SwapTransactionResponse
     */
    to?: string;
    /**
     * The transaction data. For EVM chains: hex-encoded calldata. For SVM chains: comma-separated instructions in programId:data format.
     * @type {string}
     * @memberof SwapTransactionResponse
     */
    data: string;
    /**
     * The native token value to send with the transaction
     * @type {string}
     * @memberof SwapTransactionResponse
     */
    value?: string;
}

/**
 * Check if a given object implements the SwapTransactionResponse interface.
 */
export function instanceOfSwapTransactionResponse(value: object): value is SwapTransactionResponse {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SwapTransactionResponseFromJSON(json: any): SwapTransactionResponse {
    return SwapTransactionResponseFromJSONTyped(json, false);
}

export function SwapTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapTransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'to': json['to'] == null ? undefined : json['to'],
        'data': json['data'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function SwapTransactionResponseToJSON(json: any): SwapTransactionResponse {
    return SwapTransactionResponseToJSONTyped(json, false);
}

export function SwapTransactionResponseToJSONTyped(value?: SwapTransactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'to': value['to'],
        'data': value['data'],
        'value': value['value'],
    };
}

