/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SwapRouteErrorResponse } from './SwapRouteErrorResponse';
import {
    SwapRouteErrorResponseFromJSON,
    SwapRouteErrorResponseFromJSONTyped,
    SwapRouteErrorResponseToJSON,
    SwapRouteErrorResponseToJSONTyped,
} from './SwapRouteErrorResponse';
import type { SwapPriceImpact } from './SwapPriceImpact';
import {
    SwapPriceImpactFromJSON,
    SwapPriceImpactFromJSONTyped,
    SwapPriceImpactToJSON,
    SwapPriceImpactToJSONTyped,
} from './SwapPriceImpact';
import type { SwapCostResponse } from './SwapCostResponse';
import {
    SwapCostResponseFromJSON,
    SwapCostResponseFromJSONTyped,
    SwapCostResponseToJSON,
    SwapCostResponseToJSONTyped,
} from './SwapCostResponse';

/**
 * Price and fee details for a swap quote
 * @export
 * @interface SwapQuoteDetails
 */
export interface SwapQuoteDetails {
    /**
     * Total value of tokens received in USD
     * @type {number}
     * @memberof SwapQuoteDetails
     */
    totalPriceUsd: number;
    /**
     * Total cost of tokens sent in USD
     * @type {number}
     * @memberof SwapQuoteDetails
     */
    totalCostUsd: number;
    /**
     * Slippage tolerance as a decimal (e.g. 0.01 = 1%)
     * @type {number}
     * @memberof SwapQuoteDetails
     */
    slippageTolerance: number;
    /**
     * Estimated swap duration in milliseconds
     * @type {number}
     * @memberof SwapQuoteDetails
     */
    estimatedDurationMs: number;
    /**
     * Marketplace fee in basis points
     * @type {number}
     * @memberof SwapQuoteDetails
     */
    marketplaceFeeBps: number;
    /**
     * Price impact of the swap (null if unavailable)
     * @type {SwapPriceImpact}
     * @memberof SwapQuoteDetails
     */
    priceImpact?: SwapPriceImpact;
    /**
     * The swap provider that fulfilled this quote (null if unavailable)
     * @type {string}
     * @memberof SwapQuoteDetails
     */
    swapProvider?: string;
    /**
     * Breakdown of costs for the swap
     * @type {Array<SwapCostResponse>}
     * @memberof SwapQuoteDetails
     */
    costs: Array<SwapCostResponse>;
    /**
     * Errors encountered for individual swap routes
     * @type {Array<SwapRouteErrorResponse>}
     * @memberof SwapQuoteDetails
     */
    routeErrors: Array<SwapRouteErrorResponse>;
}

/**
 * Check if a given object implements the SwapQuoteDetails interface.
 */
export function instanceOfSwapQuoteDetails(value: object): value is SwapQuoteDetails {
    if (!('totalPriceUsd' in value) || value['totalPriceUsd'] === undefined) return false;
    if (!('totalCostUsd' in value) || value['totalCostUsd'] === undefined) return false;
    if (!('slippageTolerance' in value) || value['slippageTolerance'] === undefined) return false;
    if (!('estimatedDurationMs' in value) || value['estimatedDurationMs'] === undefined) return false;
    if (!('marketplaceFeeBps' in value) || value['marketplaceFeeBps'] === undefined) return false;
    if (!('costs' in value) || value['costs'] === undefined) return false;
    if (!('routeErrors' in value) || value['routeErrors'] === undefined) return false;
    return true;
}

export function SwapQuoteDetailsFromJSON(json: any): SwapQuoteDetails {
    return SwapQuoteDetailsFromJSONTyped(json, false);
}

export function SwapQuoteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapQuoteDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPriceUsd': json['total_price_usd'],
        'totalCostUsd': json['total_cost_usd'],
        'slippageTolerance': json['slippage_tolerance'],
        'estimatedDurationMs': json['estimated_duration_ms'],
        'marketplaceFeeBps': json['marketplace_fee_bps'],
        'priceImpact': json['price_impact'] == null ? undefined : SwapPriceImpactFromJSON(json['price_impact']),
        'swapProvider': json['swap_provider'] == null ? undefined : json['swap_provider'],
        'costs': ((json['costs'] as Array<any>).map(SwapCostResponseFromJSON)),
        'routeErrors': ((json['route_errors'] as Array<any>).map(SwapRouteErrorResponseFromJSON)),
    };
}

export function SwapQuoteDetailsToJSON(json: any): SwapQuoteDetails {
    return SwapQuoteDetailsToJSONTyped(json, false);
}

export function SwapQuoteDetailsToJSONTyped(value?: SwapQuoteDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_price_usd': value['totalPriceUsd'],
        'total_cost_usd': value['totalCostUsd'],
        'slippage_tolerance': value['slippageTolerance'],
        'estimated_duration_ms': value['estimatedDurationMs'],
        'marketplace_fee_bps': value['marketplaceFeeBps'],
        'price_impact': SwapPriceImpactToJSON(value['priceImpact']),
        'swap_provider': value['swapProvider'],
        'costs': ((value['costs'] as Array<any>).map(SwapCostResponseToJSON)),
        'route_errors': ((value['routeErrors'] as Array<any>).map(SwapRouteErrorResponseToJSON)),
    };
}

