/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SwapTransactionResponse } from './SwapTransactionResponse';
import {
    SwapTransactionResponseFromJSON,
    SwapTransactionResponseFromJSONTyped,
    SwapTransactionResponseToJSON,
    SwapTransactionResponseToJSONTyped,
} from './SwapTransactionResponse';
import type { SwapQuoteDetails } from './SwapQuoteDetails';
import {
    SwapQuoteDetailsFromJSON,
    SwapQuoteDetailsFromJSONTyped,
    SwapQuoteDetailsToJSON,
    SwapQuoteDetailsToJSONTyped,
} from './SwapQuoteDetails';

/**
 * Swap quote with price details and executable transactions
 * @export
 * @interface SwapQuoteResponse
 */
export interface SwapQuoteResponse {
    /**
     * Price and fee details for the swap
     * @type {SwapQuoteDetails}
     * @memberof SwapQuoteResponse
     */
    quote: SwapQuoteDetails;
    /**
     * Transactions to execute the swap
     * @type {Array<SwapTransactionResponse>}
     * @memberof SwapQuoteResponse
     */
    transactions: Array<SwapTransactionResponse>;
}

/**
 * Check if a given object implements the SwapQuoteResponse interface.
 */
export function instanceOfSwapQuoteResponse(value: object): value is SwapQuoteResponse {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function SwapQuoteResponseFromJSON(json: any): SwapQuoteResponse {
    return SwapQuoteResponseFromJSONTyped(json, false);
}

export function SwapQuoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapQuoteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': SwapQuoteDetailsFromJSON(json['quote']),
        'transactions': ((json['transactions'] as Array<any>).map(SwapTransactionResponseFromJSON)),
    };
}

export function SwapQuoteResponseToJSON(json: any): SwapQuoteResponse {
    return SwapQuoteResponseToJSONTyped(json, false);
}

export function SwapQuoteResponseToJSONTyped(value?: SwapQuoteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': SwapQuoteDetailsToJSON(value['quote']),
        'transactions': ((value['transactions'] as Array<any>).map(SwapTransactionResponseToJSON)),
    };
}

