/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SwapTransactionResponse } from './SwapTransactionResponse';
import {
    SwapTransactionResponseFromJSON,
    SwapTransactionResponseFromJSONTyped,
    SwapTransactionResponseToJSON,
    SwapTransactionResponseToJSONTyped,
} from './SwapTransactionResponse';
import type { SwapQuoteDetails } from './SwapQuoteDetails';
import {
    SwapQuoteDetailsFromJSON,
    SwapQuoteDetailsFromJSONTyped,
    SwapQuoteDetailsToJSON,
    SwapQuoteDetailsToJSONTyped,
} from './SwapQuoteDetails';

/**
 * Response containing quote details and executable swap transactions
 * @export
 * @interface SwapExecuteResponse
 */
export interface SwapExecuteResponse {
    /**
     * Price and fee details for the swap
     * @type {SwapQuoteDetails}
     * @memberof SwapExecuteResponse
     */
    quote: SwapQuoteDetails;
    /**
     * Ordered list of transactions to execute the swap
     * @type {Array<SwapTransactionResponse>}
     * @memberof SwapExecuteResponse
     */
    transactions: Array<SwapTransactionResponse>;
}

/**
 * Check if a given object implements the SwapExecuteResponse interface.
 */
export function instanceOfSwapExecuteResponse(value: object): value is SwapExecuteResponse {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function SwapExecuteResponseFromJSON(json: any): SwapExecuteResponse {
    return SwapExecuteResponseFromJSONTyped(json, false);
}

export function SwapExecuteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapExecuteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': SwapQuoteDetailsFromJSON(json['quote']),
        'transactions': ((json['transactions'] as Array<any>).map(SwapTransactionResponseFromJSON)),
    };
}

export function SwapExecuteResponseToJSON(json: any): SwapExecuteResponse {
    return SwapExecuteResponseToJSONTyped(json, false);
}

export function SwapExecuteResponseToJSONTyped(value?: SwapExecuteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': SwapQuoteDetailsToJSON(value['quote']),
        'transactions': ((value['transactions'] as Array<any>).map(SwapTransactionResponseToJSON)),
    };
}

