/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An asset to swap with chain, contract address, and amount
 * @export
 * @interface SwapAssetInput
 */
export interface SwapAssetInput {
    /**
     * Chain slug (e.g. ethereum, base, solana)
     * @type {string}
     * @memberof SwapAssetInput
     */
    chain: string;
    /**
     * Contract address of the token
     * @type {string}
     * @memberof SwapAssetInput
     */
    contract: string;
    /**
     * Amount in the smallest unit of the token (e.g. wei for ETH). Use "0" for to_assets to receive the market rate.
     * @type {string}
     * @memberof SwapAssetInput
     */
    amount: string;
}

/**
 * Check if a given object implements the SwapAssetInput interface.
 */
export function instanceOfSwapAssetInput(value: object): value is SwapAssetInput {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function SwapAssetInputFromJSON(json: any): SwapAssetInput {
    return SwapAssetInputFromJSONTyped(json, false);
}

export function SwapAssetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapAssetInput {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contract': json['contract'],
        'amount': json['amount'],
    };
}

export function SwapAssetInputToJSON(json: any): SwapAssetInput {
    return SwapAssetInputToJSONTyped(json, false);
}

export function SwapAssetInputToJSONTyped(value?: SwapAssetInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract': value['contract'],
        'amount': value['amount'],
    };
}

