/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Price impact of the swap
 * @export
 * @interface SwapPriceImpact
 */
export interface SwapPriceImpact {
    /**
     * Price impact in USD (negative means user loses value)
     * @type {string}
     * @memberof SwapPriceImpact
     */
    usd: string;
    /**
     * Price impact as a percentage (negative means user loses value)
     * @type {string}
     * @memberof SwapPriceImpact
     */
    percent: string;
}

/**
 * Check if a given object implements the SwapPriceImpact interface.
 */
export function instanceOfSwapPriceImpact(value: object): value is SwapPriceImpact {
    if (!('usd' in value) || value['usd'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function SwapPriceImpactFromJSON(json: any): SwapPriceImpact {
    return SwapPriceImpactFromJSONTyped(json, false);
}

export function SwapPriceImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapPriceImpact {
    if (json == null) {
        return json;
    }
    return {
        
        'usd': json['usd'],
        'percent': json['percent'],
    };
}

export function SwapPriceImpactToJSON(json: any): SwapPriceImpact {
    return SwapPriceImpactToJSONTyped(json, false);
}

export function SwapPriceImpactToJSONTyped(value?: SwapPriceImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usd': value['usd'],
        'percent': value['percent'],
    };
}

