/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An error encountered during a sweep operation
 * @export
 * @interface SweepError
 */
export interface SweepError {
    /**
     * Human-readable error message
     * @type {string}
     * @memberof SweepError
     */
    message: string;
}

/**
 * Check if a given object implements the SweepError interface.
 */
export function instanceOfSweepError(value: object): value is SweepError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SweepErrorFromJSON(json: any): SweepError {
    return SweepErrorFromJSONTyped(json, false);
}

export function SweepErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SweepError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SweepErrorToJSON(json: any): SweepError {
    return SweepErrorToJSONTyped(json, false);
}

export function SweepErrorToJSONTyped(value?: SweepError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

