/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A token contract identifier consisting of chain and address
 * @export
 * @interface TokenContractInput
 */
export interface TokenContractInput {
    /**
     * The blockchain the token is on
     * @type {string}
     * @memberof TokenContractInput
     */
    chain: string;
    /**
     * The contract address of the token
     * @type {string}
     * @memberof TokenContractInput
     */
    address: string;
}

/**
 * Check if a given object implements the TokenContractInput interface.
 */
export function instanceOfTokenContractInput(value: object): value is TokenContractInput {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function TokenContractInputFromJSON(json: any): TokenContractInput {
    return TokenContractInputFromJSONTyped(json, false);
}

export function TokenContractInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenContractInput {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'address': json['address'],
    };
}

export function TokenContractInputToJSON(json: any): TokenContractInput {
    return TokenContractInputToJSONTyped(json, false);
}

export function TokenContractInputToJSONTyped(value?: TokenContractInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'address': value['address'],
    };
}

