/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Market statistics for a token
 * @export
 * @interface TokenStatsResponse
 */
export interface TokenStatsResponse {
    /**
     * Market capitalization in USD
     * @type {number}
     * @memberof TokenStatsResponse
     */
    marketCapUsd?: number;
    /**
     * Fully diluted valuation in USD
     * @type {number}
     * @memberof TokenStatsResponse
     */
    fdvUsd?: number;
    /**
     * Circulating supply of the token
     * @type {number}
     * @memberof TokenStatsResponse
     */
    circulatingSupply?: number;
    /**
     * Maximum supply of the token
     * @type {number}
     * @memberof TokenStatsResponse
     */
    maxSupply?: number;
    /**
     * Total supply of the token
     * @type {number}
     * @memberof TokenStatsResponse
     */
    totalSupply?: number;
    /**
     * 24-hour trading volume in USD
     * @type {number}
     * @memberof TokenStatsResponse
     */
    volume24h?: number;
    /**
     * Price change percentage over the last hour
     * @type {number}
     * @memberof TokenStatsResponse
     */
    priceChange1h?: number;
    /**
     * Price change percentage over the last 24 hours
     * @type {number}
     * @memberof TokenStatsResponse
     */
    priceChange24h?: number;
    /**
     * Price change percentage over the last 7 days
     * @type {number}
     * @memberof TokenStatsResponse
     */
    priceChange7d?: number;
    /**
     * Price change percentage over the last 30 days
     * @type {number}
     * @memberof TokenStatsResponse
     */
    priceChange30d?: number;
}

/**
 * Check if a given object implements the TokenStatsResponse interface.
 */
export function instanceOfTokenStatsResponse(value: object): value is TokenStatsResponse {
    return true;
}

export function TokenStatsResponseFromJSON(json: any): TokenStatsResponse {
    return TokenStatsResponseFromJSONTyped(json, false);
}

export function TokenStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'marketCapUsd': json['market_cap_usd'] == null ? undefined : json['market_cap_usd'],
        'fdvUsd': json['fdv_usd'] == null ? undefined : json['fdv_usd'],
        'circulatingSupply': json['circulating_supply'] == null ? undefined : json['circulating_supply'],
        'maxSupply': json['max_supply'] == null ? undefined : json['max_supply'],
        'totalSupply': json['total_supply'] == null ? undefined : json['total_supply'],
        'volume24h': json['volume_24h'] == null ? undefined : json['volume_24h'],
        'priceChange1h': json['price_change_1h'] == null ? undefined : json['price_change_1h'],
        'priceChange24h': json['price_change_24h'] == null ? undefined : json['price_change_24h'],
        'priceChange7d': json['price_change_7d'] == null ? undefined : json['price_change_7d'],
        'priceChange30d': json['price_change_30d'] == null ? undefined : json['price_change_30d'],
    };
}

export function TokenStatsResponseToJSON(json: any): TokenStatsResponse {
    return TokenStatsResponseToJSONTyped(json, false);
}

export function TokenStatsResponseToJSONTyped(value?: TokenStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_cap_usd': value['marketCapUsd'],
        'fdv_usd': value['fdvUsd'],
        'circulating_supply': value['circulatingSupply'],
        'max_supply': value['maxSupply'],
        'total_supply': value['totalSupply'],
        'volume_24h': value['volume24h'],
        'price_change_1h': value['priceChange1h'],
        'price_change_24h': value['priceChange24h'],
        'price_change_7d': value['priceChange7d'],
        'price_change_30d': value['priceChange30d'],
    };
}

