/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A currency within a token group
 * @export
 * @interface TokenGroupCurrencyResponse
 */
export interface TokenGroupCurrencyResponse {
    /**
     * The contract address of the currency
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    address: string;
    /**
     * The blockchain the currency is on
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    chain: string;
    /**
     * The display name of the currency
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    name: string;
    /**
     * The ticker symbol of the currency
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    symbol: string;
    /**
     * URL of the currency's image
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    imageUrl?: string;
    /**
     * Number of decimal places
     * @type {number}
     * @memberof TokenGroupCurrencyResponse
     */
    decimals: number;
    /**
     * Current price in USD
     * @type {string}
     * @memberof TokenGroupCurrencyResponse
     */
    usdPrice: string;
}

/**
 * Check if a given object implements the TokenGroupCurrencyResponse interface.
 */
export function instanceOfTokenGroupCurrencyResponse(value: object): value is TokenGroupCurrencyResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    return true;
}

export function TokenGroupCurrencyResponseFromJSON(json: any): TokenGroupCurrencyResponse {
    return TokenGroupCurrencyResponseFromJSONTyped(json, false);
}

export function TokenGroupCurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenGroupCurrencyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chain': json['chain'],
        'name': json['name'],
        'symbol': json['symbol'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'decimals': json['decimals'],
        'usdPrice': json['usd_price'],
    };
}

export function TokenGroupCurrencyResponseToJSON(json: any): TokenGroupCurrencyResponse {
    return TokenGroupCurrencyResponseToJSONTyped(json, false);
}

export function TokenGroupCurrencyResponseToJSONTyped(value?: TokenGroupCurrencyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'name': value['name'],
        'symbol': value['symbol'],
        'image_url': value['imageUrl'],
        'decimals': value['decimals'],
        'usd_price': value['usdPrice'],
    };
}

