/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token (currency) search result
 * @export
 * @interface TokenSearchResponse
 */
export interface TokenSearchResponse {
    /**
     * The contract address of the token
     * @type {string}
     * @memberof TokenSearchResponse
     */
    address: string;
    /**
     * The blockchain the token is on
     * @type {string}
     * @memberof TokenSearchResponse
     */
    chain: string;
    /**
     * The display name of the token
     * @type {string}
     * @memberof TokenSearchResponse
     */
    name: string;
    /**
     * The ticker symbol of the token
     * @type {string}
     * @memberof TokenSearchResponse
     */
    symbol: string;
    /**
     * URL of the token's image
     * @type {string}
     * @memberof TokenSearchResponse
     */
    imageUrl?: string;
    /**
     * Current price in USD
     * @type {string}
     * @memberof TokenSearchResponse
     */
    usdPrice: string;
    /**
     * Number of decimal places
     * @type {number}
     * @memberof TokenSearchResponse
     */
    decimals: number;
    /**
     * URL to the token page on OpenSea
     * @type {string}
     * @memberof TokenSearchResponse
     */
    openseaUrl: string;
}

/**
 * Check if a given object implements the TokenSearchResponse interface.
 */
export function instanceOfTokenSearchResponse(value: object): value is TokenSearchResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    return true;
}

export function TokenSearchResponseFromJSON(json: any): TokenSearchResponse {
    return TokenSearchResponseFromJSONTyped(json, false);
}

export function TokenSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chain': json['chain'],
        'name': json['name'],
        'symbol': json['symbol'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'usdPrice': json['usd_price'],
        'decimals': json['decimals'],
        'openseaUrl': json['opensea_url'],
    };
}

export function TokenSearchResponseToJSON(json: any): TokenSearchResponse {
    return TokenSearchResponseToJSONTyped(json, false);
}

export function TokenSearchResponseToJSONTyped(value?: TokenSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'name': value['name'],
        'symbol': value['symbol'],
        'image_url': value['imageUrl'],
        'usd_price': value['usdPrice'],
        'decimals': value['decimals'],
        'opensea_url': value['openseaUrl'],
    };
}

