/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenResponse } from './TokenResponse';
import {
    TokenResponseFromJSON,
    TokenResponseFromJSONTyped,
    TokenResponseToJSON,
    TokenResponseToJSONTyped,
} from './TokenResponse';

/**
 * Paginated list of tokens
 * @export
 * @interface TokenPaginatedResponse
 */
export interface TokenPaginatedResponse {
    /**
     * List of tokens
     * @type {Array<TokenResponse>}
     * @memberof TokenPaginatedResponse
     */
    tokens: Array<TokenResponse>;
    /**
     * Cursor for the next page of results
     * @type {string}
     * @memberof TokenPaginatedResponse
     */
    next?: string;
}

/**
 * Check if a given object implements the TokenPaginatedResponse interface.
 */
export function instanceOfTokenPaginatedResponse(value: object): value is TokenPaginatedResponse {
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function TokenPaginatedResponseFromJSON(json: any): TokenPaginatedResponse {
    return TokenPaginatedResponseFromJSONTyped(json, false);
}

export function TokenPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': ((json['tokens'] as Array<any>).map(TokenResponseFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function TokenPaginatedResponseToJSON(json: any): TokenPaginatedResponse {
    return TokenPaginatedResponseToJSONTyped(json, false);
}

export function TokenPaginatedResponseToJSONTyped(value?: TokenPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': ((value['tokens'] as Array<any>).map(TokenResponseToJSON)),
        'next': value['next'],
    };
}

