/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rolling statistics for a token group over multiple time periods
 * @export
 * @interface TokenGroupRollingStatsResponse
 */
export interface TokenGroupRollingStatsResponse {
    /**
     * 1-day trading volume in USD
     * @type {string}
     * @memberof TokenGroupRollingStatsResponse
     */
    volume1d?: string;
    /**
     * 7-day trading volume in USD
     * @type {string}
     * @memberof TokenGroupRollingStatsResponse
     */
    volume7d?: string;
    /**
     * 30-day trading volume in USD
     * @type {string}
     * @memberof TokenGroupRollingStatsResponse
     */
    volume30d?: string;
    /**
     * 1-day price change percentage
     * @type {number}
     * @memberof TokenGroupRollingStatsResponse
     */
    priceChange1d?: number;
    /**
     * 7-day price change percentage
     * @type {number}
     * @memberof TokenGroupRollingStatsResponse
     */
    priceChange7d?: number;
    /**
     * 30-day price change percentage
     * @type {number}
     * @memberof TokenGroupRollingStatsResponse
     */
    priceChange30d?: number;
}

/**
 * Check if a given object implements the TokenGroupRollingStatsResponse interface.
 */
export function instanceOfTokenGroupRollingStatsResponse(value: object): value is TokenGroupRollingStatsResponse {
    return true;
}

export function TokenGroupRollingStatsResponseFromJSON(json: any): TokenGroupRollingStatsResponse {
    return TokenGroupRollingStatsResponseFromJSONTyped(json, false);
}

export function TokenGroupRollingStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenGroupRollingStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'volume1d': json['volume_1d'] == null ? undefined : json['volume_1d'],
        'volume7d': json['volume_7d'] == null ? undefined : json['volume_7d'],
        'volume30d': json['volume_30d'] == null ? undefined : json['volume_30d'],
        'priceChange1d': json['price_change_1d'] == null ? undefined : json['price_change_1d'],
        'priceChange7d': json['price_change_7d'] == null ? undefined : json['price_change_7d'],
        'priceChange30d': json['price_change_30d'] == null ? undefined : json['price_change_30d'],
    };
}

export function TokenGroupRollingStatsResponseToJSON(json: any): TokenGroupRollingStatsResponse {
    return TokenGroupRollingStatsResponseToJSONTyped(json, false);
}

export function TokenGroupRollingStatsResponseToJSONTyped(value?: TokenGroupRollingStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'volume_1d': value['volume1d'],
        'volume_7d': value['volume7d'],
        'volume_30d': value['volume30d'],
        'price_change_1d': value['priceChange1d'],
        'price_change_7d': value['priceChange7d'],
        'price_change_30d': value['priceChange30d'],
    };
}

