/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenGroupStatsResponse } from './TokenGroupStatsResponse';
import {
    TokenGroupStatsResponseFromJSON,
    TokenGroupStatsResponseFromJSONTyped,
    TokenGroupStatsResponseToJSON,
    TokenGroupStatsResponseToJSONTyped,
} from './TokenGroupStatsResponse';
import type { TokenGroupSocialsResponse } from './TokenGroupSocialsResponse';
import {
    TokenGroupSocialsResponseFromJSON,
    TokenGroupSocialsResponseFromJSONTyped,
    TokenGroupSocialsResponseToJSON,
    TokenGroupSocialsResponseToJSONTyped,
} from './TokenGroupSocialsResponse';
import type { TokenGroupCurrencyResponse } from './TokenGroupCurrencyResponse';
import {
    TokenGroupCurrencyResponseFromJSON,
    TokenGroupCurrencyResponseFromJSONTyped,
    TokenGroupCurrencyResponseToJSON,
    TokenGroupCurrencyResponseToJSONTyped,
} from './TokenGroupCurrencyResponse';

/**
 * A token group representing equivalent currencies across different blockchains
 * @export
 * @interface TokenGroupResponse
 */
export interface TokenGroupResponse {
    /**
     * Unique slug identifier for the token group
     * @type {string}
     * @memberof TokenGroupResponse
     */
    slug: string;
    /**
     * Display name of the token group
     * @type {string}
     * @memberof TokenGroupResponse
     */
    displayName: string;
    /**
     * Ticker symbol of the token group
     * @type {string}
     * @memberof TokenGroupResponse
     */
    symbol?: string;
    /**
     * Description of the token group
     * @type {string}
     * @memberof TokenGroupResponse
     */
    description?: string;
    /**
     * URL of the token group's image
     * @type {string}
     * @memberof TokenGroupResponse
     */
    imageUrl?: string;
    /**
     * URL to the token group page on OpenSea
     * @type {string}
     * @memberof TokenGroupResponse
     */
    openseaUrl: string;
    /**
     * Currencies in this token group
     * @type {Array<TokenGroupCurrencyResponse>}
     * @memberof TokenGroupResponse
     */
    currencies: Array<TokenGroupCurrencyResponse>;
    /**
     * The primary currency for this token group
     * @type {TokenGroupCurrencyResponse}
     * @memberof TokenGroupResponse
     */
    primaryCurrency: TokenGroupCurrencyResponse;
    /**
     * Market statistics for the token group
     * @type {TokenGroupStatsResponse}
     * @memberof TokenGroupResponse
     */
    stats?: TokenGroupStatsResponse;
    /**
     * Social media links for the token group
     * @type {TokenGroupSocialsResponse}
     * @memberof TokenGroupResponse
     */
    socials?: TokenGroupSocialsResponse;
    /**
     * ISO 8601 timestamp when the token group was created
     * @type {string}
     * @memberof TokenGroupResponse
     */
    createdAt: string;
    /**
     * ISO 8601 timestamp when the token group was last updated
     * @type {string}
     * @memberof TokenGroupResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the TokenGroupResponse interface.
 */
export function instanceOfTokenGroupResponse(value: object): value is TokenGroupResponse {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    if (!('currencies' in value) || value['currencies'] === undefined) return false;
    if (!('primaryCurrency' in value) || value['primaryCurrency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TokenGroupResponseFromJSON(json: any): TokenGroupResponse {
    return TokenGroupResponseFromJSONTyped(json, false);
}

export function TokenGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'displayName': json['display_name'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'openseaUrl': json['opensea_url'],
        'currencies': ((json['currencies'] as Array<any>).map(TokenGroupCurrencyResponseFromJSON)),
        'primaryCurrency': TokenGroupCurrencyResponseFromJSON(json['primary_currency']),
        'stats': json['stats'] == null ? undefined : TokenGroupStatsResponseFromJSON(json['stats']),
        'socials': json['socials'] == null ? undefined : TokenGroupSocialsResponseFromJSON(json['socials']),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function TokenGroupResponseToJSON(json: any): TokenGroupResponse {
    return TokenGroupResponseToJSONTyped(json, false);
}

export function TokenGroupResponseToJSONTyped(value?: TokenGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'display_name': value['displayName'],
        'symbol': value['symbol'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'opensea_url': value['openseaUrl'],
        'currencies': ((value['currencies'] as Array<any>).map(TokenGroupCurrencyResponseToJSON)),
        'primary_currency': TokenGroupCurrencyResponseToJSON(value['primaryCurrency']),
        'stats': TokenGroupStatsResponseToJSON(value['stats']),
        'socials': TokenGroupSocialsResponseToJSON(value['socials']),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

