/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token amount with contract and value information
 * @export
 * @interface TokenAmountResponse
 */
export interface TokenAmountResponse {
    /**
     * Contract address of the token
     * @type {string}
     * @memberof TokenAmountResponse
     */
    address: string;
    /**
     * Blockchain the token is on
     * @type {string}
     * @memberof TokenAmountResponse
     */
    chain: string;
    /**
     * Amount in token units
     * @type {number}
     * @memberof TokenAmountResponse
     */
    amountToken: number;
    /**
     * Amount in USD
     * @type {string}
     * @memberof TokenAmountResponse
     */
    amountUsd: string;
    /**
     * Amount in chain-native units
     * @type {number}
     * @memberof TokenAmountResponse
     */
    amountNative: number;
}

/**
 * Check if a given object implements the TokenAmountResponse interface.
 */
export function instanceOfTokenAmountResponse(value: object): value is TokenAmountResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('amountToken' in value) || value['amountToken'] === undefined) return false;
    if (!('amountUsd' in value) || value['amountUsd'] === undefined) return false;
    if (!('amountNative' in value) || value['amountNative'] === undefined) return false;
    return true;
}

export function TokenAmountResponseFromJSON(json: any): TokenAmountResponse {
    return TokenAmountResponseFromJSONTyped(json, false);
}

export function TokenAmountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAmountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chain': json['chain'],
        'amountToken': json['amount_token'],
        'amountUsd': json['amount_usd'],
        'amountNative': json['amount_native'],
    };
}

export function TokenAmountResponseToJSON(json: any): TokenAmountResponse {
    return TokenAmountResponseToJSONTyped(json, false);
}

export function TokenAmountResponseToJSONTyped(value?: TokenAmountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'amount_token': value['amountToken'],
        'amount_usd': value['amountUsd'],
        'amount_native': value['amountNative'],
    };
}

