/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Social media links for a token
 * @export
 * @interface TokenSocialsResponse
 */
export interface TokenSocialsResponse {
    /**
     * The token's website URL
     * @type {string}
     * @memberof TokenSocialsResponse
     */
    website?: string;
    /**
     * The token's Twitter/X handle
     * @type {string}
     * @memberof TokenSocialsResponse
     */
    twitterHandle?: string;
    /**
     * The token's Telegram identifier
     * @type {string}
     * @memberof TokenSocialsResponse
     */
    telegramIdentifier?: string;
}

/**
 * Check if a given object implements the TokenSocialsResponse interface.
 */
export function instanceOfTokenSocialsResponse(value: object): value is TokenSocialsResponse {
    return true;
}

export function TokenSocialsResponseFromJSON(json: any): TokenSocialsResponse {
    return TokenSocialsResponseFromJSONTyped(json, false);
}

export function TokenSocialsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSocialsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'website': json['website'] == null ? undefined : json['website'],
        'twitterHandle': json['twitter_handle'] == null ? undefined : json['twitter_handle'],
        'telegramIdentifier': json['telegram_identifier'] == null ? undefined : json['telegram_identifier'],
    };
}

export function TokenSocialsResponseToJSON(json: any): TokenSocialsResponse {
    return TokenSocialsResponseToJSONTyped(json, false);
}

export function TokenSocialsResponseToJSONTyped(value?: TokenSocialsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'website': value['website'],
        'twitter_handle': value['twitterHandle'],
        'telegram_identifier': value['telegramIdentifier'],
    };
}

