/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenSocialsResponse } from './TokenSocialsResponse';
import {
    TokenSocialsResponseFromJSON,
    TokenSocialsResponseFromJSONTyped,
    TokenSocialsResponseToJSON,
    TokenSocialsResponseToJSONTyped,
} from './TokenSocialsResponse';
import type { TokenStatsResponse } from './TokenStatsResponse';
import {
    TokenStatsResponseFromJSON,
    TokenStatsResponseFromJSONTyped,
    TokenStatsResponseToJSON,
    TokenStatsResponseToJSONTyped,
} from './TokenStatsResponse';

/**
 * Detailed token information including stats and social links
 * @export
 * @interface TokenDetailedResponse
 */
export interface TokenDetailedResponse {
    /**
     * The contract address of the token
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    address: string;
    /**
     * The blockchain the token is on
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    chain: string;
    /**
     * The display name of the token
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    name: string;
    /**
     * The ticker symbol of the token
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    symbol: string;
    /**
     * URL of the token's image
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    imageUrl?: string;
    /**
     * Current price in USD
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    usdPrice: string;
    /**
     * Number of decimal places
     * @type {number}
     * @memberof TokenDetailedResponse
     */
    decimals: number;
    /**
     * URL to the token page on OpenSea
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    openseaUrl: string;
    /**
     * A description of the token
     * @type {string}
     * @memberof TokenDetailedResponse
     */
    description?: string;
    /**
     * Market statistics for the token
     * @type {TokenStatsResponse}
     * @memberof TokenDetailedResponse
     */
    stats?: TokenStatsResponse;
    /**
     * Social media links for the token
     * @type {TokenSocialsResponse}
     * @memberof TokenDetailedResponse
     */
    socials?: TokenSocialsResponse;
    /**
     * Token safety status based on OpenSea's spam-classification rules. `OK` for tokens that pass all safety checks (the normal case). Categories are intentionally broad and may evolve. Possible values, in decreasing severity: `WARNING` (flagged as risky/suspicious — caution advised), `SPAM` (flagged as spam), `LOW_LIQUIDITY` (insufficient liquidity pool reserves), `OK` (passes all checks).
     * @type {TokenDetailedResponseStatusEnum}
     * @memberof TokenDetailedResponse
     */
    status?: TokenDetailedResponseStatusEnum;
}


/**
 * @export
 */
export const TokenDetailedResponseStatusEnum = {
    Ok: 'OK',
    Warning: 'WARNING',
    Spam: 'SPAM',
    LowLiquidity: 'LOW_LIQUIDITY'
} as const;
export type TokenDetailedResponseStatusEnum = typeof TokenDetailedResponseStatusEnum[keyof typeof TokenDetailedResponseStatusEnum];


/**
 * Check if a given object implements the TokenDetailedResponse interface.
 */
export function instanceOfTokenDetailedResponse(value: object): value is TokenDetailedResponse {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('usdPrice' in value) || value['usdPrice'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('openseaUrl' in value) || value['openseaUrl'] === undefined) return false;
    return true;
}

export function TokenDetailedResponseFromJSON(json: any): TokenDetailedResponse {
    return TokenDetailedResponseFromJSONTyped(json, false);
}

export function TokenDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDetailedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chain': json['chain'],
        'name': json['name'],
        'symbol': json['symbol'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'usdPrice': json['usd_price'],
        'decimals': json['decimals'],
        'openseaUrl': json['opensea_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'stats': json['stats'] == null ? undefined : TokenStatsResponseFromJSON(json['stats']),
        'socials': json['socials'] == null ? undefined : TokenSocialsResponseFromJSON(json['socials']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TokenDetailedResponseToJSON(json: any): TokenDetailedResponse {
    return TokenDetailedResponseToJSONTyped(json, false);
}

export function TokenDetailedResponseToJSONTyped(value?: TokenDetailedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'name': value['name'],
        'symbol': value['symbol'],
        'image_url': value['imageUrl'],
        'usd_price': value['usdPrice'],
        'decimals': value['decimals'],
        'opensea_url': value['openseaUrl'],
        'description': value['description'],
        'stats': TokenStatsResponseToJSON(value['stats']),
        'socials': TokenSocialsResponseToJSON(value['socials']),
        'status': value['status'],
    };
}

