/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Total
 */
export interface Total {
    /**
     * 
     * @type {number}
     * @memberof Total
     */
    volume: number;
    /**
     * 
     * @type {number}
     * @memberof Total
     */
    sales: number;
    /**
     * 
     * @type {number}
     * @memberof Total
     */
    numOwners: number;
    /**
     * 
     * @type {number}
     * @memberof Total
     */
    floorPrice: number;
    /**
     * 
     * @type {string}
     * @memberof Total
     */
    floorPriceSymbol: string;
}

/**
 * Check if a given object implements the Total interface.
 */
export function instanceOfTotal(value: object): value is Total {
    if (!('volume' in value) || value['volume'] === undefined) return false;
    if (!('sales' in value) || value['sales'] === undefined) return false;
    if (!('numOwners' in value) || value['numOwners'] === undefined) return false;
    if (!('floorPrice' in value) || value['floorPrice'] === undefined) return false;
    if (!('floorPriceSymbol' in value) || value['floorPriceSymbol'] === undefined) return false;
    return true;
}

export function TotalFromJSON(json: any): Total {
    return TotalFromJSONTyped(json, false);
}

export function TotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Total {
    if (json == null) {
        return json;
    }
    return {
        
        'volume': json['volume'],
        'sales': json['sales'],
        'numOwners': json['num_owners'],
        'floorPrice': json['floor_price'],
        'floorPriceSymbol': json['floor_price_symbol'],
    };
}

export function TotalToJSON(json: any): Total {
    return TotalToJSONTyped(json, false);
}

export function TotalToJSONTyped(value?: Total | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'volume': value['volume'],
        'sales': value['sales'],
        'num_owners': value['numOwners'],
        'floor_price': value['floorPrice'],
        'floor_price_symbol': value['floorPriceSymbol'],
    };
}

