/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Trait
 */
export interface Trait {
    /**
     * 
     * @type {string}
     * @memberof Trait
     */
    traitType: string;
    /**
     * 
     * @type {string}
     * @memberof Trait
     */
    displayType?: string;
    /**
     * 
     * @type {string}
     * @memberof Trait
     */
    maxValue?: string;
    /**
     * 
     * @type {any}
     * @memberof Trait
     */
    value: any | null;
}

/**
 * Check if a given object implements the Trait interface.
 */
export function instanceOfTrait(value: object): value is Trait {
    if (!('traitType' in value) || value['traitType'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TraitFromJSON(json: any): Trait {
    return TraitFromJSONTyped(json, false);
}

export function TraitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trait {
    if (json == null) {
        return json;
    }
    return {
        
        'traitType': json['trait_type'],
        'displayType': json['display_type'] == null ? undefined : json['display_type'],
        'maxValue': json['max_value'] == null ? undefined : json['max_value'],
        'value': json['value'],
    };
}

export function TraitToJSON(json: any): Trait {
    return TraitToJSONTyped(json, false);
}

export function TraitToJSONTyped(value?: Trait | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trait_type': value['traitType'],
        'display_type': value['displayType'],
        'max_value': value['maxValue'],
        'value': value['value'],
    };
}

