/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraitObject
 */
export interface TraitObject {
    /**
     * 
     * @type {string}
     * @memberof TraitObject
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TraitObject
     */
    value: string;
}

/**
 * Check if a given object implements the TraitObject interface.
 */
export function instanceOfTraitObject(value: object): value is TraitObject {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TraitObjectFromJSON(json: any): TraitObject {
    return TraitObjectFromJSONTyped(json, false);
}

export function TraitObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraitObject {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function TraitObjectToJSON(json: any): TraitObject {
    return TraitObjectToJSONTyped(json, false);
}

export function TraitObjectToJSONTyped(value?: TraitObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

