/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraitCriteria
 */
export interface TraitCriteria {
    /**
     * 
     * @type {string}
     * @memberof TraitCriteria
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TraitCriteria
     */
    value: string;
}

/**
 * Check if a given object implements the TraitCriteria interface.
 */
export function instanceOfTraitCriteria(value: object): value is TraitCriteria {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TraitCriteriaFromJSON(json: any): TraitCriteria {
    return TraitCriteriaFromJSONTyped(json, false);
}

export function TraitCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraitCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function TraitCriteriaToJSON(json: any): TraitCriteria {
    return TraitCriteriaToJSONTyped(json, false);
}

export function TraitCriteriaToJSONTyped(value?: TraitCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

