/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A transaction identifier with optional swap provider
 * @export
 * @interface TransactionIdentifierInput
 */
export interface TransactionIdentifierInput {
    /**
     * The transaction hash
     * @type {string}
     * @memberof TransactionIdentifierInput
     */
    transactionHash: string;
    /**
     * The blockchain chain
     * @type {string}
     * @memberof TransactionIdentifierInput
     */
    chain: string;
    /**
     * The swap provider used (e.g. RELAY, JUPITER, ZERO_EX, LOCAL_BUY_NFT). Required when relay_request_id is not provided. Can be omitted for cross-chain flows that use relay_request_id.
     * @type {string}
     * @memberof TransactionIdentifierInput
     */
    swapProvider?: string;
}

/**
 * Check if a given object implements the TransactionIdentifierInput interface.
 */
export function instanceOfTransactionIdentifierInput(value: object): value is TransactionIdentifierInput {
    if (!('transactionHash' in value) || value['transactionHash'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    return true;
}

export function TransactionIdentifierInputFromJSON(json: any): TransactionIdentifierInput {
    return TransactionIdentifierInputFromJSONTyped(json, false);
}

export function TransactionIdentifierInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIdentifierInput {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionHash': json['transaction_hash'],
        'chain': json['chain'],
        'swapProvider': json['swap_provider'] == null ? undefined : json['swap_provider'],
    };
}

export function TransactionIdentifierInputToJSON(json: any): TransactionIdentifierInput {
    return TransactionIdentifierInputToJSONTyped(json, false);
}

export function TransactionIdentifierInputToJSONTyped(value?: TransactionIdentifierInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_hash': value['transactionHash'],
        'chain': value['chain'],
        'swap_provider': value['swapProvider'],
    };
}

