/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An asset to transfer
 * @export
 * @interface TransferAsset
 */
export interface TransferAsset {
    /**
     * The chain the asset is on (e.g. ethereum, base, solana)
     * @type {string}
     * @memberof TransferAsset
     */
    chain: string;
    /**
     * The contract address of the asset
     * @type {string}
     * @memberof TransferAsset
     */
    contract: string;
    /**
     * The token ID of the asset
     * @type {string}
     * @memberof TransferAsset
     */
    tokenId: string;
    /**
     * The quantity to transfer in raw units (1 for ERC721, raw amount for ERC1155/fungible)
     * @type {string}
     * @memberof TransferAsset
     */
    quantity: string;
}

/**
 * Check if a given object implements the TransferAsset interface.
 */
export function instanceOfTransferAsset(value: object): value is TransferAsset {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function TransferAssetFromJSON(json: any): TransferAsset {
    return TransferAssetFromJSONTyped(json, false);
}

export function TransferAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contract': json['contract'],
        'tokenId': json['token_id'],
        'quantity': json['quantity'],
    };
}

export function TransferAssetToJSON(json: any): TransferAsset {
    return TransferAssetToJSONTyped(json, false);
}

export function TransferAssetToJSONTyped(value?: TransferAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contract': value['contract'],
        'token_id': value['tokenId'],
        'quantity': value['quantity'],
    };
}

