/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionDataInputData } from './TransactionDataInputData';
import {
    TransactionDataInputDataFromJSON,
    TransactionDataInputDataFromJSONTyped,
    TransactionDataInputDataToJSON,
    TransactionDataInputDataToJSONTyped,
} from './TransactionDataInputData';

/**
 * 
 * @export
 * @interface TransactionData
 */
export interface TransactionData {
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    _function: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionData
     */
    chain: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    value: string;
    /**
     * 
     * @type {TransactionDataInputData}
     * @memberof TransactionData
     */
    inputData: TransactionDataInputData;
}

/**
 * Check if a given object implements the TransactionData interface.
 */
export function instanceOfTransactionData(value: object): value is TransactionData {
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('inputData' in value) || value['inputData'] === undefined) return false;
    return true;
}

export function TransactionDataFromJSON(json: any): TransactionData {
    return TransactionDataFromJSONTyped(json, false);
}

export function TransactionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionData {
    if (json == null) {
        return json;
    }
    return {
        
        '_function': json['function'],
        'chain': json['chain'],
        'to': json['to'],
        'value': json['value'],
        'inputData': TransactionDataInputDataFromJSON(json['input_data']),
    };
}

export function TransactionDataToJSON(json: any): TransactionData {
    return TransactionDataToJSONTyped(json, false);
}

export function TransactionDataToJSONTyped(value?: TransactionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'function': value['_function'],
        'chain': value['chain'],
        'to': value['to'],
        'value': value['value'],
        'input_data': TransactionDataInputDataToJSON(value['inputData']),
    };
}

