/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FulfillAdvancedOrder } from './FulfillAdvancedOrder';
import {
    instanceOfFulfillAdvancedOrder,
    FulfillAdvancedOrderFromJSON,
    FulfillAdvancedOrderFromJSONTyped,
    FulfillAdvancedOrderToJSON,
} from './FulfillAdvancedOrder';
import type { FulfillAvailableAdvancedOrders } from './FulfillAvailableAdvancedOrders';
import {
    instanceOfFulfillAvailableAdvancedOrders,
    FulfillAvailableAdvancedOrdersFromJSON,
    FulfillAvailableAdvancedOrdersFromJSONTyped,
    FulfillAvailableAdvancedOrdersToJSON,
} from './FulfillAvailableAdvancedOrders';
import type { FulfillAvailableOrders } from './FulfillAvailableOrders';
import {
    instanceOfFulfillAvailableOrders,
    FulfillAvailableOrdersFromJSON,
    FulfillAvailableOrdersFromJSONTyped,
    FulfillAvailableOrdersToJSON,
} from './FulfillAvailableOrders';
import type { FulfillBasicOrder } from './FulfillBasicOrder';
import {
    instanceOfFulfillBasicOrder,
    FulfillBasicOrderFromJSON,
    FulfillBasicOrderFromJSONTyped,
    FulfillBasicOrderToJSON,
} from './FulfillBasicOrder';
import type { FulfillOrder } from './FulfillOrder';
import {
    instanceOfFulfillOrder,
    FulfillOrderFromJSON,
    FulfillOrderFromJSONTyped,
    FulfillOrderToJSON,
} from './FulfillOrder';
import type { MatchAdvancedOrders } from './MatchAdvancedOrders';
import {
    instanceOfMatchAdvancedOrders,
    MatchAdvancedOrdersFromJSON,
    MatchAdvancedOrdersFromJSONTyped,
    MatchAdvancedOrdersToJSON,
} from './MatchAdvancedOrders';
import type { MatchOrders } from './MatchOrders';
import {
    instanceOfMatchOrders,
    MatchOrdersFromJSON,
    MatchOrdersFromJSONTyped,
    MatchOrdersToJSON,
} from './MatchOrders';

/**
 * @type TransactionDataInputData
 * 
 * @export
 */
export type TransactionDataInputData = FulfillAdvancedOrder | FulfillAvailableAdvancedOrders | FulfillAvailableOrders | FulfillBasicOrder | FulfillOrder | MatchAdvancedOrders | MatchOrders;

export function TransactionDataInputDataFromJSON(json: any): TransactionDataInputData {
    return TransactionDataInputDataFromJSONTyped(json, false);
}

export function TransactionDataInputDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDataInputData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfFulfillAdvancedOrder(json)) {
        return FulfillAdvancedOrderFromJSONTyped(json, true);
    }
    if (instanceOfFulfillAvailableAdvancedOrders(json)) {
        return FulfillAvailableAdvancedOrdersFromJSONTyped(json, true);
    }
    if (instanceOfFulfillAvailableOrders(json)) {
        return FulfillAvailableOrdersFromJSONTyped(json, true);
    }
    if (instanceOfFulfillBasicOrder(json)) {
        return FulfillBasicOrderFromJSONTyped(json, true);
    }
    if (instanceOfFulfillOrder(json)) {
        return FulfillOrderFromJSONTyped(json, true);
    }
    if (instanceOfMatchAdvancedOrders(json)) {
        return MatchAdvancedOrdersFromJSONTyped(json, true);
    }
    if (instanceOfMatchOrders(json)) {
        return MatchOrdersFromJSONTyped(json, true);
    }
    return {} as any;
}

export function TransactionDataInputDataToJSON(json: any): any {
    return TransactionDataInputDataToJSONTyped(json, false);
}

export function TransactionDataInputDataToJSONTyped(value?: TransactionDataInputData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfFulfillAdvancedOrder(value)) {
        return FulfillAdvancedOrderToJSON(value as FulfillAdvancedOrder);
    }
    if (instanceOfFulfillAvailableAdvancedOrders(value)) {
        return FulfillAvailableAdvancedOrdersToJSON(value as FulfillAvailableAdvancedOrders);
    }
    if (instanceOfFulfillAvailableOrders(value)) {
        return FulfillAvailableOrdersToJSON(value as FulfillAvailableOrders);
    }
    if (instanceOfFulfillBasicOrder(value)) {
        return FulfillBasicOrderToJSON(value as FulfillBasicOrder);
    }
    if (instanceOfFulfillOrder(value)) {
        return FulfillOrderToJSON(value as FulfillOrder);
    }
    if (instanceOfMatchAdvancedOrders(value)) {
        return MatchAdvancedOrdersToJSON(value as MatchAdvancedOrders);
    }
    if (instanceOfMatchOrders(value)) {
        return MatchOrdersToJSON(value as MatchOrders);
    }
    return {};
}

