/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionIdentifierInput } from './TransactionIdentifierInput';
import {
    TransactionIdentifierInputFromJSON,
    TransactionIdentifierInputFromJSONTyped,
    TransactionIdentifierInputToJSON,
    TransactionIdentifierInputToJSONTyped,
} from './TransactionIdentifierInput';
import type { SwapQuoteInput } from './SwapQuoteInput';
import {
    SwapQuoteInputFromJSON,
    SwapQuoteInputFromJSONTyped,
    SwapQuoteInputToJSON,
    SwapQuoteInputToJSONTyped,
} from './SwapQuoteInput';

/**
 * Request to get a transaction receipt/status
 * @export
 * @interface TransactionReceiptRequest
 */
export interface TransactionReceiptRequest {
    /**
     * Transaction identifiers to look up
     * @type {Array<TransactionIdentifierInput>}
     * @memberof TransactionReceiptRequest
     */
    transactionIdentifiers?: Array<TransactionIdentifierInput>;
    /**
     * The swap quote that was originally submitted
     * @type {SwapQuoteInput}
     * @memberof TransactionReceiptRequest
     */
    swapQuote: SwapQuoteInput;
    /**
     * Relay request ID for cross-chain tracking
     * @type {string}
     * @memberof TransactionReceiptRequest
     */
    relayRequestId?: string;
    /**
     * Request ID for workflow tracking
     * @type {string}
     * @memberof TransactionReceiptRequest
     */
    requestId?: string;
}

/**
 * Check if a given object implements the TransactionReceiptRequest interface.
 */
export function instanceOfTransactionReceiptRequest(value: object): value is TransactionReceiptRequest {
    if (!('swapQuote' in value) || value['swapQuote'] === undefined) return false;
    return true;
}

export function TransactionReceiptRequestFromJSON(json: any): TransactionReceiptRequest {
    return TransactionReceiptRequestFromJSONTyped(json, false);
}

export function TransactionReceiptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionReceiptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionIdentifiers': json['transaction_identifiers'] == null ? undefined : ((json['transaction_identifiers'] as Array<any>).map(TransactionIdentifierInputFromJSON)),
        'swapQuote': SwapQuoteInputFromJSON(json['swap_quote']),
        'relayRequestId': json['relay_request_id'] == null ? undefined : json['relay_request_id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function TransactionReceiptRequestToJSON(json: any): TransactionReceiptRequest {
    return TransactionReceiptRequestToJSONTyped(json, false);
}

export function TransactionReceiptRequestToJSONTyped(value?: TransactionReceiptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_identifiers': value['transactionIdentifiers'] == null ? undefined : ((value['transactionIdentifiers'] as Array<any>).map(TransactionIdentifierInputToJSON)),
        'swap_quote': SwapQuoteInputToJSON(value['swapQuote']),
        'relay_request_id': value['relayRequestId'],
        'request_id': value['requestId'],
    };
}

