/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateMetadataAssetIdentifier
 */
export interface ValidateMetadataAssetIdentifier {
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAssetIdentifier
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAssetIdentifier
     */
    contractAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAssetIdentifier
     */
    tokenId: string;
}

/**
 * Check if a given object implements the ValidateMetadataAssetIdentifier interface.
 */
export function instanceOfValidateMetadataAssetIdentifier(value: object): value is ValidateMetadataAssetIdentifier {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('contractAddress' in value) || value['contractAddress'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    return true;
}

export function ValidateMetadataAssetIdentifierFromJSON(json: any): ValidateMetadataAssetIdentifier {
    return ValidateMetadataAssetIdentifierFromJSONTyped(json, false);
}

export function ValidateMetadataAssetIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateMetadataAssetIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'contractAddress': json['contractAddress'],
        'tokenId': json['tokenId'],
    };
}

export function ValidateMetadataAssetIdentifierToJSON(json: any): ValidateMetadataAssetIdentifier {
    return ValidateMetadataAssetIdentifierToJSONTyped(json, false);
}

export function ValidateMetadataAssetIdentifierToJSONTyped(value?: ValidateMetadataAssetIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contractAddress': value['contractAddress'],
        'tokenId': value['tokenId'],
    };
}

