/* tslint:disable */
/* eslint-disable */
/**
 * OpenSea API
 * The API for OpenSea
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@opensea.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateMetadataAttribute
 */
export interface ValidateMetadataAttribute {
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAttribute
     */
    traitType: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAttribute
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateMetadataAttribute
     */
    displayType?: string;
}

/**
 * Check if a given object implements the ValidateMetadataAttribute interface.
 */
export function instanceOfValidateMetadataAttribute(value: object): value is ValidateMetadataAttribute {
    if (!('traitType' in value) || value['traitType'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ValidateMetadataAttributeFromJSON(json: any): ValidateMetadataAttribute {
    return ValidateMetadataAttributeFromJSONTyped(json, false);
}

export function ValidateMetadataAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateMetadataAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'traitType': json['traitType'],
        'value': json['value'],
        'displayType': json['displayType'] == null ? undefined : json['displayType'],
    };
}

export function ValidateMetadataAttributeToJSON(json: any): ValidateMetadataAttribute {
    return ValidateMetadataAttributeToJSONTyped(json, false);
}

export function ValidateMetadataAttributeToJSONTyped(value?: ValidateMetadataAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'traitType': value['traitType'],
        'value': value['value'],
        'displayType': value['displayType'],
    };
}

